import type { Locale } from "@/lib/types";

export type WebLiteLocale = Locale;

const zh = {
  documentTitle: "歌词卡片生成器 · Web Lite",
  badge: "Web Lite",
  headerDesktop: "下载桌面版",
  headerRepository: "GitHub 仓库",
  clearAll: "清空内容",
  clearAlreadyEmpty: "卡片已经是空的。",
  language: "界面语言",
  songStep: "歌曲信息",
  songStepDescription: "手动填写歌曲信息并添加可导出的封面。",
  remoteCover: "远程封面 URL",
  remoteCoverPlaceholder: "https://example.com/cover.jpg",
  applyRemoteCover: "使用远程封面",
  checkingRemoteCover: "正在检查封面是否可以导出…",
  remoteCoverReady: "封面已就绪，可用于预览、取色和导出。",
  remoteCoverHttpsOnly: "远程封面必须使用 HTTPS 地址。",
  remoteCoverFailed: "无法读取这张图片。请上传本地图片，或改用允许 CORS 的图片地址。",
  localCoverReady: "本地封面只在当前标签页中使用，不会上传。",
  uploadCover: "上传本地封面",
  coverHint: "本地图片最稳定；远程图片必须允许匿名跨域读取。",
  noticeTitle: "Web Lite 功能范围",
  noticeBody: "Web Lite 支持手动编辑、实时预览和本地 PNG、WebP、JPG 导出。歌曲搜索、音乐链接解析、本地音频信息、在线歌词和 AI 翻译请使用桌面版。",
  downloadDesktop: "下载桌面版",
  fontTitle: "字体方案",
  fontDescription: "内置字体的输出更一致；系统字体会因设备而异。",
  sourceHanSans: "思源黑体",
  sourceHanSerif: "思源宋体",
  systemSans: "系统无衬线字体",
  systemSerif: "系统衬线字体",
  stableFont: "内置 · 输出一致",
  deviceFont: "系统字体 · 因设备而异",
  selected: "已选择",
  exportStandard: "标准",
  exportHigh: "高清",
  exportReady: "图片已开始下载。",
  exportFailed: "图片导出失败。请检查封面后重试。",
  remoteCoverApplyFailed: "封面检查失败，请改为上传本地图片。"
};

type WebLiteCopyShape = typeof zh;

export const webLiteCopy: Record<WebLiteLocale, WebLiteCopyShape> = {
  zh,
  "zh-TW": {
    documentTitle: "歌詞卡片產生器 · Web Lite",
    badge: "Web Lite",
    headerDesktop: "下載桌面版",
    headerRepository: "GitHub 專案",
    clearAll: "清除內容",
    clearAlreadyEmpty: "卡片已經是空的。",
    language: "介面語言",
    songStep: "歌曲資訊",
    songStepDescription: "手動填寫歌曲資訊，並加入可匯出的封面。",
    remoteCover: "遠端封面 URL",
    remoteCoverPlaceholder: "https://example.com/cover.jpg",
    applyRemoteCover: "使用遠端封面",
    checkingRemoteCover: "正在檢查封面是否能夠匯出…",
    remoteCoverReady: "封面已就緒，可用於預覽、取色與匯出。",
    remoteCoverHttpsOnly: "遠端封面必須使用 HTTPS 網址。",
    remoteCoverFailed: "無法讀取這張圖片。請上傳本機圖片，或改用允許 CORS 的圖片網址。",
    localCoverReady: "本機封面只會在目前分頁中使用，不會上傳。",
    uploadCover: "上傳本機封面",
    coverHint: "本機圖片最穩定；遠端圖片必須允許匿名跨來源讀取。",
    noticeTitle: "Web Lite 功能範圍",
    noticeBody: "Web Lite 支援手動編輯、即時預覽與本機 PNG、WebP、JPG 匯出。歌曲搜尋、音樂連結解析、本機音訊資訊、線上歌詞與 AI 翻譯請使用桌面版。",
    downloadDesktop: "下載桌面版",
    fontTitle: "字型方案",
    fontDescription: "內建字型的輸出較一致；系統字型會因裝置而異。",
    sourceHanSans: "思源黑體",
    sourceHanSerif: "思源宋體",
    systemSans: "系統無襯線字型",
    systemSerif: "系統襯線字型",
    stableFont: "內建 · 輸出一致",
    deviceFont: "系統字型 · 因裝置而異",
    selected: "已選取",
    exportStandard: "標準",
    exportHigh: "高畫質",
    exportReady: "圖片已開始下載。",
    exportFailed: "圖片匯出失敗。請檢查封面後再試一次。",
    remoteCoverApplyFailed: "封面檢查失敗，請改為上傳本機圖片。"
  },
  en: {
    documentTitle: "Lyrics Card Generator · Web Lite",
    badge: "Web Lite",
    headerDesktop: "Download desktop app",
    headerRepository: "GitHub repository",
    clearAll: "Clear content",
    clearAlreadyEmpty: "The card is already empty.",
    language: "Interface language",
    songStep: "Song info",
    songStepDescription: "Enter song details and add a cover that can be exported.",
    remoteCover: "Remote cover URL",
    remoteCoverPlaceholder: "https://example.com/cover.jpg",
    applyRemoteCover: "Use remote cover",
    checkingRemoteCover: "Checking whether the cover can be exported…",
    remoteCoverReady: "The remote cover is safe to preview, sample, and export.",
    remoteCoverHttpsOnly: "Remote covers must use an HTTPS URL.",
    remoteCoverFailed: "This image could not be read. Upload it locally or use an image URL that allows CORS.",
    localCoverReady: "The local cover stays in this tab and is not uploaded.",
    uploadCover: "Upload local cover",
    coverHint: "Local images are most reliable. Remote images must allow anonymous cross-origin access.",
    noticeTitle: "What Web Lite supports",
    noticeBody: "Web Lite supports manual editing, live preview, and local PNG, WebP, and JPG export. Use the desktop app for song search, music-link parsing, local-audio metadata, online lyrics, and AI translation.",
    downloadDesktop: "Download desktop app",
    fontTitle: "Font scheme",
    fontDescription: "Bundled fonts produce consistent output; system fonts vary by device.",
    sourceHanSans: "Source Han Sans",
    sourceHanSerif: "Source Han Serif",
    systemSans: "System sans serif",
    systemSerif: "System serif",
    stableFont: "Bundled · consistent output",
    deviceFont: "System font · varies by device",
    selected: "Selected",
    exportStandard: "Standard",
    exportHigh: "High",
    exportReady: "Image download started.",
    exportFailed: "Image export failed. Check the cover and try again.",
    remoteCoverApplyFailed: "The cover check failed. Upload the image locally instead."
  },
  fr: {
    documentTitle: "Générateur de cartes de paroles · Web Lite",
    badge: "Web Lite",
    headerDesktop: "Télécharger l’application",
    headerRepository: "Dépôt GitHub",
    clearAll: "Effacer le contenu",
    clearAlreadyEmpty: "La carte est déjà vide.",
    language: "Langue de l’interface",
    songStep: "Informations sur le morceau",
    songStepDescription: "Saisissez les informations du morceau et ajoutez une pochette exportable.",
    remoteCover: "URL de la pochette",
    remoteCoverPlaceholder: "https://example.com/cover.jpg",
    applyRemoteCover: "Utiliser cette pochette",
    checkingRemoteCover: "Vérification de la pochette…",
    remoteCoverReady: "La pochette peut être prévisualisée, analysée et exportée.",
    remoteCoverHttpsOnly: "L’adresse de la pochette doit utiliser HTTPS.",
    remoteCoverFailed: "Impossible de lire cette image. Importez-la depuis l’appareil ou utilisez une URL qui autorise CORS.",
    localCoverReady: "La pochette locale reste dans cet onglet et n’est pas envoyée en ligne.",
    uploadCover: "Importer une pochette",
    coverHint: "Une image locale est plus fiable. Une image distante doit autoriser l’accès anonyme entre origines.",
    noticeTitle: "Fonctions de Web Lite",
    noticeBody: "Web Lite permet la saisie manuelle, l’aperçu en direct et l’export local en PNG, WebP et JPG. Utilisez l’application de bureau pour la recherche de morceaux, l’analyse de liens, les métadonnées audio locales, les paroles en ligne et la traduction par IA.",
    downloadDesktop: "Télécharger l’application de bureau",
    fontTitle: "Jeu de polices",
    fontDescription: "Les polices intégrées donnent un résultat constant ; les polices système varient selon l’appareil.",
    sourceHanSans: "Source Han Sans",
    sourceHanSerif: "Source Han Serif",
    systemSans: "Sans serif du système",
    systemSerif: "Serif du système",
    stableFont: "Intégrée · résultat constant",
    deviceFont: "Police système · selon l’appareil",
    selected: "Sélectionnée",
    exportStandard: "Standard",
    exportHigh: "Élevée",
    exportReady: "Le téléchargement de l’image a commencé.",
    exportFailed: "Échec de l’export de l’image. Vérifiez la pochette et réessayez.",
    remoteCoverApplyFailed: "La vérification de la pochette a échoué. Importez plutôt une image locale."
  },
  ja: {
    documentTitle: "歌詞カードジェネレーター · Web Lite",
    badge: "Web Lite",
    headerDesktop: "デスクトップ版をダウンロード",
    headerRepository: "GitHub リポジトリ",
    clearAll: "内容を消去",
    clearAlreadyEmpty: "カードはすでに空です。",
    language: "表示言語",
    songStep: "曲の情報",
    songStepDescription: "曲の情報を入力し、書き出し可能なジャケット画像を追加します。",
    remoteCover: "ジャケット画像の URL",
    remoteCoverPlaceholder: "https://example.com/cover.jpg",
    applyRemoteCover: "この画像を使う",
    checkingRemoteCover: "画像を書き出せるか確認しています…",
    remoteCoverReady: "プレビュー、色の抽出、書き出しに使用できます。",
    remoteCoverHttpsOnly: "画像の URL は HTTPS で指定してください。",
    remoteCoverFailed: "この画像を読み込めませんでした。端末からアップロードするか、CORS を許可する URL を使用してください。",
    localCoverReady: "端末の画像はこのタブ内だけで使用され、アップロードされません。",
    uploadCover: "画像をアップロード",
    coverHint: "端末の画像が最も確実です。外部画像は匿名のクロスオリジンアクセスを許可している必要があります。",
    noticeTitle: "Web Lite で使える機能",
    noticeBody: "Web Lite では手動編集、リアルタイムプレビュー、端末への PNG、WebP、JPG 書き出しができます。曲の検索、音楽リンクの解析、音声ファイルの情報、オンライン歌詞、AI 翻訳にはデスクトップ版を使用してください。",
    downloadDesktop: "デスクトップ版をダウンロード",
    fontTitle: "フォント設定",
    fontDescription: "内蔵フォントは同じ結果になります。システムフォントは端末によって変わります。",
    sourceHanSans: "源ノ角ゴシック",
    sourceHanSerif: "源ノ明朝",
    systemSans: "システムゴシック",
    systemSerif: "システム明朝",
    stableFont: "内蔵 · 安定した出力",
    deviceFont: "システムフォント · 端末に依存",
    selected: "選択中",
    exportStandard: "標準",
    exportHigh: "高画質",
    exportReady: "画像のダウンロードを開始しました。",
    exportFailed: "画像の書き出しに失敗しました。画像を確認して、もう一度お試しください。",
    remoteCoverApplyFailed: "画像の確認に失敗しました。端末からアップロードしてください。"
  },
  es: {
    documentTitle: "Generador de tarjetas de letras · Web Lite",
    badge: "Web Lite",
    headerDesktop: "Descargar aplicación",
    headerRepository: "Repositorio de GitHub",
    clearAll: "Borrar contenido",
    clearAlreadyEmpty: "La tarjeta ya está vacía.",
    language: "Idioma de la interfaz",
    songStep: "Información de la canción",
    songStepDescription: "Escribe los datos de la canción y añade una portada que se pueda exportar.",
    remoteCover: "URL de la portada",
    remoteCoverPlaceholder: "https://example.com/cover.jpg",
    applyRemoteCover: "Usar esta portada",
    checkingRemoteCover: "Comprobando si se puede exportar la portada…",
    remoteCoverReady: "La portada está lista para previsualizarla, extraer colores y exportarla.",
    remoteCoverHttpsOnly: "La URL de la portada debe usar HTTPS.",
    remoteCoverFailed: "No se pudo leer esta imagen. Súbela desde el dispositivo o usa una URL que permita CORS.",
    localCoverReady: "La portada local permanece en esta pestaña y no se sube.",
    uploadCover: "Subir portada",
    coverHint: "Las imágenes locales son más fiables. Las remotas deben permitir el acceso anónimo entre orígenes.",
    noticeTitle: "Funciones de Web Lite",
    noticeBody: "Web Lite permite editar manualmente, ver los cambios al instante y exportar archivos PNG, WebP y JPG de forma local. Usa la aplicación de escritorio para buscar canciones, analizar enlaces, leer metadatos de audio local, obtener letras en línea y traducir con IA.",
    downloadDesktop: "Descargar aplicación de escritorio",
    fontTitle: "Conjunto de fuentes",
    fontDescription: "Las fuentes incluidas mantienen el resultado; las del sistema varían según el dispositivo.",
    sourceHanSans: "Source Han Sans",
    sourceHanSerif: "Source Han Serif",
    systemSans: "Sans serif del sistema",
    systemSerif: "Serif del sistema",
    stableFont: "Incluida · resultado uniforme",
    deviceFont: "Fuente del sistema · depende del dispositivo",
    selected: "Seleccionada",
    exportStandard: "Estándar",
    exportHigh: "Alta",
    exportReady: "Se inició la descarga de la imagen.",
    exportFailed: "No se pudo exportar la imagen. Revisa la portada e inténtalo de nuevo.",
    remoteCoverApplyFailed: "No se pudo comprobar la portada. Súbela desde el dispositivo."
  }
};

export type WebLiteCopy = WebLiteCopyShape;

export function detectWebLiteLocale(language: string): WebLiteLocale {
  const normalized = language.trim().toLowerCase().replace(/_/g, "-");
  if (/^zh-(tw|hk|mo|hant)(?:-|$)/.test(normalized)) return "zh-TW";
  if (normalized === "zh-hant") return "zh-TW";
  if (normalized.startsWith("zh")) return "zh";
  if (normalized.startsWith("fr")) return "fr";
  if (normalized.startsWith("ja")) return "ja";
  if (normalized.startsWith("es")) return "es";
  return "en";
}

export function isWebLiteLocale(value: unknown): value is WebLiteLocale {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(webLiteCopy, value);
}
