import type { Locale } from "@/lib/types";

export type WebLiteLocale = Extract<Locale, "zh" | "en">;

export const webLiteCopy = {
  zh: {
    badge: "Web Lite",
    headerDesktop: "下载桌面版",
    headerRepository: "GitHub 仓库",
    clearAll: "一键清空",
    language: "界面语言",
    songStep: "歌曲信息",
    songStepDescription: "手动填写歌曲信息并添加可安全导出的封面。",
    remoteCover: "远程封面 URL",
    remoteCoverPlaceholder: "https://example.com/cover.jpg",
    applyRemoteCover: "使用远程封面",
    checkingRemoteCover: "正在验证封面是否允许跨域导出…",
    remoteCoverReady: "远程封面已验证，可用于预览、取色和导出。",
    remoteCoverHttpsOnly: "远程封面必须使用 HTTPS 地址。",
    remoteCoverFailed: "此图片无法安全跨域导出，请改用本地上传或其他允许 CORS 的图片地址。",
    localCoverReady: "本地封面只在当前浏览器标签中使用，不会上传。",
    uploadCover: "上传本地封面",
    coverHint: "本地图片最可靠；远程图片必须允许匿名跨域读取。",
    noticeTitle: "Web Lite 的能力边界",
    noticeBody: "此静态版专注于手动编辑、实时预览与本地 PNG 导出。歌曲搜索、音乐链接解析、本地音频元数据、在线歌词和 AI 翻译仅在桌面版提供。",
    downloadDesktop: "下载完整桌面版",
    fontTitle: "字体方案",
    fontDescription: "内置字体可保持稳定输出；系统字体会随设备而变化。",
    sourceHanSans: "思源黑体",
    sourceHanSerif: "思源宋体",
    systemSans: "系统无衬线",
    systemSerif: "系统衬线",
    stableFont: "内置 · 稳定输出",
    deviceFont: "浏览器系统字体 · 因设备而异",
    selected: "已选择",
    exportStandard: "标准",
    exportHigh: "高清",
    exportReady: "PNG 已开始下载。",
    exportFailed: "PNG 导出失败，请检查封面后重试。",
    remoteCoverApplyFailed: "封面验证失败，请改用本地上传。"
  },
  en: {
    badge: "Web Lite",
    headerDesktop: "Desktop App",
    headerRepository: "GitHub Repository",
    clearAll: "Clear all",
    language: "Interface language",
    songStep: "Song Info",
    songStepDescription: "Enter song details manually and add an export-safe cover.",
    remoteCover: "Remote cover URL",
    remoteCoverPlaceholder: "https://example.com/cover.jpg",
    applyRemoteCover: "Use remote cover",
    checkingRemoteCover: "Checking whether this cover allows cross-origin export…",
    remoteCoverReady: "The remote cover is safe to preview, sample, and export.",
    remoteCoverHttpsOnly: "Remote covers must use an HTTPS URL.",
    remoteCoverFailed: "This image cannot be exported safely across origins. Upload it locally or use a CORS-enabled image URL.",
    localCoverReady: "The local cover stays in this browser tab and is never uploaded.",
    uploadCover: "Upload local cover",
    coverHint: "Local images are most reliable. Remote images must allow anonymous cross-origin reads.",
    noticeTitle: "What Web Lite includes",
    noticeBody: "This static edition focuses on manual editing, live preview, and local PNG export. Song search, music-link parsing, local-audio metadata, online lyrics, and AI translation are available in the desktop app.",
    downloadDesktop: "Download the full desktop app",
    fontTitle: "Font scheme",
    fontDescription: "Bundled fonts produce stable output; system fonts vary by device.",
    sourceHanSans: "Source Han Sans",
    sourceHanSerif: "Source Han Serif",
    systemSans: "System Sans",
    systemSerif: "System Serif",
    stableFont: "Bundled · stable output",
    deviceFont: "Browser system font · device dependent",
    selected: "Selected",
    exportStandard: "Standard",
    exportHigh: "High",
    exportReady: "Your PNG download has started.",
    exportFailed: "PNG export failed. Check the cover and try again.",
    remoteCoverApplyFailed: "Cover validation failed. Please upload the image locally."
  }
} as const;

export type WebLiteCopy = typeof webLiteCopy[WebLiteLocale];
