import type { Locale } from "@/lib/types";

export type LyricsWorkspaceCopy = {
  manuscript: string;
  original: string;
  translation: string;
  currentPosition: string;
  sharedScrollHint: string;
  resizeSidebar: string;
  commandBar: string;
  sidebar: string;
  collapseSidebar: string;
  expandSidebar: string;
  closeDrawer: string;
  cleanupTab: string;
  translationTab: string;
  reviewTab: string;
  sourceTab: string;
  activeColumnScope: string;
  selectedLinesScope: string;
  synchronizedScope: string;
  undo: string;
  redo: string;
  undoNow: string;
  blankShortcut: string;
  findShortcut: string;
  aiShortcut: string;
  cleanupHeading: string;
  scopeHeading: string;
  activeColumn: string;
  alignedColumns: string;
  alignedColumnsHint: string;
  blankLinesHeading: string;
  trimBlankLines: string;
  collapseBlankLines: string;
  removeBlankLines: string;
  removeBlankLinesPreview: string;
  confirmRemoveBlankLines: string;
  cleanPaste: string;
  cleanPasteHint: string;
  lrcHeading: string;
  previewLrc: string;
  applyLrc: string;
  lrcPreview: string;
  findReplaceHeading: string;
  findLabel: string;
  replaceLabel: string;
  matchCase: string;
  matchCount: string;
  replaceMatches: string;
  mergeHeading: string;
  mergeSelectedLines: string;
  mergeSelectionHint: string;
  tagsHeading: string;
  previewTags: string;
  removeTags: string;
  noTags: string;
  translationHeading: string;
  splitPreview: string;
  splitApply: string;
  splitSummary: string;
  formatTranslation: string;
  swapPreview: string;
  swapApply: string;
  swapSummary: string;
  alignmentHeading: string;
  alignmentOk: string;
  alignmentMismatch: string;
  locateLine: string;
  reviewHeading: string;
  lineBudgetLabel: string;
  budgetRemaining: string;
  budgetExceeded: string;
  issueHeading: string;
  noIssues: string;
  longLineIssue: string;
  duplicateLineIssue: string;
  invisibleIssue: string;
  sourceHeading: string;
  currentSong: string;
  sourceStatus: string;
  noSourceTools: string;
  noChanges: string;
  removedLinesResult: string;
  cleanedPasteResult: string;
  cleanedLrcResult: string;
  replacedResult: string;
  mergedResult: string;
  tagsRemovedResult: string;
  synchronizedResult: string;
  formattedResult: string;
  splitResult: string;
  swappedResult: string;
  undoneResult: string;
  redoneResult: string;
};

const COPY: Record<Locale, LyricsWorkspaceCopy> = {
  zh: {
    manuscript: "歌词文档",
    original: "原文",
    translation: "译文",
    currentPosition: "{label} · 第 {line} / {total} 行",
    sharedScrollHint: "原文与译文共享同一个滚动位置",
    resizeSidebar: "调整歌词编辑区和侧栏宽度",
    commandBar: "歌词命令栏",
    sidebar: "歌词工具侧栏",
    collapseSidebar: "折叠侧栏",
    expandSidebar: "展开侧栏",
    closeDrawer: "关闭工具抽屉",
    cleanupTab: "整理",
    translationTab: "翻译",
    reviewTab: "检查",
    sourceTab: "来源",
    activeColumnScope: "{label}全栏",
    selectedLinesScope: "{label}第 {start}–{end} 行",
    synchronizedScope: "原译同步第 {start}–{end} 行",
    undo: "撤销上次整理",
    redo: "重做上次整理",
    undoNow: "立即撤销",
    blankShortcut: "空行整理",
    findShortcut: "查找",
    aiShortcut: "AI 翻译",
    cleanupHeading: "确定性文本整理",
    scopeHeading: "作用范围",
    activeColumn: "当前栏",
    alignedColumns: "原译同步",
    alignedColumnsHint: "仅删除同一索引上原文与译文都为空的行。",
    blankLinesHeading: "空行",
    trimBlankLines: "删除首尾空行",
    collapseBlankLines: "连续空行留一个",
    removeBlankLines: "删除全部空行",
    removeBlankLinesPreview: "将从{scope}删除 {count} 个空行。",
    confirmRemoveBlankLines: "确认删除全部空行",
    cleanPaste: "清理粘贴内容",
    cleanPasteHint: "清理行尾空格、纯空白行、BOM、零宽字符和换行，不改正文标点。",
    lrcHeading: "LRC 时间轴与元数据",
    previewLrc: "预览 LRC 清理",
    applyLrc: "应用 LRC 清理",
    lrcPreview: "将清理 {timestamps} 个时间标记和 {metadata} 行元数据。",
    findReplaceHeading: "查找替换",
    findLabel: "查找",
    replaceLabel: "替换为",
    matchCase: "区分大小写",
    matchCount: "{count} 处匹配",
    replaceMatches: "替换 {count} 处",
    mergeHeading: "合并行",
    mergeSelectedLines: "合并 {count} 个选中行",
    mergeSelectionHint: "先在歌词编辑区选择至少两行。",
    tagsHeading: "段落标签",
    previewTags: "预览段落标签",
    removeTags: "移除 {count} 个标签",
    noTags: "当前范围没有可安全识别的段落标签。",
    translationHeading: "双栏翻译工作流",
    splitPreview: "预览交替歌词拆分",
    splitApply: "应用拆分",
    splitSummary: "将生成原文 {original} 行、译文 {translation} 行。",
    formatTranslation: "格式化中文译文",
    swapPreview: "预览交换原文/译文",
    swapApply: "确认交换",
    swapSummary: "原文与译文将完整交换；此操作不会逐行重排。",
    alignmentHeading: "双栏对齐",
    alignmentOk: "原文与译文行数一致。",
    alignmentMismatch: "原文与译文相差 {count} 行，首个未配对位置在第 {line} 行。",
    locateLine: "定位第 {line} 行",
    reviewHeading: "导出与文本检查",
    lineBudgetLabel: "导出行数预算",
    budgetRemaining: "还可使用 {count} 个非空行。",
    budgetExceeded: "已超出 {count} 个非空行。",
    issueHeading: "可定位的问题",
    noIssues: "未发现过长行、连续重复行或不可见字符。",
    longLineIssue: "{label}第 {line} 行较长（{count} 字符）",
    duplicateLineIssue: "{label}第 {line} 行与上一行连续重复",
    invisibleIssue: "{label}第 {line} 行含 {count} 个不可见字符",
    sourceHeading: "歌曲与歌词来源",
    currentSong: "当前歌曲",
    sourceStatus: "来源状态：{source}",
    noSourceTools: "当前歌曲没有可用的在线歌词获取入口。",
    noChanges: "当前范围无需更改。",
    removedLinesResult: "已从{scope}移除 {count} 行。",
    cleanedPasteResult: "已清理 {count} 项粘贴残留。",
    cleanedLrcResult: "已清理 {timestamps} 个时间标记和 {metadata} 行元数据。",
    replacedResult: "已在{scope}替换 {count} 处。",
    mergedResult: "已将 {count} 行合并为一行。",
    tagsRemovedResult: "已从{scope}移除 {count} 个段落标签。",
    synchronizedResult: "已同步移除原译两栏的 {count} 个空行。",
    formattedResult: "已格式化中文译文。",
    splitResult: "已拆分交替歌词并启用译文。",
    swappedResult: "已交换原文与译文。",
    undoneResult: "已撤销：{label}",
    redoneResult: "已重做：{label}"
  },
  "zh-TW": {
    manuscript: "歌詞文件",
    original: "原文",
    translation: "譯文",
    currentPosition: "{label} · 第 {line} / {total} 行",
    sharedScrollHint: "原文與譯文共用同一個捲動位置",
    resizeSidebar: "調整歌詞編輯區與側欄寬度",
    commandBar: "歌詞命令列",
    sidebar: "歌詞工具側欄",
    collapseSidebar: "收合側欄",
    expandSidebar: "展開側欄",
    closeDrawer: "關閉工具抽屜",
    cleanupTab: "整理",
    translationTab: "翻譯",
    reviewTab: "檢查",
    sourceTab: "來源",
    activeColumnScope: "{label}全欄",
    selectedLinesScope: "{label}第 {start}–{end} 行",
    synchronizedScope: "原譯同步第 {start}–{end} 行",
    undo: "復原上次整理",
    redo: "重做上次整理",
    undoNow: "立即復原",
    blankShortcut: "空行整理",
    findShortcut: "尋找",
    aiShortcut: "AI 翻譯",
    cleanupHeading: "確定性文字整理",
    scopeHeading: "作用範圍",
    activeColumn: "目前欄",
    alignedColumns: "原譯同步",
    alignedColumnsHint: "只刪除相同索引上原文與譯文都為空的行。",
    blankLinesHeading: "空行",
    trimBlankLines: "刪除開頭與結尾空行",
    collapseBlankLines: "連續空行保留一個",
    removeBlankLines: "刪除所有空行",
    removeBlankLinesPreview: "將從{scope}刪除 {count} 個空行。",
    confirmRemoveBlankLines: "確認刪除所有空行",
    cleanPaste: "清理貼上內容",
    cleanPasteHint: "清理行尾空格、純空白行、BOM、零寬字元與換行，不改正文標點。",
    lrcHeading: "LRC 時間軸與中繼資料",
    previewLrc: "預覽 LRC 清理",
    applyLrc: "套用 LRC 清理",
    lrcPreview: "將清理 {timestamps} 個時間標記與 {metadata} 行中繼資料。",
    findReplaceHeading: "尋找與取代",
    findLabel: "尋找",
    replaceLabel: "取代為",
    matchCase: "區分大小寫",
    matchCount: "{count} 處相符",
    replaceMatches: "取代 {count} 處",
    mergeHeading: "合併行",
    mergeSelectedLines: "合併 {count} 個選取行",
    mergeSelectionHint: "請先在歌詞編輯區選取至少兩行。",
    tagsHeading: "段落標籤",
    previewTags: "預覽段落標籤",
    removeTags: "移除 {count} 個標籤",
    noTags: "目前範圍沒有可安全辨識的段落標籤。",
    translationHeading: "雙欄翻譯流程",
    splitPreview: "預覽交替歌詞拆分",
    splitApply: "套用拆分",
    splitSummary: "將產生原文 {original} 行、譯文 {translation} 行。",
    formatTranslation: "格式化中文譯文",
    swapPreview: "預覽交換原文/譯文",
    swapApply: "確認交換",
    swapSummary: "原文與譯文將完整交換；此操作不會逐行重排。",
    alignmentHeading: "雙欄對齊",
    alignmentOk: "原文與譯文行數一致。",
    alignmentMismatch: "原文與譯文相差 {count} 行，第一個未配對位置在第 {line} 行。",
    locateLine: "定位第 {line} 行",
    reviewHeading: "匯出與文字檢查",
    lineBudgetLabel: "匯出行數額度",
    budgetRemaining: "還可使用 {count} 個非空行。",
    budgetExceeded: "已超出 {count} 個非空行。",
    issueHeading: "可定位的問題",
    noIssues: "未發現過長行、連續重複行或不可見字元。",
    longLineIssue: "{label}第 {line} 行較長（{count} 字元）",
    duplicateLineIssue: "{label}第 {line} 行與上一行連續重複",
    invisibleIssue: "{label}第 {line} 行含 {count} 個不可見字元",
    sourceHeading: "歌曲與歌詞來源",
    currentSong: "目前歌曲",
    sourceStatus: "來源狀態：{source}",
    noSourceTools: "目前歌曲沒有可用的線上歌詞取得入口。",
    noChanges: "目前範圍不需要更改。",
    removedLinesResult: "已從{scope}移除 {count} 行。",
    cleanedPasteResult: "已清理 {count} 項貼上殘留。",
    cleanedLrcResult: "已清理 {timestamps} 個時間標記與 {metadata} 行中繼資料。",
    replacedResult: "已在{scope}取代 {count} 處。",
    mergedResult: "已將 {count} 行合併為一行。",
    tagsRemovedResult: "已從{scope}移除 {count} 個段落標籤。",
    synchronizedResult: "已同步移除原譯兩欄的 {count} 個空行。",
    formattedResult: "已格式化中文譯文。",
    splitResult: "已拆分交替歌詞並啟用譯文。",
    swappedResult: "已交換原文與譯文。",
    undoneResult: "已復原：{label}",
    redoneResult: "已重做：{label}"
  },
  en: {
    manuscript: "Lyrics document",
    original: "Original",
    translation: "Translation",
    currentPosition: "{label} · line {line} / {total}",
    sharedScrollHint: "Original and translation share one scroll position",
    resizeSidebar: "Resize the lyrics editor and sidebar",
    commandBar: "Lyrics command bar",
    sidebar: "Lyrics tools sidebar",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    closeDrawer: "Close tools drawer",
    cleanupTab: "Cleanup",
    translationTab: "Translation",
    reviewTab: "Review",
    sourceTab: "Source",
    activeColumnScope: "All {label}",
    selectedLinesScope: "{label} lines {start}–{end}",
    synchronizedScope: "Aligned lines {start}–{end}",
    undo: "Undo last cleanup",
    redo: "Redo last cleanup",
    undoNow: "Undo now",
    blankShortcut: "Blank lines",
    findShortcut: "Find",
    aiShortcut: "AI translate",
    cleanupHeading: "Deterministic text cleanup",
    scopeHeading: "Apply to",
    activeColumn: "Active column",
    alignedColumns: "Both, aligned",
    alignedColumnsHint: "Only removes a row when both columns are blank at the same index.",
    blankLinesHeading: "Blank lines",
    trimBlankLines: "Trim leading/trailing",
    collapseBlankLines: "Collapse consecutive",
    removeBlankLines: "Remove all blanks",
    removeBlankLinesPreview: "Will remove {count} blank rows from {scope}.",
    confirmRemoveBlankLines: "Confirm removing all blanks",
    cleanPaste: "Clean pasted text",
    cleanPasteHint: "Removes trailing spaces, whitespace-only rows, BOM, zero-width characters, and mixed newlines without changing punctuation.",
    lrcHeading: "LRC timeline and metadata",
    previewLrc: "Preview LRC cleanup",
    applyLrc: "Apply LRC cleanup",
    lrcPreview: "Will clear {timestamps} timestamps and {metadata} metadata rows.",
    findReplaceHeading: "Find and replace",
    findLabel: "Find",
    replaceLabel: "Replace with",
    matchCase: "Match case",
    matchCount: "{count} matches",
    replaceMatches: "Replace {count}",
    mergeHeading: "Merge lines",
    mergeSelectedLines: "Merge {count} selected lines",
    mergeSelectionHint: "Select at least two lines in the lyrics editor first.",
    tagsHeading: "Section labels",
    previewTags: "Preview section labels",
    removeTags: "Remove {count} labels",
    noTags: "No safely recognized section labels in this scope.",
    translationHeading: "Two-column translation workflow",
    splitPreview: "Preview alternating split",
    splitApply: "Apply split",
    splitSummary: "Creates {original} original and {translation} translated lines.",
    formatTranslation: "Format Chinese translation",
    swapPreview: "Preview column swap",
    swapApply: "Confirm swap",
    swapSummary: "The full original and translation columns will swap; rows are not reordered.",
    alignmentHeading: "Column alignment",
    alignmentOk: "Original and translation have the same number of lines.",
    alignmentMismatch: "Columns differ by {count} lines; the first unpaired position is line {line}.",
    locateLine: "Go to line {line}",
    reviewHeading: "Export and text review",
    lineBudgetLabel: "Export line budget",
    budgetRemaining: "{count} non-empty lines remain.",
    budgetExceeded: "{count} non-empty lines over budget.",
    issueHeading: "Locatable issues",
    noIssues: "No long lines, consecutive duplicates, or invisible characters found.",
    longLineIssue: "{label} line {line} is long ({count} characters)",
    duplicateLineIssue: "{label} line {line} repeats the previous line",
    invisibleIssue: "{label} line {line} has {count} invisible characters",
    sourceHeading: "Song and lyrics source",
    currentSong: "Current song",
    sourceStatus: "Source status: {source}",
    noSourceTools: "No online lyrics source is available for this song.",
    noChanges: "Nothing in this scope needs changing.",
    removedLinesResult: "Removed {count} lines from {scope}.",
    cleanedPasteResult: "Cleaned {count} pasted-text artifacts.",
    cleanedLrcResult: "Cleared {timestamps} timestamps and {metadata} metadata rows.",
    replacedResult: "Replaced {count} matches in {scope}.",
    mergedResult: "Merged {count} lines into one.",
    tagsRemovedResult: "Removed {count} section labels from {scope}.",
    synchronizedResult: "Removed {count} aligned blank rows from both columns.",
    formattedResult: "Formatted the Chinese translation.",
    splitResult: "Split alternating lyrics and enabled translation.",
    swappedResult: "Swapped original and translation.",
    undoneResult: "Undid: {label}",
    redoneResult: "Redid: {label}"
  },
  fr: {
    manuscript: "Document de paroles",
    original: "Original",
    translation: "Traduction",
    currentPosition: "{label} · ligne {line} / {total}",
    sharedScrollHint: "L’original et la traduction partagent le même défilement",
    resizeSidebar: "Redimensionner l’éditeur et la barre latérale",
    commandBar: "Barre de commandes des paroles",
    sidebar: "Outils de paroles",
    collapseSidebar: "Réduire la barre latérale",
    expandSidebar: "Développer la barre latérale",
    closeDrawer: "Fermer le tiroir d’outils",
    cleanupTab: "Nettoyer",
    translationTab: "Traduction",
    reviewTab: "Vérifier",
    sourceTab: "Source",
    activeColumnScope: "Toute la colonne {label}",
    selectedLinesScope: "{label}, lignes {start}–{end}",
    synchronizedScope: "Lignes alignées {start}–{end}",
    undo: "Annuler le dernier nettoyage",
    redo: "Rétablir le dernier nettoyage",
    undoNow: "Annuler",
    blankShortcut: "Lignes vides",
    findShortcut: "Rechercher",
    aiShortcut: "Traduction IA",
    cleanupHeading: "Nettoyage déterministe du texte",
    scopeHeading: "Appliquer à",
    activeColumn: "Colonne active",
    alignedColumns: "Deux colonnes alignées",
    alignedColumnsHint: "Supprime une ligne seulement si les deux colonnes sont vides au même index.",
    blankLinesHeading: "Lignes vides",
    trimBlankLines: "Retirer au début/à la fin",
    collapseBlankLines: "Réduire les suites",
    removeBlankLines: "Tout supprimer",
    removeBlankLinesPreview: "{count} lignes vides seront supprimées de {scope}.",
    confirmRemoveBlankLines: "Confirmer la suppression",
    cleanPaste: "Nettoyer le texte collé",
    cleanPasteHint: "Retire espaces finaux, lignes blanches, BOM, caractères invisibles et retours mixtes sans modifier la ponctuation.",
    lrcHeading: "Chronologie et métadonnées LRC",
    previewLrc: "Prévisualiser le nettoyage LRC",
    applyLrc: "Appliquer le nettoyage LRC",
    lrcPreview: "{timestamps} horodatages et {metadata} lignes de métadonnées seront effacés.",
    findReplaceHeading: "Rechercher et remplacer",
    findLabel: "Rechercher",
    replaceLabel: "Remplacer par",
    matchCase: "Respecter la casse",
    matchCount: "{count} occurrences",
    replaceMatches: "Remplacer {count}",
    mergeHeading: "Fusionner les lignes",
    mergeSelectedLines: "Fusionner {count} lignes sélectionnées",
    mergeSelectionHint: "Sélectionnez d’abord au moins deux lignes dans l’éditeur.",
    tagsHeading: "Libellés de section",
    previewTags: "Prévisualiser les libellés",
    removeTags: "Retirer {count} libellés",
    noTags: "Aucun libellé de section reconnu de façon sûre dans cette zone.",
    translationHeading: "Flux de traduction en deux colonnes",
    splitPreview: "Prévisualiser la séparation alternée",
    splitApply: "Appliquer la séparation",
    splitSummary: "Créera {original} lignes originales et {translation} lignes traduites.",
    formatTranslation: "Formater la traduction chinoise",
    swapPreview: "Prévisualiser l’échange",
    swapApply: "Confirmer l’échange",
    swapSummary: "Les colonnes complètes seront échangées sans réordonner les lignes.",
    alignmentHeading: "Alignement des colonnes",
    alignmentOk: "L’original et la traduction ont le même nombre de lignes.",
    alignmentMismatch: "Écart de {count} lignes ; la première position non appariée est la ligne {line}.",
    locateLine: "Aller à la ligne {line}",
    reviewHeading: "Vérification du texte et de l’export",
    lineBudgetLabel: "Budget de lignes d’export",
    budgetRemaining: "Il reste {count} lignes non vides.",
    budgetExceeded: "Dépassement de {count} lignes non vides.",
    issueHeading: "Problèmes localisables",
    noIssues: "Aucune ligne longue, répétition consécutive ou caractère invisible.",
    longLineIssue: "{label}, ligne {line} longue ({count} caractères)",
    duplicateLineIssue: "{label}, ligne {line} identique à la précédente",
    invisibleIssue: "{label}, ligne {line} contient {count} caractères invisibles",
    sourceHeading: "Source du morceau et des paroles",
    currentSong: "Morceau actuel",
    sourceStatus: "État de la source : {source}",
    noSourceTools: "Aucune source de paroles en ligne n’est disponible pour ce morceau.",
    noChanges: "Aucune modification nécessaire dans cette zone.",
    removedLinesResult: "{count} lignes retirées de {scope}.",
    cleanedPasteResult: "{count} résidus de collage nettoyés.",
    cleanedLrcResult: "{timestamps} horodatages et {metadata} lignes de métadonnées effacés.",
    replacedResult: "{count} occurrences remplacées dans {scope}.",
    mergedResult: "{count} lignes fusionnées en une.",
    tagsRemovedResult: "{count} libellés retirés de {scope}.",
    synchronizedResult: "{count} lignes vides alignées retirées des deux colonnes.",
    formattedResult: "Traduction chinoise formatée.",
    splitResult: "Paroles alternées séparées et traduction activée.",
    swappedResult: "Original et traduction échangés.",
    undoneResult: "Annulé : {label}",
    redoneResult: "Rétabli : {label}"
  },
  ja: {
    manuscript: "歌詞ドキュメント",
    original: "原文",
    translation: "翻訳",
    currentPosition: "{label} · {line} / {total} 行",
    sharedScrollHint: "原文と翻訳は同じスクロール位置を共有します",
    resizeSidebar: "歌詞エディターとサイドバーの幅を調整",
    commandBar: "歌詞コマンドバー",
    sidebar: "歌詞ツールサイドバー",
    collapseSidebar: "サイドバーを折りたたむ",
    expandSidebar: "サイドバーを展開",
    closeDrawer: "ツールドロワーを閉じる",
    cleanupTab: "整理",
    translationTab: "翻訳",
    reviewTab: "確認",
    sourceTab: "ソース",
    activeColumnScope: "{label}全体",
    selectedLinesScope: "{label} {start}〜{end} 行",
    synchronizedScope: "原文・翻訳の同期 {start}〜{end} 行",
    undo: "直前の整理を元に戻す",
    redo: "直前の整理をやり直す",
    undoNow: "今すぐ元に戻す",
    blankShortcut: "空行整理",
    findShortcut: "検索",
    aiShortcut: "AI 翻訳",
    cleanupHeading: "確定的なテキスト整理",
    scopeHeading: "対象範囲",
    activeColumn: "現在の列",
    alignedColumns: "原文・翻訳を同期",
    alignedColumnsHint: "同じ位置で両方の列が空の場合にだけ行を削除します。",
    blankLinesHeading: "空行",
    trimBlankLines: "先頭・末尾を削除",
    collapseBlankLines: "連続空行を1つに",
    removeBlankLines: "空行をすべて削除",
    removeBlankLinesPreview: "{scope}から空行を {count} 行削除します。",
    confirmRemoveBlankLines: "すべての空行削除を確認",
    cleanPaste: "貼り付け内容を整理",
    cleanPasteHint: "行末空白、空白だけの行、BOM、ゼロ幅文字、改行を整理し、本文の句読点は変更しません。",
    lrcHeading: "LRC タイムラインとメタデータ",
    previewLrc: "LRC 整理をプレビュー",
    applyLrc: "LRC 整理を適用",
    lrcPreview: "{timestamps} 個の時刻タグと {metadata} 行のメタデータを消去します。",
    findReplaceHeading: "検索と置換",
    findLabel: "検索",
    replaceLabel: "置換後",
    matchCase: "大文字小文字を区別",
    matchCount: "{count} 件一致",
    replaceMatches: "{count} 件を置換",
    mergeHeading: "行を結合",
    mergeSelectedLines: "選択した {count} 行を結合",
    mergeSelectionHint: "歌詞エディターで2行以上を選択してください。",
    tagsHeading: "セクションラベル",
    previewTags: "ラベルをプレビュー",
    removeTags: "{count} 個のラベルを削除",
    noTags: "この範囲に安全に認識できるセクションラベルはありません。",
    translationHeading: "2列翻訳ワークフロー",
    splitPreview: "交互歌詞の分割をプレビュー",
    splitApply: "分割を適用",
    splitSummary: "原文 {original} 行、翻訳 {translation} 行を作成します。",
    formatTranslation: "中国語訳を整形",
    swapPreview: "原文・翻訳の交換をプレビュー",
    swapApply: "交換を確定",
    swapSummary: "原文列と翻訳列をそのまま交換し、行の並べ替えは行いません。",
    alignmentHeading: "2列の整合性",
    alignmentOk: "原文と翻訳の行数は一致しています。",
    alignmentMismatch: "{count} 行の差があります。最初の未対応位置は {line} 行目です。",
    locateLine: "{line} 行目へ移動",
    reviewHeading: "書き出しとテキストの確認",
    lineBudgetLabel: "書き出し行数予算",
    budgetRemaining: "空でない行をあと {count} 行使用できます。",
    budgetExceeded: "空でない行が {count} 行超過しています。",
    issueHeading: "移動できる問題",
    noIssues: "長すぎる行、連続重複行、不可視文字は見つかりませんでした。",
    longLineIssue: "{label} {line} 行目が長いです（{count} 文字）",
    duplicateLineIssue: "{label} {line} 行目が直前の行と連続重複",
    invisibleIssue: "{label} {line} 行目に不可視文字が {count} 個",
    sourceHeading: "曲と歌詞のソース",
    currentSong: "現在の曲",
    sourceStatus: "ソース状態：{source}",
    noSourceTools: "この曲ではオンライン歌詞取得を利用できません。",
    noChanges: "この範囲に変更は必要ありません。",
    removedLinesResult: "{scope}から {count} 行を削除しました。",
    cleanedPasteResult: "貼り付け時の残留要素を {count} 件整理しました。",
    cleanedLrcResult: "{timestamps} 個の時刻タグと {metadata} 行のメタデータを消去しました。",
    replacedResult: "{scope}で {count} 件を置換しました。",
    mergedResult: "{count} 行を1行に結合しました。",
    tagsRemovedResult: "{scope}から {count} 個のラベルを削除しました。",
    synchronizedResult: "両方の列から同期した空行を {count} 行削除しました。",
    formattedResult: "中国語訳を整形しました。",
    splitResult: "交互歌詞を分割して翻訳を有効にしました。",
    swappedResult: "原文と翻訳を交換しました。",
    undoneResult: "元に戻しました：{label}",
    redoneResult: "やり直しました：{label}"
  },
  es: {
    manuscript: "Documento de letras",
    original: "Original",
    translation: "Traducción",
    currentPosition: "{label} · línea {line} / {total}",
    sharedScrollHint: "El original y la traducción comparten una sola posición de desplazamiento",
    resizeSidebar: "Cambiar el ancho del editor y la barra lateral",
    commandBar: "Barra de comandos de letras",
    sidebar: "Herramientas de letras",
    collapseSidebar: "Contraer la barra lateral",
    expandSidebar: "Expandir la barra lateral",
    closeDrawer: "Cerrar el panel de herramientas",
    cleanupTab: "Limpiar",
    translationTab: "Traducción",
    reviewTab: "Revisar",
    sourceTab: "Fuente",
    activeColumnScope: "Toda la columna {label}",
    selectedLinesScope: "{label}, líneas {start}–{end}",
    synchronizedScope: "Líneas alineadas {start}–{end}",
    undo: "Deshacer la última limpieza",
    redo: "Rehacer la última limpieza",
    undoNow: "Deshacer ahora",
    blankShortcut: "Líneas vacías",
    findShortcut: "Buscar",
    aiShortcut: "Traducción IA",
    cleanupHeading: "Limpieza determinista de texto",
    scopeHeading: "Aplicar a",
    activeColumn: "Columna activa",
    alignedColumns: "Ambas, alineadas",
    alignedColumnsHint: "Solo elimina una fila si ambas columnas están vacías en el mismo índice.",
    blankLinesHeading: "Líneas vacías",
    trimBlankLines: "Quitar al inicio/final",
    collapseBlankLines: "Reducir consecutivas",
    removeBlankLines: "Eliminar todas",
    removeBlankLinesPreview: "Se eliminarán {count} filas vacías de {scope}.",
    confirmRemoveBlankLines: "Confirmar eliminación",
    cleanPaste: "Limpiar texto pegado",
    cleanPasteHint: "Quita espacios finales, filas solo con espacios, BOM, caracteres invisibles y saltos mixtos sin cambiar la puntuación.",
    lrcHeading: "Cronología y metadatos LRC",
    previewLrc: "Previsualizar limpieza LRC",
    applyLrc: "Aplicar limpieza LRC",
    lrcPreview: "Se limpiarán {timestamps} marcas de tiempo y {metadata} filas de metadatos.",
    findReplaceHeading: "Buscar y reemplazar",
    findLabel: "Buscar",
    replaceLabel: "Reemplazar por",
    matchCase: "Distinguir mayúsculas",
    matchCount: "{count} coincidencias",
    replaceMatches: "Reemplazar {count}",
    mergeHeading: "Unir líneas",
    mergeSelectedLines: "Unir {count} líneas seleccionadas",
    mergeSelectionHint: "Selecciona primero al menos dos líneas en el editor.",
    tagsHeading: "Etiquetas de sección",
    previewTags: "Previsualizar etiquetas",
    removeTags: "Quitar {count} etiquetas",
    noTags: "No hay etiquetas de sección reconocidas con seguridad en este ámbito.",
    translationHeading: "Flujo de traducción en dos columnas",
    splitPreview: "Previsualizar separación alternada",
    splitApply: "Aplicar separación",
    splitSummary: "Creará {original} líneas originales y {translation} traducidas.",
    formatTranslation: "Formatear traducción china",
    swapPreview: "Previsualizar intercambio",
    swapApply: "Confirmar intercambio",
    swapSummary: "Las columnas completas se intercambiarán sin reordenar sus filas.",
    alignmentHeading: "Alineación de columnas",
    alignmentOk: "El original y la traducción tienen el mismo número de líneas.",
    alignmentMismatch: "Hay {count} líneas de diferencia; la primera posición sin pareja es la línea {line}.",
    locateLine: "Ir a la línea {line}",
    reviewHeading: "Revisión de exportación y texto",
    lineBudgetLabel: "Presupuesto de líneas de exportación",
    budgetRemaining: "Quedan {count} líneas no vacías.",
    budgetExceeded: "Se excede el límite por {count} líneas no vacías.",
    issueHeading: "Problemas localizables",
    noIssues: "No se encontraron líneas largas, duplicados consecutivos ni caracteres invisibles.",
    longLineIssue: "{label}, línea {line} larga ({count} caracteres)",
    duplicateLineIssue: "{label}, línea {line} repite la anterior",
    invisibleIssue: "{label}, línea {line} contiene {count} caracteres invisibles",
    sourceHeading: "Fuente de la canción y la letra",
    currentSong: "Canción actual",
    sourceStatus: "Estado de la fuente: {source}",
    noSourceTools: "No hay una fuente de letras en línea disponible para esta canción.",
    noChanges: "No hace falta cambiar nada en este ámbito.",
    removedLinesResult: "Se eliminaron {count} líneas de {scope}.",
    cleanedPasteResult: "Se limpiaron {count} residuos del texto pegado.",
    cleanedLrcResult: "Se limpiaron {timestamps} marcas de tiempo y {metadata} filas de metadatos.",
    replacedResult: "Se reemplazaron {count} coincidencias en {scope}.",
    mergedResult: "Se unieron {count} líneas en una.",
    tagsRemovedResult: "Se quitaron {count} etiquetas de {scope}.",
    synchronizedResult: "Se eliminaron {count} filas vacías alineadas de ambas columnas.",
    formattedResult: "Se formateó la traducción china.",
    splitResult: "Se separó la letra alternada y se activó la traducción.",
    swappedResult: "Se intercambiaron original y traducción.",
    undoneResult: "Deshecho: {label}",
    redoneResult: "Rehecho: {label}"
  }
};

export function getLyricsWorkspaceCopy(locale: Locale) {
  return COPY[locale];
}

export function formatLyricsWorkspaceCopy(
  template: string,
  values: Record<string, string | number>
) {
  return template.replace(/\{(\w+)\}/gu, (match, key: string) => (
    values[key] === undefined ? match : String(values[key])
  ));
}
