import type { Locale } from "@/lib/types";
import type { AutosaveStatus } from "@/lib/editor-draft";

type Copy = Record<AutosaveStatus, string> & { draft: string; resume: string; untitled: string; closeFailed: string };
export const editorAutosaveCopy: Record<Locale, Copy> = {
  zh: { loading: "正在恢复草稿…", idle: "修改后 5 秒自动保存", pending: "有未保存的修改 · 停止修改 5 秒后自动保存", saving: "正在保存…", saved: "已自动保存", error: "自动保存失败 · 点击重试", disabled: "自动保存已停用", draft: "自动草稿", resume: "继续编辑", untitled: "未命名草稿", closeFailed: "草稿或设置未能保存，应用尚未关闭。请检查磁盘后重试。" },
  "zh-TW": { loading: "正在恢復草稿…", idle: "修改後 5 秒自動儲存", pending: "有未儲存的修改 · 停止修改 5 秒後自動儲存", saving: "正在儲存…", saved: "已自動儲存", error: "自動儲存失敗 · 點擊重試", disabled: "自動儲存已停用", draft: "自動草稿", resume: "繼續編輯", untitled: "未命名草稿", closeFailed: "草稿或設定未能儲存，應用程式尚未關閉。請檢查磁碟後重試。" },
  en: { loading: "Restoring draft…", idle: "Auto-saves after 5 seconds of inactivity", pending: "Unsaved changes · Auto-saves after 5 seconds of inactivity", saving: "Saving…", saved: "Automatically saved", error: "Auto-save failed · Click to retry", disabled: "Auto-save is off", draft: "Auto-saved draft", resume: "Continue editing", untitled: "Untitled draft", closeFailed: "The draft or settings could not be saved. The app remains open. Check the disk and try again." },
  fr: { loading: "Restauration du brouillon…", idle: "Enregistrement après 5 secondes sans modification", pending: "Modifications en attente · Enregistrement après 5 secondes", saving: "Enregistrement…", saved: "Enregistré automatiquement", error: "Échec de l’enregistrement · Cliquez pour réessayer", disabled: "Enregistrement automatique désactivé", draft: "Brouillon automatique", resume: "Continuer l’édition", untitled: "Brouillon sans titre", closeFailed: "Le brouillon ou les paramètres n’ont pas été enregistrés. L’application reste ouverte. Vérifiez le disque et réessayez." },
  ja: { loading: "下書きを復元中…", idle: "変更が止まってから 5 秒後に自動保存", pending: "未保存の変更 · 操作を止めて 5 秒後に自動保存", saving: "保存中…", saved: "自動保存済み", error: "自動保存に失敗 · クリックして再試行", disabled: "自動保存はオフです", draft: "自動保存した下書き", resume: "編集を続ける", untitled: "無題の下書き", closeFailed: "下書きまたは設定を保存できませんでした。アプリは開いたままです。ディスクを確認して再試行してください。" },
  es: { loading: "Restaurando borrador…", idle: "Guardado automático tras 5 segundos sin cambios", pending: "Cambios pendientes · Se guardan tras 5 segundos sin cambios", saving: "Guardando…", saved: "Guardado automáticamente", error: "Error al guardar · Haz clic para reintentar", disabled: "Guardado automático desactivado", draft: "Borrador automático", resume: "Continuar editando", untitled: "Borrador sin título", closeFailed: "No se pudo guardar el borrador o la configuración. La aplicación sigue abierta. Comprueba el disco e inténtalo de nuevo." }
};
