import type { Locale } from "@/lib/types";
import type { AutosaveStatus } from "@/lib/editor-draft";

type Copy = Record<AutosaveStatus, string> & { draft: string; resume: string; untitled: string; storageLimit: string; closeFailed: string };
export const editorAutosaveCopy: Record<Locale, Copy> = {
  zh: { storageLimit: "草稿与历史文件超过 64 MiB 保存上限。已有文件与备份已保留。若仍可打开历史，请删除不需要的草稿后重试；否则先备份用户数据目录中的 app-data/import-history.json 和 .bak 副本，再联系维护者协助恢复。", loading: "正在恢复草稿…", idle: "修改后 5 秒自动保存", pending: "有未保存的修改 · 停止修改 5 秒后自动保存", saving: "正在保存…", saved: "已自动保存", error: "自动保存失败 · 点击重试", disabled: "自动保存已停用", draft: "自动草稿", resume: "继续编辑", untitled: "未命名草稿", closeFailed: "草稿或设置未能保存，应用尚未关闭。请检查磁盘后重试。" },
  "zh-TW": { storageLimit: "草稿與歷史檔案超過 64 MiB 儲存上限。現有檔案與備份已保留。若仍可開啟歷史，請刪除不需要的草稿後重試；否則先備份使用者資料目錄中的 app-data/import-history.json 與 .bak 副本，再聯絡維護者協助復原。", loading: "正在恢復草稿…", idle: "修改後 5 秒自動儲存", pending: "有未儲存的修改 · 停止修改 5 秒後自動儲存", saving: "正在儲存…", saved: "已自動儲存", error: "自動儲存失敗 · 點擊重試", disabled: "自動儲存已停用", draft: "自動草稿", resume: "繼續編輯", untitled: "未命名草稿", closeFailed: "草稿或設定未能儲存，應用程式尚未關閉。請檢查磁碟後重試。" },
  en: { storageLimit: "Drafts and history exceed the 64 MiB storage limit. Existing files and backups are preserved. If History still opens, delete unneeded drafts and retry; otherwise back up app-data/import-history.json and its .bak copy in the user data directory and contact the maintainer for recovery.", loading: "Restoring draft…", idle: "Auto-saves after 5 seconds of inactivity", pending: "Unsaved changes · Auto-saves after 5 seconds of inactivity", saving: "Saving…", saved: "Automatically saved", error: "Auto-save failed · Click to retry", disabled: "Auto-save is off", draft: "Auto-saved draft", resume: "Continue editing", untitled: "Untitled draft", closeFailed: "The draft or settings could not be saved. The app remains open. Check the disk and try again." },
  fr: { storageLimit: "Les brouillons et l’historique dépassent la limite de 64 MiB. Les fichiers et sauvegardes sont conservés. Si l’historique s’ouvre encore, supprimez les brouillons inutiles et réessayez ; sinon sauvegardez app-data/import-history.json et sa copie .bak dans le dossier de données utilisateur et contactez le responsable pour la récupération.", loading: "Restauration du brouillon…", idle: "Enregistrement après 5 secondes sans modification", pending: "Modifications en attente · Enregistrement après 5 secondes", saving: "Enregistrement…", saved: "Enregistré automatiquement", error: "Échec de l’enregistrement · Cliquez pour réessayer", disabled: "Enregistrement automatique désactivé", draft: "Brouillon automatique", resume: "Continuer l’édition", untitled: "Brouillon sans titre", closeFailed: "Le brouillon ou les paramètres n’ont pas été enregistrés. L’application reste ouverte. Vérifiez le disque et réessayez." },
  ja: { storageLimit: "下書きと履歴が 64 MiB の保存上限を超えています。既存ファイルとバックアップは保持されています。履歴を開ける場合は不要な下書きを削除して再試行してください。開けない場合はユーザーデータ内の app-data/import-history.json と .bak のコピーをバックアップし、開発者に復元をご相談ください。", loading: "下書きを復元中…", idle: "変更が止まってから 5 秒後に自動保存", pending: "未保存の変更 · 操作を止めて 5 秒後に自動保存", saving: "保存中…", saved: "自動保存済み", error: "自動保存に失敗 · クリックして再試行", disabled: "自動保存はオフです", draft: "自動保存した下書き", resume: "編集を続ける", untitled: "無題の下書き", closeFailed: "下書きまたは設定を保存できませんでした。アプリは開いたままです。ディスクを確認して再試行してください。" },
  es: { storageLimit: "Los borradores y el historial superan el límite de 64 MiB. Los archivos y sus copias se conservan. Si el historial aún se abre, elimina borradores innecesarios y vuelve a intentarlo; de lo contrario, guarda una copia de app-data/import-history.json y de su archivo .bak del directorio de datos de usuario y contacta al mantenedor para recuperarlos.", loading: "Restaurando borrador…", idle: "Guardado automático tras 5 segundos sin cambios", pending: "Cambios pendientes · Se guardan tras 5 segundos sin cambios", saving: "Guardando…", saved: "Guardado automáticamente", error: "Error al guardar · Haz clic para reintentar", disabled: "Guardado automático desactivado", draft: "Borrador automático", resume: "Continuar editando", untitled: "Borrador sin título", closeFailed: "No se pudo guardar el borrador o la configuración. La aplicación sigue abierta. Comprueba el disco e inténtalo de nuevo." }
};
