import type { Locale } from "@/lib/types";

const en = {
  entry: "History",
  title: "Import history",
  intro: "Reimport songs and covers that were successfully parsed or saved on this desktop.",
  searchPlaceholder: "Search title, artist, album, file, or site",
  filterLabel: "Source",
  allSources: "All sources",
  sourceLink: "Link",
  sourceSearch: "Song search",
  sourceLocalAudio: "Local audio",
  sourceManualCover: "Manual cover",
  loading: "Loading import history…",
  loadFailed: "Import history could not be loaded.",
  retry: "Try again",
  empty: "No successful imports have been recorded yet.",
  emptyFiltered: "No history items match this search or filter.",
  resultCount: "{count} items",
  importedAt: "Imported {time}",
  reimport: "Reimport",
  reimporting: "Reimporting…",
  relocate: "Relocate",
  remove: "Delete",
  loadMore: "Load more",
  clearAll: "Clear all history",
  clearConfirm: "Delete every import history item? This cannot be undone.",
  removed: "History item deleted.",
  cleared: "Import history cleared.",
  historySaveFailed: "Imported successfully, but the history could not be saved.",
  replayFailed: "This history item could not be reimported. The current document was not changed.",
  replaySucceeded: "Reimported from history.",
  fileMissing: "The original file is missing. Relocate it to reimport without changing the current document.",
  fileChanged: "The file has changed since it was recorded. The current file was imported.",
  relocateFailed: "The replacement file could not be used.",
  corruptRecovered: "A damaged history file was preserved as {file}. A new history was started.",
  limitLabel: "Maximum import history",
  limitDescription: "Keep the most recently used successful imports on this desktop.",
  limitFive: "5 items",
  limitTen: "10 items",
  limitUnlimited: "Unlimited",
  limitTrimConfirm: "Changing the limit to {limit} will delete {count} older history items. Continue?",
  limitStatsFailed: "The history size could not be checked. The limit was not changed."
};

type HistoryCopy = typeof en;

const zh: HistoryCopy = {
  entry: "历史记录",
  title: "导入/解析历史",
  intro: "重新导入在此桌面端成功解析或保存过的歌曲与封面。",
  searchPlaceholder: "搜索歌名、歌手、专辑、文件或网站",
  filterLabel: "来源",
  allSources: "全部来源",
  sourceLink: "链接解析",
  sourceSearch: "歌曲搜索",
  sourceLocalAudio: "本地音频",
  sourceManualCover: "手动封面",
  loading: "正在载入导入历史…",
  loadFailed: "无法载入导入历史。",
  retry: "重试",
  empty: "还没有成功导入的历史记录。",
  emptyFiltered: "没有符合当前搜索或筛选条件的记录。",
  resultCount: "共 {count} 条",
  importedAt: "导入于 {time}",
  reimport: "重新导入",
  reimporting: "正在重新导入…",
  relocate: "重新定位",
  remove: "删除",
  loadMore: "加载更多",
  clearAll: "清空全部历史",
  clearConfirm: "确定删除全部导入历史吗？此操作无法撤销。",
  removed: "已删除历史记录。",
  cleared: "已清空导入历史。",
  historySaveFailed: "已成功导入，但历史记录保存失败。",
  replayFailed: "无法重新导入这条记录，当前文档未发生变化。",
  replaySucceeded: "已从历史记录重新导入。",
  fileMissing: "找不到原文件。重新定位后可再次导入，当前文档不会改变。",
  fileChanged: "文件自记录后已有变化，已按当前文件重新导入。",
  relocateFailed: "无法使用重新选择的文件。",
  corruptRecovered: "损坏的历史文件已保留为 {file}，并已新建历史记录。",
  limitLabel: "最多保留历史",
  limitDescription: "在此桌面端保留最近使用的成功导入记录。",
  limitFive: "5 条",
  limitTen: "10 条",
  limitUnlimited: "无限",
  limitTrimConfirm: "改为最多 {limit} 条将删除较早的 {count} 条记录，是否继续？",
  limitStatsFailed: "无法核对历史记录数量，本次未更改上限。"
};

const zhTW: HistoryCopy = {
  entry: "歷史記錄",
  title: "匯入／解析歷史",
  intro: "重新匯入曾在此桌面版成功解析或儲存的歌曲與封面。",
  searchPlaceholder: "搜尋歌名、演出者、專輯、檔案或網站",
  filterLabel: "來源",
  allSources: "全部來源",
  sourceLink: "連結解析",
  sourceSearch: "歌曲搜尋",
  sourceLocalAudio: "本機音訊",
  sourceManualCover: "手動封面",
  loading: "正在載入匯入歷史…",
  loadFailed: "無法載入匯入歷史。",
  retry: "重試",
  empty: "目前還沒有成功匯入的歷史記錄。",
  emptyFiltered: "沒有符合目前搜尋或篩選條件的記錄。",
  resultCount: "共 {count} 筆",
  importedAt: "匯入於 {time}",
  reimport: "重新匯入",
  reimporting: "正在重新匯入…",
  relocate: "重新定位",
  remove: "刪除",
  loadMore: "載入更多",
  clearAll: "清除全部歷史",
  clearConfirm: "確定要刪除全部匯入歷史嗎？此操作無法復原。",
  removed: "已刪除歷史記錄。",
  cleared: "已清除匯入歷史。",
  historySaveFailed: "已成功匯入，但無法儲存歷史記錄。",
  replayFailed: "無法重新匯入這筆記錄，目前文件未受影響。",
  replaySucceeded: "已從歷史記錄重新匯入。",
  fileMissing: "找不到原始檔案。重新定位後即可再次匯入，目前文件不會改變。",
  fileChanged: "檔案自記錄後已有變更，已依目前檔案重新匯入。",
  relocateFailed: "無法使用重新選取的檔案。",
  corruptRecovered: "損壞的歷史檔案已保留為 {file}，並已建立新的歷史記錄。",
  limitLabel: "最多保留歷史",
  limitDescription: "在此桌面版保留最近使用的成功匯入記錄。",
  limitFive: "5 筆",
  limitTen: "10 筆",
  limitUnlimited: "無限",
  limitTrimConfirm: "改為最多 {limit} 筆將刪除較早的 {count} 筆記錄，是否繼續？",
  limitStatsFailed: "無法確認歷史記錄數量，本次未變更上限。"
};

const fr: HistoryCopy = {
  entry: "Historique",
  title: "Historique des imports",
  intro: "Réimportez les morceaux et pochettes analysés ou enregistrés avec succès sur cet ordinateur.",
  searchPlaceholder: "Rechercher un titre, artiste, album, fichier ou site",
  filterLabel: "Source",
  allSources: "Toutes les sources",
  sourceLink: "Lien",
  sourceSearch: "Recherche de morceau",
  sourceLocalAudio: "Audio local",
  sourceManualCover: "Pochette manuelle",
  loading: "Chargement de l’historique…",
  loadFailed: "Impossible de charger l’historique des imports.",
  retry: "Réessayer",
  empty: "Aucun import réussi n’a encore été enregistré.",
  emptyFiltered: "Aucun élément ne correspond à cette recherche ou à ce filtre.",
  resultCount: "{count} éléments",
  importedAt: "Importé le {time}",
  reimport: "Réimporter",
  reimporting: "Réimportation…",
  relocate: "Relocaliser",
  remove: "Supprimer",
  loadMore: "Afficher plus",
  clearAll: "Effacer tout l’historique",
  clearConfirm: "Supprimer tout l’historique des imports ? Cette action est irréversible.",
  removed: "Élément supprimé de l’historique.",
  cleared: "Historique des imports effacé.",
  historySaveFailed: "Import réussi, mais impossible d’enregistrer l’historique.",
  replayFailed: "Impossible de réimporter cet élément. Le document actuel n’a pas été modifié.",
  replaySucceeded: "Élément réimporté depuis l’historique.",
  fileMissing: "Le fichier d’origine est introuvable. Relocalisez-le pour le réimporter sans modifier le document actuel.",
  fileChanged: "Le fichier a changé depuis son enregistrement. La version actuelle a été importée.",
  relocateFailed: "Impossible d’utiliser le fichier de remplacement.",
  corruptRecovered: "Le fichier d’historique endommagé a été conservé sous {file}. Un nouvel historique a été créé.",
  limitLabel: "Taille maximale de l’historique",
  limitDescription: "Conservez les imports réussis utilisés le plus récemment sur cet ordinateur.",
  limitFive: "5 éléments",
  limitTen: "10 éléments",
  limitUnlimited: "Illimité",
  limitTrimConfirm: "Limiter l’historique à {limit} supprimera {count} éléments plus anciens. Continuer ?",
  limitStatsFailed: "Impossible de vérifier la taille de l’historique. La limite n’a pas été modifiée."
};

const ja: HistoryCopy = {
  entry: "履歴",
  title: "読み込み・解析履歴",
  intro: "このデスクトップ版で正常に解析または保存した曲やカバーを再読み込みできます。",
  searchPlaceholder: "曲名、アーティスト、アルバム、ファイル、サイトを検索",
  filterLabel: "読み込み元",
  allSources: "すべて",
  sourceLink: "リンク",
  sourceSearch: "楽曲検索",
  sourceLocalAudio: "ローカル音声",
  sourceManualCover: "手動カバー",
  loading: "履歴を読み込み中…",
  loadFailed: "読み込み履歴を取得できませんでした。",
  retry: "再試行",
  empty: "正常に読み込まれた履歴はまだありません。",
  emptyFiltered: "検索または絞り込み条件に一致する履歴はありません。",
  resultCount: "{count} 件",
  importedAt: "{time} に読み込み",
  reimport: "再読み込み",
  reimporting: "再読み込み中…",
  relocate: "再指定",
  remove: "削除",
  loadMore: "さらに表示",
  clearAll: "履歴をすべて消去",
  clearConfirm: "読み込み履歴をすべて削除しますか？この操作は取り消せません。",
  removed: "履歴を削除しました。",
  cleared: "読み込み履歴を消去しました。",
  historySaveFailed: "読み込みは完了しましたが、履歴を保存できませんでした。",
  replayFailed: "この履歴を再読み込みできませんでした。現在の文書は変更されていません。",
  replaySucceeded: "履歴から再読み込みしました。",
  fileMissing: "元のファイルが見つかりません。再指定すれば、現在の文書を変更せずに再読み込みできます。",
  fileChanged: "記録後にファイルが変更されています。現在のファイルを読み込みました。",
  relocateFailed: "指定し直したファイルを使用できませんでした。",
  corruptRecovered: "破損した履歴ファイルを {file} として保存し、新しい履歴を開始しました。",
  limitLabel: "履歴の最大件数",
  limitDescription: "このデスクトップ版で最近使用した正常な読み込みを保持します。",
  limitFive: "5 件",
  limitTen: "10 件",
  limitUnlimited: "無制限",
  limitTrimConfirm: "上限を {limit} 件にすると、古い履歴 {count} 件が削除されます。続行しますか？",
  limitStatsFailed: "履歴件数を確認できなかったため、上限は変更されませんでした。"
};

const es: HistoryCopy = {
  entry: "Historial",
  title: "Historial de importaciones",
  intro: "Vuelve a importar canciones y portadas analizadas o guardadas correctamente en este equipo.",
  searchPlaceholder: "Buscar por título, artista, álbum, archivo o sitio",
  filterLabel: "Origen",
  allSources: "Todos los orígenes",
  sourceLink: "Enlace",
  sourceSearch: "Búsqueda de canción",
  sourceLocalAudio: "Audio local",
  sourceManualCover: "Portada manual",
  loading: "Cargando el historial…",
  loadFailed: "No se pudo cargar el historial de importaciones.",
  retry: "Reintentar",
  empty: "Todavía no se ha registrado ninguna importación correcta.",
  emptyFiltered: "Ningún elemento coincide con la búsqueda o el filtro.",
  resultCount: "{count} elementos",
  importedAt: "Importado el {time}",
  reimport: "Volver a importar",
  reimporting: "Importando de nuevo…",
  relocate: "Reubicar",
  remove: "Eliminar",
  loadMore: "Cargar más",
  clearAll: "Borrar todo el historial",
  clearConfirm: "¿Quieres eliminar todo el historial de importaciones? Esta acción no se puede deshacer.",
  removed: "Elemento eliminado del historial.",
  cleared: "Historial de importaciones borrado.",
  historySaveFailed: "La importación se completó, pero no se pudo guardar el historial.",
  replayFailed: "No se pudo volver a importar este elemento. El documento actual no cambió.",
  replaySucceeded: "Elemento importado de nuevo desde el historial.",
  fileMissing: "Falta el archivo original. Reubícalo para volver a importarlo sin cambiar el documento actual.",
  fileChanged: "El archivo ha cambiado desde que se registró. Se importó el archivo actual.",
  relocateFailed: "No se pudo usar el archivo de reemplazo.",
  corruptRecovered: "El historial dañado se conservó como {file}. Se inició un historial nuevo.",
  limitLabel: "Máximo del historial",
  limitDescription: "Conserva las importaciones correctas usadas más recientemente en este equipo.",
  limitFive: "5 elementos",
  limitTen: "10 elementos",
  limitUnlimited: "Sin límite",
  limitTrimConfirm: "Cambiar el límite a {limit} eliminará {count} elementos antiguos. ¿Continuar?",
  limitStatsFailed: "No se pudo comprobar el tamaño del historial. El límite no cambió."
};

export const importHistoryCopy: Record<Locale, HistoryCopy> = {
  zh,
  "zh-TW": zhTW,
  en,
  fr,
  ja,
  es
};

export function formatImportHistoryText(template: string, values: Record<string, string | number>) {
  return template.replace(/\{([A-Za-z][A-Za-z0-9_]*)\}/g, (match, key) => (
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  ));
}
