import type { Locale } from "@/lib/types";

const en = {
  entry: "History",
  title: "Import history",
  intro: "Reimport songs and covers that were successfully parsed or saved on this desktop.",
  searchPlaceholder: "Search title, artist, album, file, or site",
  filterLabel: "Source",
  allSources: "All sources",
  sourceLink: "Link",
  sourceSearch: "Song search",
  sourceLocalAudio: "Local audio",
  sourceManualCover: "Manual cover",
  sourceManualSave: "Manual save",
  loading: "Loading import history…",
  loadFailed: "Import history could not be loaded.",
  retry: "Try again",
  empty: "No successful imports have been recorded yet.",
  emptyFiltered: "No history items match this search or filter.",
  resultCount: "{count} items",
  importedAt: "Imported {time}",
  savedAt: "Saved or updated {time}",
  reimport: "Reimport",
  reimporting: "Reimporting…",
  loadManualSave: "Load save",
  loadingManualSave: "Loading save…",
  relocate: "Relocate",
  remove: "Delete",
  loadMore: "Load more",
  clearAll: "Clear all history",
  clearConfirm: "Delete every import history item? This cannot be undone.",
  removed: "History item deleted",
  cleared: "Import history cleared",
  historySaveFailed: "Import completed, but history was not updated",
  replayFailed: "Reimport failed; current document unchanged",
  replaySucceeded: "Reimported from history",
  fileMissing: "Original file missing; relocate it to reimport",
  fileChanged: "Original file changed; current version reimported",
  relocateFailed: "Selected file could not be used",
  corruptRecovered: "History file was damaged; backup saved and history rebuilt",
  limitLabel: "Maximum import history",
  limitDescription: "Keep the most recently used successful imports on this desktop.",
  limitFive: "5 items",
  limitTen: "10 items",
  limitUnlimited: "Unlimited",
  limitTrimConfirm: "Changing the limit to {limit} will delete {count} older history items. Continue?",
  limitStatsFailed: "The history size could not be checked. The limit was not changed.",
  manualSaveCreateLabel: "Save to history",
  manualSaveUpdateLabel: "Update current save",
  manualSaveCurrentLabel: "Save is up to date",
  manualSaveSavingLabel: "Saving…",
  manualSaveUnavailableLabel: "Save is temporarily unavailable",
  manualSaveCreated: "Manual save created",
  manualSaveUpdated: "Current save updated",
  manualSaveUnchanged: "Save already up to date",
  manualSaveUnavailable: "Current document cannot be saved yet",
  manualSaveNotFound: "Original save missing; saving again will create a new one",
  manualSaveFailed: "Manual save could not be written",
  manualSaveLoaded: "Manual save loaded"
};

type HistoryCopy = typeof en;

const zh: HistoryCopy = {
  entry: "历史记录",
  title: "导入/解析历史",
  intro: "重新导入在此桌面端成功解析或保存过的歌曲与封面。",
  searchPlaceholder: "搜索歌名、歌手、专辑、文件或网站",
  filterLabel: "来源",
  allSources: "全部来源",
  sourceLink: "链接解析",
  sourceSearch: "歌曲搜索",
  sourceLocalAudio: "本地音频",
  sourceManualCover: "手动封面",
  sourceManualSave: "手动存档",
  loading: "正在载入导入历史…",
  loadFailed: "无法载入导入历史。",
  retry: "重试",
  empty: "还没有成功导入的历史记录。",
  emptyFiltered: "没有符合当前搜索或筛选条件的记录。",
  resultCount: "共 {count} 条",
  importedAt: "导入于 {time}",
  savedAt: "存档或更新于 {time}",
  reimport: "重新导入",
  reimporting: "正在重新导入…",
  loadManualSave: "载入存档",
  loadingManualSave: "正在载入存档…",
  relocate: "重新定位",
  remove: "删除",
  loadMore: "加载更多",
  clearAll: "清空全部历史",
  clearConfirm: "确定删除全部导入历史吗？此操作无法撤销。",
  removed: "历史记录已删除",
  cleared: "导入历史已清空",
  historySaveFailed: "导入完成，但历史记录未更新",
  replayFailed: "重新导入失败，当前文档未更改",
  replaySucceeded: "已从历史记录重新导入",
  fileMissing: "原文件不存在，请重新定位后再导入",
  fileChanged: "原文件已变更，已按当前文件重新导入",
  relocateFailed: "所选文件无法使用",
  corruptRecovered: "历史文件损坏，已备份并重建历史记录",
  limitLabel: "最多保留历史",
  limitDescription: "在此桌面端保留最近使用的成功导入记录。",
  limitFive: "5 条",
  limitTen: "10 条",
  limitUnlimited: "无限",
  limitTrimConfirm: "改为最多 {limit} 条将删除较早的 {count} 条记录，是否继续？",
  limitStatsFailed: "无法核对历史记录数量，本次未更改上限。",
  manualSaveCreateLabel: "保存到历史记录",
  manualSaveUpdateLabel: "更新当前存档",
  manualSaveCurrentLabel: "存档已是最新",
  manualSaveSavingLabel: "正在保存",
  manualSaveUnavailableLabel: "暂时无法保存",
  manualSaveCreated: "手动存档已创建",
  manualSaveUpdated: "当前存档已更新",
  manualSaveUnchanged: "存档已是最新",
  manualSaveUnavailable: "当前文档暂不可保存",
  manualSaveNotFound: "原存档不存在，再次保存将新建存档",
  manualSaveFailed: "手动存档写入失败",
  manualSaveLoaded: "手动存档已载入"
};

const zhTW: HistoryCopy = {
  entry: "歷史記錄",
  title: "匯入／解析歷史",
  intro: "重新匯入曾在此桌面版成功解析或儲存的歌曲與封面。",
  searchPlaceholder: "搜尋歌名、演出者、專輯、檔案或網站",
  filterLabel: "來源",
  allSources: "全部來源",
  sourceLink: "連結解析",
  sourceSearch: "歌曲搜尋",
  sourceLocalAudio: "本機音訊",
  sourceManualCover: "手動封面",
  sourceManualSave: "手動存檔",
  loading: "正在載入匯入歷史…",
  loadFailed: "無法載入匯入歷史。",
  retry: "重試",
  empty: "目前還沒有成功匯入的歷史記錄。",
  emptyFiltered: "沒有符合目前搜尋或篩選條件的記錄。",
  resultCount: "共 {count} 筆",
  importedAt: "匯入於 {time}",
  savedAt: "存檔或更新於 {time}",
  reimport: "重新匯入",
  reimporting: "正在重新匯入…",
  loadManualSave: "載入存檔",
  loadingManualSave: "正在載入存檔…",
  relocate: "重新定位",
  remove: "刪除",
  loadMore: "載入更多",
  clearAll: "清除全部歷史",
  clearConfirm: "確定要刪除全部匯入歷史嗎？此操作無法復原。",
  removed: "歷史記錄已刪除",
  cleared: "匯入歷史已清除",
  historySaveFailed: "匯入完成，但歷史記錄未更新",
  replayFailed: "重新匯入失敗，目前文件未變更",
  replaySucceeded: "已從歷史記錄重新匯入",
  fileMissing: "原始檔案不存在，請重新定位後再匯入",
  fileChanged: "原始檔案已變更，已依目前檔案重新匯入",
  relocateFailed: "所選檔案無法使用",
  corruptRecovered: "歷史檔案損壞，已備份並重建歷史記錄",
  limitLabel: "最多保留歷史",
  limitDescription: "在此桌面版保留最近使用的成功匯入記錄。",
  limitFive: "5 筆",
  limitTen: "10 筆",
  limitUnlimited: "無限",
  limitTrimConfirm: "改為最多 {limit} 筆將刪除較早的 {count} 筆記錄，是否繼續？",
  limitStatsFailed: "無法確認歷史記錄數量，本次未變更上限。",
  manualSaveCreateLabel: "儲存到歷史記錄",
  manualSaveUpdateLabel: "更新目前存檔",
  manualSaveCurrentLabel: "存檔已是最新版本",
  manualSaveSavingLabel: "正在儲存",
  manualSaveUnavailableLabel: "暫時無法儲存",
  manualSaveCreated: "手動存檔已建立",
  manualSaveUpdated: "目前存檔已更新",
  manualSaveUnchanged: "存檔已是最新",
  manualSaveUnavailable: "目前文件暫時無法儲存",
  manualSaveNotFound: "原存檔不存在，再次儲存將建立新存檔",
  manualSaveFailed: "手動存檔寫入失敗",
  manualSaveLoaded: "手動存檔已載入"
};

const fr: HistoryCopy = {
  entry: "Historique",
  title: "Historique des imports",
  intro: "Réimportez les morceaux et pochettes analysés ou enregistrés avec succès sur cet ordinateur.",
  searchPlaceholder: "Rechercher un titre, artiste, album, fichier ou site",
  filterLabel: "Source",
  allSources: "Toutes les sources",
  sourceLink: "Lien",
  sourceSearch: "Recherche de morceau",
  sourceLocalAudio: "Audio local",
  sourceManualCover: "Pochette manuelle",
  sourceManualSave: "Sauvegarde manuelle",
  loading: "Chargement de l’historique…",
  loadFailed: "Impossible de charger l’historique des imports.",
  retry: "Réessayer",
  empty: "Aucun import réussi n’a encore été enregistré.",
  emptyFiltered: "Aucun élément ne correspond à cette recherche ou à ce filtre.",
  resultCount: "{count} éléments",
  importedAt: "Importé le {time}",
  savedAt: "Sauvegardé ou mis à jour le {time}",
  reimport: "Réimporter",
  reimporting: "Réimportation…",
  loadManualSave: "Charger la sauvegarde",
  loadingManualSave: "Chargement de la sauvegarde…",
  relocate: "Relocaliser",
  remove: "Supprimer",
  loadMore: "Afficher plus",
  clearAll: "Effacer tout l’historique",
  clearConfirm: "Supprimer tout l’historique des imports ? Cette action est irréversible.",
  removed: "Élément supprimé de l’historique",
  cleared: "Historique des imports effacé",
  historySaveFailed: "Import terminé, mais historique non mis à jour",
  replayFailed: "Échec de la réimportation ; document actuel inchangé",
  replaySucceeded: "Élément réimporté depuis l’historique",
  fileMissing: "Fichier d’origine introuvable ; relocalisez-le pour réimporter",
  fileChanged: "Fichier d’origine modifié ; version actuelle réimportée",
  relocateFailed: "Impossible d’utiliser le fichier sélectionné",
  corruptRecovered: "Fichier d’historique endommagé ; sauvegarde créée et historique reconstruit",
  limitLabel: "Taille maximale de l’historique",
  limitDescription: "Conservez les imports réussis utilisés le plus récemment sur cet ordinateur.",
  limitFive: "5 éléments",
  limitTen: "10 éléments",
  limitUnlimited: "Illimité",
  limitTrimConfirm: "Limiter l’historique à {limit} supprimera {count} éléments plus anciens. Continuer ?",
  limitStatsFailed: "Impossible de vérifier la taille de l’historique. La limite n’a pas été modifiée.",
  manualSaveCreateLabel: "Sauvegarder dans l’historique",
  manualSaveUpdateLabel: "Mettre à jour la sauvegarde actuelle",
  manualSaveCurrentLabel: "La sauvegarde est à jour",
  manualSaveSavingLabel: "Sauvegarde en cours…",
  manualSaveUnavailableLabel: "Sauvegarde temporairement indisponible",
  manualSaveCreated: "Sauvegarde manuelle créée",
  manualSaveUpdated: "Sauvegarde actuelle mise à jour",
  manualSaveUnchanged: "Sauvegarde déjà à jour",
  manualSaveUnavailable: "Impossible de sauvegarder ce document pour le moment",
  manualSaveNotFound: "Sauvegarde d’origine introuvable ; une nouvelle sera créée au prochain enregistrement",
  manualSaveFailed: "Impossible d’écrire la sauvegarde manuelle",
  manualSaveLoaded: "Sauvegarde manuelle chargée"
};

const ja: HistoryCopy = {
  entry: "履歴",
  title: "読み込み・解析履歴",
  intro: "このデスクトップ版で正常に解析または保存した曲やカバーを再読み込みできます。",
  searchPlaceholder: "曲名、アーティスト、アルバム、ファイル、サイトを検索",
  filterLabel: "読み込み元",
  allSources: "すべて",
  sourceLink: "リンク",
  sourceSearch: "楽曲検索",
  sourceLocalAudio: "ローカル音声",
  sourceManualCover: "手動カバー",
  sourceManualSave: "手動保存",
  loading: "履歴を読み込み中…",
  loadFailed: "読み込み履歴を取得できませんでした。",
  retry: "再試行",
  empty: "正常に読み込まれた履歴はまだありません。",
  emptyFiltered: "検索または絞り込み条件に一致する履歴はありません。",
  resultCount: "{count} 件",
  importedAt: "{time} に読み込み",
  savedAt: "{time} に保存または更新",
  reimport: "再読み込み",
  reimporting: "再読み込み中…",
  loadManualSave: "保存を読み込む",
  loadingManualSave: "保存を読み込み中…",
  relocate: "再指定",
  remove: "削除",
  loadMore: "さらに表示",
  clearAll: "履歴をすべて消去",
  clearConfirm: "読み込み履歴をすべて削除しますか？この操作は取り消せません。",
  removed: "履歴を削除しました",
  cleared: "読み込み履歴を消去しました",
  historySaveFailed: "読み込みは完了しましたが、履歴を更新できませんでした",
  replayFailed: "再読み込みに失敗しました。現在の文書は変更されていません",
  replaySucceeded: "履歴から再読み込みしました",
  fileMissing: "元のファイルがありません。再指定して読み込んでください",
  fileChanged: "元のファイルが変更されたため、現在の内容を再読み込みしました",
  relocateFailed: "選択したファイルを使用できません",
  corruptRecovered: "履歴ファイルが破損していたため、バックアップして履歴を再作成しました",
  limitLabel: "履歴の最大件数",
  limitDescription: "このデスクトップ版で最近使用した正常な読み込みを保持します。",
  limitFive: "5 件",
  limitTen: "10 件",
  limitUnlimited: "無制限",
  limitTrimConfirm: "上限を {limit} 件にすると、古い履歴 {count} 件が削除されます。続行しますか？",
  limitStatsFailed: "履歴件数を確認できなかったため、上限は変更されませんでした。",
  manualSaveCreateLabel: "履歴に保存",
  manualSaveUpdateLabel: "現在の保存を更新",
  manualSaveCurrentLabel: "保存は最新です",
  manualSaveSavingLabel: "保存中…",
  manualSaveUnavailableLabel: "現在は保存できません",
  manualSaveCreated: "手動保存を作成しました",
  manualSaveUpdated: "現在の保存を更新しました",
  manualSaveUnchanged: "保存は最新です",
  manualSaveUnavailable: "現在の文書は保存できません",
  manualSaveNotFound: "元の保存がありません。再度保存すると新規作成されます",
  manualSaveFailed: "手動保存を書き込めませんでした",
  manualSaveLoaded: "手動保存を読み込みました"
};

const es: HistoryCopy = {
  entry: "Historial",
  title: "Historial de importaciones",
  intro: "Vuelve a importar canciones y portadas analizadas o guardadas correctamente en este equipo.",
  searchPlaceholder: "Buscar por título, artista, álbum, archivo o sitio",
  filterLabel: "Origen",
  allSources: "Todos los orígenes",
  sourceLink: "Enlace",
  sourceSearch: "Búsqueda de canción",
  sourceLocalAudio: "Audio local",
  sourceManualCover: "Portada manual",
  sourceManualSave: "Guardado manual",
  loading: "Cargando el historial…",
  loadFailed: "No se pudo cargar el historial de importaciones.",
  retry: "Reintentar",
  empty: "Todavía no se ha registrado ninguna importación correcta.",
  emptyFiltered: "Ningún elemento coincide con la búsqueda o el filtro.",
  resultCount: "{count} elementos",
  importedAt: "Importado el {time}",
  savedAt: "Guardado o actualizado el {time}",
  reimport: "Volver a importar",
  reimporting: "Importando de nuevo…",
  loadManualSave: "Cargar guardado",
  loadingManualSave: "Cargando guardado…",
  relocate: "Reubicar",
  remove: "Eliminar",
  loadMore: "Cargar más",
  clearAll: "Borrar todo el historial",
  clearConfirm: "¿Quieres eliminar todo el historial de importaciones? Esta acción no se puede deshacer.",
  removed: "Elemento eliminado del historial",
  cleared: "Historial de importaciones borrado",
  historySaveFailed: "Importación completada, pero el historial no se actualizó",
  replayFailed: "Error al volver a importar; el documento actual no cambió",
  replaySucceeded: "Elemento importado de nuevo desde el historial",
  fileMissing: "Falta el archivo original; reubícalo para volver a importarlo",
  fileChanged: "El archivo original cambió; se importó la versión actual",
  relocateFailed: "No se pudo usar el archivo seleccionado",
  corruptRecovered: "Historial dañado; se guardó una copia y se reconstruyó",
  limitLabel: "Máximo del historial",
  limitDescription: "Conserva las importaciones correctas usadas más recientemente en este equipo.",
  limitFive: "5 elementos",
  limitTen: "10 elementos",
  limitUnlimited: "Sin límite",
  limitTrimConfirm: "Cambiar el límite a {limit} eliminará {count} elementos antiguos. ¿Continuar?",
  limitStatsFailed: "No se pudo comprobar el tamaño del historial. El límite no cambió.",
  manualSaveCreateLabel: "Guardar en el historial",
  manualSaveUpdateLabel: "Actualizar el guardado actual",
  manualSaveCurrentLabel: "El guardado está al día",
  manualSaveSavingLabel: "Guardando…",
  manualSaveUnavailableLabel: "Guardado no disponible temporalmente",
  manualSaveCreated: "Guardado manual creado",
  manualSaveUpdated: "Guardado actual actualizado",
  manualSaveUnchanged: "El guardado ya está al día",
  manualSaveUnavailable: "Este documento aún no se puede guardar",
  manualSaveNotFound: "Falta el guardado original; al guardar se creará uno nuevo",
  manualSaveFailed: "No se pudo escribir el guardado manual",
  manualSaveLoaded: "Guardado manual cargado"
};

export const importHistoryCopy: Record<Locale, HistoryCopy> = {
  zh,
  "zh-TW": zhTW,
  en,
  fr,
  ja,
  es
};

export function formatImportHistoryText(template: string, values: Record<string, string | number>) {
  return template.replace(/\{([A-Za-z][A-Za-z0-9_]*)\}/g, (match, key) => (
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  ));
}
