import type { Locale } from "@/lib/types";

type Copy = { settingsFailed: string; loadFailed: string; restored: string; restoredDetail: string; history: string; saveFailed: string; saveDetail: string; retry: string; historyRecovered: string; close: string };
export const notificationCopy: Record<Locale, Copy> = {
  zh: { settingsFailed: "设置保存失败", loadFailed: "草稿恢复失败", restored: "已恢复上次的草稿", restoredDetail: "编辑内容已自动保存，可以接着制作。", history: "查看历史", saveFailed: "草稿保存失败", saveDetail: "最新修改尚未保存，请重试。", retry: "重试保存", historyRecovered: "历史记录恢复提示", close: "关闭通知" },
  "zh-TW": { settingsFailed: "設定儲存失敗", loadFailed: "草稿恢復失敗", restored: "已恢復上次的草稿", restoredDetail: "編輯內容已自動儲存，可以繼續製作。", history: "查看歷史", saveFailed: "草稿儲存失敗", saveDetail: "最新修改尚未儲存，請重試。", retry: "重試儲存", historyRecovered: "歷史記錄恢復提示", close: "關閉通知" },
  en: { settingsFailed: "Could not save settings", loadFailed: "Could not restore the draft", restored: "Your last draft has been restored", restoredDetail: "Your edits were saved automatically. You can carry on editing.", history: "View history", saveFailed: "Could not save the draft", saveDetail: "Your latest changes have not been saved. Please try again.", retry: "Retry saving", historyRecovered: "History recovery", close: "Dismiss notification" },
  fr: { settingsFailed: "Échec de l’enregistrement des paramètres", loadFailed: "Échec de la restauration du brouillon", restored: "Votre dernier brouillon a été restauré", restoredDetail: "Vos modifications ont été enregistrées automatiquement. Vous pouvez continuer.", history: "Voir l’historique", saveFailed: "Échec de l’enregistrement du brouillon", saveDetail: "Vos dernières modifications ne sont pas enregistrées. Réessayez.", retry: "Réessayer", historyRecovered: "Récupération de l’historique", close: "Fermer la notification" },
  ja: { settingsFailed: "設定を保存できませんでした", loadFailed: "下書きを復元できませんでした", restored: "前回の下書きを復元しました", restoredDetail: "編集内容は自動保存されています。続けて編集できます。", history: "履歴を見る", saveFailed: "下書きを保存できませんでした", saveDetail: "最新の変更は保存されていません。再試行してください。", retry: "保存を再試行", historyRecovered: "履歴の復旧について", close: "通知を閉じる" },
  es: { settingsFailed: "No se pudo guardar la configuración", loadFailed: "No se pudo restaurar el borrador", restored: "Se ha restaurado tu último borrador", restoredDetail: "Tus cambios se guardaron automáticamente. Puedes seguir editando.", history: "Ver historial", saveFailed: "No se pudo guardar el borrador", saveDetail: "Tus últimos cambios no se han guardado. Inténtalo de nuevo.", retry: "Reintentar", historyRecovered: "Recuperación del historial", close: "Cerrar notificación" }
};
