export const PROJECT_SIGNATURE_OWNER = "Qrzzzz";
export const PROJECT_SIGNATURE_REPOSITORY = "/lyrics-card-generator";
export const PROJECT_SIGNATURE_TEXT = `${PROJECT_SIGNATURE_OWNER}${PROJECT_SIGNATURE_REPOSITORY}`;
