import type { Locale } from "@/lib/types";

export type AIErrorCode = "missing_api_key" | "missing_model" | "missing_base_url" | "invalid_base_url" | "insecure_base_url" | "invalid_request" | "request_too_large" | "empty_prompt" | "network" | "timeout" | "stream_idle_timeout" | "stream_deadline_exceeded" | "provider_error" | "response_too_large" | "empty_stream" | "invalid_response" | "stream_event_too_large" | "stream_buffer_too_large" | "stream_output_too_large" | "stream_reasoning_too_large" | "empty_response" | "cancelled" | "request_failed" | "api_key_read_failed" | "secure_storage_unavailable" | "app_origin_configuration_error" | "cross_origin_request" | "missing_app_request_marker" | "unsupported_media_type" | "unknown";

export const AI_ERROR_CODES: readonly AIErrorCode[] = [
  "missing_api_key", "missing_model", "missing_base_url", "invalid_base_url", "insecure_base_url", "invalid_request",
  "request_too_large", "empty_prompt", "network", "timeout", "stream_idle_timeout", "stream_deadline_exceeded",
  "provider_error", "response_too_large", "empty_stream", "invalid_response", "stream_event_too_large",
  "stream_buffer_too_large", "stream_output_too_large", "stream_reasoning_too_large", "empty_response",
  "cancelled", "request_failed", "api_key_read_failed", "secure_storage_unavailable",
  "app_origin_configuration_error", "cross_origin_request", "missing_app_request_marker", "unsupported_media_type", "unknown"
];

const copy: Record<Locale, Record<Exclude<AIErrorCode, "app_origin_configuration_error">, string>> = {
  zh: {
    missing_api_key: "请先在设置中配置 API Key", missing_model: "请先在设置中配置模型", missing_base_url: "请先在设置中配置 Base URL", invalid_base_url: "Base URL 无效，请检查设置。", insecure_base_url: "远程 AI Base URL 必须使用 HTTPS。HTTP 仅支持 localhost 或回环 IP 地址。", invalid_request: "AI 翻译请求无效。", request_too_large: "AI 翻译请求内容超过安全上限。", empty_prompt: "歌词为空，请先输入歌词。", network: "网络请求失败，请检查 Base URL、网络连接和服务状态。", timeout: "AI 请求超时，请稍后重试。", stream_idle_timeout: "AI 数据流等待超时，请稍后重试。", stream_deadline_exceeded: "AI 请求超过总时限，请稍后重试。", provider_error: "AI 服务返回错误。", response_too_large: "AI 服务返回的数据超过安全上限。", empty_stream: "AI 服务未返回可读取的数据流。", invalid_response: "AI 服务返回了无法解析的响应。", stream_event_too_large: "AI 服务返回的单个流事件过大。", stream_buffer_too_large: "AI 数据流缓冲区超过安全上限。", stream_output_too_large: "AI 翻译结果超过安全上限。", stream_reasoning_too_large: "AI 推理内容超过安全上限。", empty_response: "AI 返回为空，请重试或更换模型。", cancelled: "AI 翻译已取消。", request_failed: "AI 翻译请求失败。", api_key_read_failed: "无法读取已保存的 API Key，请重新输入。", secure_storage_unavailable: "系统安全存储不可用，无法安全保存 API Key。", cross_origin_request: "该请求不是来自当前应用页面。", missing_app_request_marker: "该请求缺少应用标记。", unsupported_media_type: "该请求的内容格式不受支持。", unknown: "AI 翻译请求失败，请检查网络和接口设置。"
  },
  "zh-TW": {
    missing_api_key: "請先在設定中設定 API Key", missing_model: "請先在設定中設定模型", missing_base_url: "請先在設定中設定 Base URL", invalid_base_url: "Base URL 無效，請檢查設定。", insecure_base_url: "遠端 AI Base URL 必須使用 HTTPS。HTTP 僅支援 localhost 或回送 IP 位址。", invalid_request: "AI 翻譯請求無效。", request_too_large: "AI 翻譯請求內容超過安全上限。", empty_prompt: "歌詞為空，請先輸入歌詞。", network: "網路請求失敗，請檢查 Base URL、網路連線和服務狀態。", timeout: "AI 請求逾時，請稍後重試。", stream_idle_timeout: "AI 資料串流等候逾時，請稍後重試。", stream_deadline_exceeded: "AI 請求超過總時限，請稍後重試。", provider_error: "AI 服務傳回錯誤。", response_too_large: "AI 服務傳回的資料超過安全上限。", empty_stream: "AI 服務未傳回可讀取的資料串流。", invalid_response: "AI 服務傳回了無法解析的回應。", stream_event_too_large: "AI 服務傳回的單一串流事件過大。", stream_buffer_too_large: "AI 資料串流緩衝區超過安全上限。", stream_output_too_large: "AI 翻譯結果超過安全上限。", stream_reasoning_too_large: "AI 推理內容超過安全上限。", empty_response: "AI 回傳內容為空，請重試或更換模型。", cancelled: "AI 翻譯已取消。", request_failed: "AI 翻譯請求失敗。", api_key_read_failed: "無法讀取已儲存的 API Key，請重新輸入。", secure_storage_unavailable: "系統安全儲存空間無法使用，因此無法安全儲存 API Key。", cross_origin_request: "這個請求並非來自目前的應用程式頁面。", missing_app_request_marker: "這個請求缺少應用程式標記。", unsupported_media_type: "不支援這個請求的內容格式。", unknown: "AI 翻譯請求失敗，請檢查網路和介面設定。"
  },
  en: {
    missing_api_key: "Configure an API key in Settings", missing_model: "Configure a model in Settings", missing_base_url: "Configure a Base URL in Settings", invalid_base_url: "The Base URL is invalid. Check Settings.", insecure_base_url: "Remote AI Base URLs must use HTTPS. HTTP is supported only for localhost or loopback IP addresses.", invalid_request: "The AI translation request is invalid.", request_too_large: "The AI translation request exceeds the safe size limit.", empty_prompt: "Enter lyrics before starting a translation.", network: "The network request failed. Check the Base URL, connection, and service status.", timeout: "The AI request timed out. Try again later.", stream_idle_timeout: "The AI stream was idle for too long. Try again later.", stream_deadline_exceeded: "The AI request exceeded its total deadline. Try again later.", provider_error: "The AI provider returned an error.", response_too_large: "The AI provider returned more data than allowed.", empty_stream: "The AI provider did not return a readable stream.", invalid_response: "The AI provider returned an unreadable response.", stream_event_too_large: "The AI provider returned an oversized stream event.", stream_buffer_too_large: "The AI stream buffer exceeded its safe limit.", stream_output_too_large: "The AI translation output exceeded its safe limit.", stream_reasoning_too_large: "The AI reasoning output exceeded its safe limit.", empty_response: "The AI response was empty. Retry or choose another model.", cancelled: "AI translation was cancelled.", request_failed: "The AI translation request failed.", api_key_read_failed: "The saved API key could not be read. Enter it again.", secure_storage_unavailable: "Secure system storage is unavailable, so the API key cannot be saved safely.", cross_origin_request: "This request did not come from the current app page.", missing_app_request_marker: "This request is missing the app marker.", unsupported_media_type: "This request format is not supported.", unknown: "AI translation failed. Check the network and provider settings."
  },
  fr: {
    missing_api_key: "Configurez une clé API dans les paramètres", missing_model: "Configurez un modèle dans les paramètres", missing_base_url: "Configurez une URL de base dans les paramètres", invalid_base_url: "L’URL de base est invalide. Vérifiez les paramètres.", insecure_base_url: "Les URL de base IA distantes doivent utiliser HTTPS. HTTP est réservé à localhost et aux adresses IP de bouclage.", invalid_request: "La demande de traduction IA est invalide.", request_too_large: "La demande de traduction IA dépasse la limite de sécurité.", empty_prompt: "Saisissez des paroles avant de lancer la traduction.", network: "La requête réseau a échoué. Vérifiez l’URL de base, la connexion et le service.", timeout: "La requête IA a expiré. Réessayez plus tard.", stream_idle_timeout: "Le flux IA est resté inactif trop longtemps. Réessayez plus tard.", stream_deadline_exceeded: "La requête IA a dépassé sa durée totale. Réessayez plus tard.", provider_error: "Le fournisseur d’IA a renvoyé une erreur.", response_too_large: "Le fournisseur d’IA a renvoyé trop de données.", empty_stream: "Le fournisseur d’IA n’a pas renvoyé de flux lisible.", invalid_response: "Le fournisseur d’IA a renvoyé une réponse illisible.", stream_event_too_large: "Le fournisseur d’IA a renvoyé un événement de flux trop volumineux.", stream_buffer_too_large: "Le tampon du flux IA a dépassé sa limite de sécurité.", stream_output_too_large: "La traduction IA a dépassé sa limite de sécurité.", stream_reasoning_too_large: "Le raisonnement IA a dépassé sa limite de sécurité.", empty_response: "La réponse de l’IA est vide. Réessayez ou changez de modèle.", cancelled: "La traduction IA a été annulée.", request_failed: "La demande de traduction IA a échoué.", api_key_read_failed: "Impossible de lire la clé API enregistrée. Saisissez-la de nouveau.", secure_storage_unavailable: "Le stockage sécurisé du système est indisponible ; la clé API ne peut pas être enregistrée en toute sécurité.", cross_origin_request: "Cette requête ne provient pas de la page actuelle de l’application.", missing_app_request_marker: "Cette requête ne contient pas le marqueur de l’application.", unsupported_media_type: "Le format de cette requête n’est pas pris en charge.", unknown: "La traduction IA a échoué. Vérifiez le réseau et les paramètres du fournisseur."
  },
  ja: {
    missing_api_key: "設定画面で API キーを設定してください", missing_model: "設定画面でモデルを設定してください", missing_base_url: "設定画面で Base URL を設定してください", invalid_base_url: "Base URL が無効です。設定を確認してください。", insecure_base_url: "リモートの AI Base URL には HTTPS が必要です。HTTP は localhost またはループバック IP でのみ使用できます。", invalid_request: "AI 翻訳リクエストが無効です。", request_too_large: "AI 翻訳リクエストが安全上限を超えています。", empty_prompt: "翻訳を始める前に歌詞を入力してください。", network: "ネットワーク要求に失敗しました。Base URL、接続、サービス状態を確認してください。", timeout: "AI リクエストがタイムアウトしました。後でもう一度お試しください。", stream_idle_timeout: "AI ストリームの待機時間を超えました。もう一度お試しください。", stream_deadline_exceeded: "AI リクエストが全体の制限時間を超えました。", provider_error: "AI プロバイダーがエラーを返しました。", response_too_large: "AI プロバイダーの応答が安全上限を超えています。", empty_stream: "AI プロバイダーから読み取り可能なストリームが返されませんでした。", invalid_response: "AI プロバイダーから解析できない応答が返されました。", stream_event_too_large: "AI ストリームの単一イベントが大きすぎます。", stream_buffer_too_large: "AI ストリームのバッファーが安全上限を超えました。", stream_output_too_large: "AI 翻訳結果が安全上限を超えました。", stream_reasoning_too_large: "AI 推論内容が安全上限を超えました。", empty_response: "AI の応答が空です。再試行するか別のモデルを選んでください。", cancelled: "AI 翻訳をキャンセルしました。", request_failed: "AI 翻訳リクエストに失敗しました。", api_key_read_failed: "保存済みの API キーを読み取れませんでした。もう一度入力してください。", secure_storage_unavailable: "システムの安全なストレージを利用できないため、API キーを安全に保存できません。", cross_origin_request: "このリクエストは現在のアプリ画面から送信されていません。", missing_app_request_marker: "このリクエストにアプリ識別子がありません。", unsupported_media_type: "このリクエスト形式には対応していません。", unknown: "AI 翻訳に失敗しました。ネットワークとプロバイダー設定を確認してください。"
  },
  es: {
    missing_api_key: "Configura una clave API en los ajustes", missing_model: "Configura un modelo en los ajustes", missing_base_url: "Configura una URL base en los ajustes", invalid_base_url: "La URL base no es válida. Revisa la configuración.", insecure_base_url: "Las URL base de IA remotas deben usar HTTPS. HTTP solo se admite para localhost o direcciones IP de bucle invertido.", invalid_request: "La solicitud de traducción con IA no es válida.", request_too_large: "La solicitud de traducción con IA supera el límite seguro.", empty_prompt: "Escribe la letra antes de iniciar la traducción.", network: "La solicitud de red falló. Revisa la URL base, la conexión y el servicio.", timeout: "La solicitud de IA agotó el tiempo. Inténtalo de nuevo más tarde.", stream_idle_timeout: "El flujo de IA estuvo inactivo demasiado tiempo. Inténtalo de nuevo.", stream_deadline_exceeded: "La solicitud de IA superó su tiempo total.", provider_error: "El proveedor de IA devolvió un error.", response_too_large: "El proveedor de IA devolvió demasiados datos.", empty_stream: "El proveedor de IA no devolvió un flujo legible.", invalid_response: "El proveedor de IA devolvió una respuesta ilegible.", stream_event_too_large: "El proveedor de IA devolvió un evento de flujo demasiado grande.", stream_buffer_too_large: "El búfer del flujo de IA superó el límite seguro.", stream_output_too_large: "La traducción de IA superó el límite seguro.", stream_reasoning_too_large: "El razonamiento de IA superó el límite seguro.", empty_response: "La respuesta de IA está vacía. Reintenta o elige otro modelo.", cancelled: "La traducción con IA se canceló.", request_failed: "La solicitud de traducción con IA falló.", api_key_read_failed: "No se pudo leer la clave API guardada. Vuelve a introducirla.", secure_storage_unavailable: "El almacenamiento seguro del sistema no está disponible, por lo que no se puede guardar la clave API de forma segura.", cross_origin_request: "Esta solicitud no procede de la página actual de la aplicación.", missing_app_request_marker: "Esta solicitud no incluye el identificador de la aplicación.", unsupported_media_type: "El formato de esta solicitud no es compatible.", unknown: "La traducción con IA falló. Revisa la red y la configuración del proveedor."
  }
};

const appOriginConfigurationCopy: Record<Locale, string> = {
  zh: "应用来源策略配置错误，请检查服务器部署设置。",
  "zh-TW": "應用程式來源原則設定錯誤，請檢查伺服器部署設定。",
  en: "The app origin policy is misconfigured. Check the server deployment settings.",
  fr: "La politique d’origine de l’application est mal configurée. Vérifiez le déploiement du serveur.",
  ja: "アプリのオリジンポリシー設定が無効です。サーバーのデプロイ設定を確認してください。",
  es: "La política de origen de la aplicación está mal configurada. Revisa el despliegue del servidor."
};

export function getAIErrorMessage(locale: Locale, code: AIErrorCode, diagnostic?: string) {
  const primary = code === "app_origin_configuration_error"
    ? appOriginConfigurationCopy[locale]
    : copy[locale][code] ?? copy[locale].unknown;
  return diagnostic && code === "provider_error" ? `${primary} (${diagnostic.slice(0, 300)})` : primary;
}

export function parseSerializedAIError(message: string) {
  // Electron may prepend IPC and Error wrappers; remove only those envelopes
  // before recovering the stable application error code and diagnostic.
  const normalized = message.replace(/^Error invoking remote method '[^']+':\s*/i, "").replace(/^Error:\s*/i, "");
  const match = normalized.match(/^AI_ERROR:([a-z_]+)(?::([\s\S]*))?$/);
  return match ? { code: match[1] as AIErrorCode, diagnostic: match[2]?.trim() || undefined } : { code: "unknown" as const, diagnostic: undefined };
}
