import type { Locale } from "@/lib/types";

type AIUiCopy = {
  settings: string;
  settingsTitle: string;
  settingsDescription: string;
  languageSection: string;
  aiSection: string;
  baseUrl: string;
  baseUrlTip: string;
  apiKey: string;
  apiKeyPlaceholder: string;
  apiKeyConfigured: string;
  apiKeyTip: string;
  clearApiKey: string;
  clearingApiKey: string;
  clearApiKeyConfirm: string;
  apiKeyCleared: string;
  apiKeyClearFailed: string;
  model: string;
  modelPlaceholder: string;
  modelTip: string;
  temperature: string;
  temperatureTip: string;
  defaultStyle: string;
  defaultStyleTip: string;
  defaultReasoning: string;
  reasoningHint: string;
  save: string;
  saving: string;
  changesPending: string;
  loadFailed: string;
  saveFailed: string;
  cancel: string;
  close: string;
  back: string;
  stopAndBack: string;
  settingsSaved: string;
  settingsLoadFailed: string;
  settingsSaveFailed: string;
  aiTranslate: string;
  aiTranslateTitle: string;
  aiTranslateDescription: string;
  reasoning: string;
  reasoningDescription: string;
  phaseConnecting: string;
  phaseConnected: string;
  phaseReasoning: string;
  phaseTranslating: string;
  connectingTip: string;
  connectedTip: string;
  reasoningStream: string;
  live: string;
  reasoningWaiting: string;
  translationWaiting: string;
  translate: string;
  translating: string;
  stop: string;
  streamPreview: string;
  lyricsEmpty: string;
  configureFirst: string;
  overwriteConfirm: string;
  emptyResponse: string;
  translated: string;
  cancelled: string;
};

const AI_UI_COPY: Record<Locale, AIUiCopy> = {
  zh: {
    settings: "设置",
    settingsTitle: "应用设置",
    settingsDescription: "管理界面语言和 AI 歌词翻译连接。",
    languageSection: "界面语言",
    aiSection: "AI 歌词翻译",
    baseUrl: "Base URL",
    baseUrlTip: "填写厂商提供的 OpenAI-compatible API 根地址。应用会自动在末尾追加 /chat/completions；如果地址已包含该路径则不会重复追加。",
    apiKey: "API Key",
    apiKeyPlaceholder: "输入 API Key",
    apiKeyConfigured: "已配置；留空可继续使用，输入新值可替换",
    apiKeyTip: "填写 AI 厂商创建的访问密钥，不要求以 sk- 开头。正式桌面版会通过系统安全存储加密并持久保存，重启软件无需重新输入；仅 127.0.0.1 网页开发预览因没有系统密钥库而只在当前会话保留。界面不会回显完整密钥。",
    clearApiKey: "清除 API Key",
    clearingApiKey: "正在清除...",
    clearApiKeyConfirm: "确定清除已保存的 API Key 吗？其他 AI 设置会保留。",
    apiKeyCleared: "API Key 已清除",
    apiKeyClearFailed: "无法清除 API Key。",
    model: "Model",
    modelPlaceholder: "输入厂商提供的模型标识符",
    modelTip: "必须准确填写 AI 厂商文档中的模型标识符；这不是显示名称，也不会由应用自动猜测或推荐。",
    temperature: "Temperature",
    temperatureTip: "控制表达随机度，范围 0–2，默认 0.7。数值越低越稳定；Reasoning 模式下部分厂商会忽略此项。",
    defaultStyle: "默认翻译风格",
    defaultStyleTip: "决定每次打开 AI 翻译时预选的单一风格，仍可在翻译前临时切换。",
    defaultReasoning: "默认启用 Reasoning",
    reasoningHint: "启用后会请求模型的推理模式，并在翻译面板实时展示厂商返回的 reasoning_content。厂商不支持时可能不显示推理过程。",
    save: "保存设置",
    saving: "保存中...",
    changesPending: "等待保存",
    loadFailed: "加载失败",
    saveFailed: "保存失败",
    cancel: "取消",
    close: "关闭",
    back: "返回",
    stopAndBack: "停止翻译并返回",
    settingsSaved: "设置已保存",
    settingsLoadFailed: "无法读取 AI 设置。",
    settingsSaveFailed: "无法保存 AI 设置。",
    aiTranslate: "AI 翻译",
    aiTranslateTitle: "AI 歌词翻译",
    aiTranslateDescription: "选择一种风格，只生成一版简体中文译文。",
    reasoning: "使用 Reasoning",
    reasoningDescription: "模型会先推理，再流式输出最终译文；推理内容不会写入歌词框。",
    phaseConnecting: "正在连接 AI 接口",
    phaseConnected: "接口已连接，等待模型返回首个数据块",
    phaseReasoning: "模型正在推理",
    phaseTranslating: "模型正在生成译文",
    connectingTip: "如果长时间停留在这里，请检查 Base URL、API Key、模型标识符和网络连接。",
    connectedTip: "接口已接受请求；等待时间取决于模型负载、歌词长度和是否启用 Reasoning。",
    reasoningStream: "Reasoning 实时过程",
    live: "实时",
    reasoningWaiting: "正在等待模型返回 reasoning_content…",
    translationWaiting: "推理完成后，译文会在这里逐段出现。",
    translate: "开始翻译",
    translating: "正在翻译...",
    stop: "停止",
    streamPreview: "流式译文",
    lyricsEmpty: "歌词为空，请先输入歌词。",
    configureFirst: "AI 设置不完整，请先配置 API Key 和模型。",
    overwriteConfirm: "歌词翻译文本框已有内容。继续会覆盖现有译文，确定继续吗？",
    emptyResponse: "AI 返回为空，请重试或更换模型。",
    translated: "AI 翻译已写入歌词翻译文本框。",
    cancelled: "AI 翻译已取消。"
  },
  "zh-TW": {
    settings: "設定",
    settingsTitle: "應用程式設定",
    settingsDescription: "管理介面語言與 AI 歌詞翻譯連線。",
    languageSection: "介面語言",
    aiSection: "AI 歌詞翻譯",
    baseUrl: "Base URL",
    baseUrlTip: "請填入服務商提供的 OpenAI-compatible API 根網址。應用程式會自動在末尾加入 /chat/completions；若網址已包含此路徑則不會重複加入。",
    apiKey: "API Key",
    apiKeyPlaceholder: "輸入 API Key",
    apiKeyConfigured: "已設定；留空可繼續使用，輸入新值可取代原有金鑰",
    apiKeyTip: "請填入 AI 服務商建立的存取金鑰，不要求以 sk- 開頭。正式桌面版會透過系統安全儲存加密並持久保存，重新啟動軟體後無須再次輸入；只有 127.0.0.1 網頁開發預覽因沒有系統金鑰庫而僅在目前工作階段保留。介面不會顯示完整金鑰。",
    clearApiKey: "清除 API Key",
    clearingApiKey: "正在清除...",
    clearApiKeyConfirm: "確定要清除已儲存的 API Key 嗎？其他 AI 設定會保留。",
    apiKeyCleared: "API Key 已清除",
    apiKeyClearFailed: "無法清除 API Key。",
    model: "Model",
    modelPlaceholder: "輸入服務商提供的模型識別碼",
    modelTip: "必須準確填入 AI 服務商文件中的模型識別碼；這不是顯示名稱，應用程式也不會自動猜測或推薦。",
    temperature: "Temperature",
    temperatureTip: "控制輸出的隨機程度，範圍為 0–2，預設值為 0.7。數值越低越穩定；Reasoning 模式下部分服務商可能忽略此項。",
    defaultStyle: "預設翻譯風格",
    defaultStyleTip: "決定每次開啟 AI 翻譯時預先選取的單一風格，仍可在翻譯前臨時切換。",
    defaultReasoning: "預設啟用 Reasoning",
    reasoningHint: "啟用後會要求模型使用推理模式，並在翻譯面板即時顯示服務商回傳的 reasoning_content。服務商不支援時可能不會顯示推理過程。",
    save: "儲存設定",
    saving: "儲存中...",
    changesPending: "等待儲存",
    loadFailed: "載入失敗",
    saveFailed: "儲存失敗",
    cancel: "取消",
    close: "關閉",
    back: "返回",
    stopAndBack: "停止翻譯並返回",
    settingsSaved: "設定已儲存",
    settingsLoadFailed: "無法讀取 AI 設定。",
    settingsSaveFailed: "無法儲存 AI 設定。",
    aiTranslate: "AI 翻譯",
    aiTranslateTitle: "AI 歌詞翻譯",
    aiTranslateDescription: "選擇一種風格，只生成一版繁體中文譯文。",
    reasoning: "使用 Reasoning",
    reasoningDescription: "模型會先進行推理，再串流輸出最終譯文；推理內容不會寫入歌詞欄位。",
    phaseConnecting: "正在連線至 AI 介面",
    phaseConnected: "介面已連線，正在等待模型回傳第一個資料區塊",
    phaseReasoning: "模型正在推理",
    phaseTranslating: "模型正在生成譯文",
    connectingTip: "若長時間停留在此處，請檢查 Base URL、API Key、模型識別碼與網路連線。",
    connectedTip: "介面已接受請求；等待時間取決於模型負載、歌詞長度及是否啟用 Reasoning。",
    reasoningStream: "Reasoning 即時過程",
    live: "即時",
    reasoningWaiting: "正在等待模型回傳 reasoning_content…",
    translationWaiting: "推理完成後，譯文會在這裡逐段顯示。",
    translate: "開始翻譯",
    translating: "翻譯中...",
    stop: "停止",
    streamPreview: "串流譯文",
    lyricsEmpty: "歌詞為空，請先輸入歌詞。",
    configureFirst: "AI 設定不完整，請先設定 API Key 與模型。",
    overwriteConfirm: "歌詞翻譯欄位已有內容。繼續操作將覆蓋現有譯文，確定要繼續嗎？",
    emptyResponse: "AI 回傳內容為空，請重試或更換模型。",
    translated: "AI 譯文已寫入現有的歌詞翻譯欄位。",
    cancelled: "AI 翻譯已取消。"
  },
  en: {
    settings: "Settings",
    settingsTitle: "Application Settings",
    settingsDescription: "Manage the interface language and AI lyric translation connection.",
    languageSection: "Interface Language",
    aiSection: "AI Lyric Translation",
    baseUrl: "Base URL",
    baseUrlTip: "Enter the OpenAI-compatible API root supplied by your provider. /chat/completions is appended automatically unless already present.",
    apiKey: "API Key",
    apiKeyPlaceholder: "Enter API Key",
    apiKeyConfigured: "Configured; leave blank to keep it, or enter a new value to replace it",
    apiKeyTip: "Use the access key created by your AI provider. It does not need an sk- prefix. The packaged desktop app encrypts and persistently stores it in the system secure store, so it remains available after restart. Only the 127.0.0.1 development preview keeps it for the current session because no system key vault is available there. The full key is never displayed.",
    clearApiKey: "Clear API Key",
    clearingApiKey: "Clearing...",
    clearApiKeyConfirm: "Clear the stored API Key? All other AI settings will be kept.",
    apiKeyCleared: "API Key cleared",
    apiKeyClearFailed: "Unable to clear the API Key.",
    model: "Model",
    modelPlaceholder: "Enter the provider model identifier",
    modelTip: "Enter the exact model identifier from your provider documentation. This is not a display name and the app does not guess or recommend one.",
    temperature: "Temperature",
    temperatureTip: "Controls randomness from 0–2; the default is 0.7. Lower values are more stable. Some providers ignore this in reasoning mode.",
    defaultStyle: "Default Translation Style",
    defaultStyleTip: "Sets the single style preselected when the inline translation panel opens. You can still change it before each request.",
    defaultReasoning: "Enable Reasoning by Default",
    reasoningHint: "Requests reasoning mode and displays reasoning_content as it streams. Providers that do not support it may return no reasoning process.",
    save: "Save Settings",
    saving: "Saving...",
    changesPending: "Waiting to save",
    loadFailed: "Load failed",
    saveFailed: "Save failed",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    stopAndBack: "Stop translation and go back",
    settingsSaved: "Settings saved",
    settingsLoadFailed: "Unable to load AI settings.",
    settingsSaveFailed: "Unable to save AI settings.",
    aiTranslate: "AI Translate",
    aiTranslateTitle: "AI Lyric Translation",
    aiTranslateDescription: "Choose one style to generate one English translation.",
    reasoning: "Use Reasoning",
    reasoningDescription: "The model reasons first, then streams only the final translation into the lyric field.",
    phaseConnecting: "Connecting to the AI endpoint",
    phaseConnected: "Connected; waiting for the first model data chunk",
    phaseReasoning: "The model is reasoning",
    phaseTranslating: "The model is generating the translation",
    connectingTip: "If this takes too long, check the Base URL, API key, model identifier, and network connection.",
    connectedTip: "The request was accepted. Wait time depends on provider load, lyric length, and reasoning mode.",
    reasoningStream: "Live Reasoning",
    live: "Live",
    reasoningWaiting: "Waiting for reasoning_content from the model…",
    translationWaiting: "The translation will stream here after reasoning finishes.",
    translate: "Translate",
    translating: "Translating...",
    stop: "Stop",
    streamPreview: "Streaming Translation",
    lyricsEmpty: "Lyrics are empty. Enter lyrics first.",
    configureFirst: "AI settings are incomplete. Configure an API key and model first.",
    overwriteConfirm: "The translation field already contains text. Continue and overwrite it?",
    emptyResponse: "The AI returned an empty response. Retry or choose another model.",
    translated: "AI translation was written to the existing translation field.",
    cancelled: "AI translation cancelled."
  },
  fr: {
    settings: "Paramètres",
    settingsTitle: "Paramètres de l’application",
    settingsDescription: "Gérez la langue de l’interface et la connexion de traduction des paroles par IA.",
    languageSection: "Langue de l’interface",
    aiSection: "Traduction des paroles par IA",
    baseUrl: "URL de base",
    baseUrlTip: "Saisissez l’URL racine de l’API compatible OpenAI fournie par votre prestataire. /chat/completions est ajouté automatiquement s’il n’est pas déjà présent.",
    apiKey: "Clé API",
    apiKeyPlaceholder: "Saisissez la clé API",
    apiKeyConfigured: "Configurée ; laissez ce champ vide pour la conserver ou saisissez une nouvelle valeur pour la remplacer",
    apiKeyTip: "Utilisez la clé d’accès créée par votre prestataire d’IA. Elle ne doit pas nécessairement commencer par sk-. L’application de bureau distribuée la chiffre et la conserve durablement dans le stockage sécurisé du système : aucune nouvelle saisie n’est nécessaire après redémarrage. Seul l’aperçu de développement sur 127.0.0.1 la limite à la session actuelle, faute de coffre-fort système. La clé complète n’est jamais affichée.",
    clearApiKey: "Effacer la clé API",
    clearingApiKey: "Suppression...",
    clearApiKeyConfirm: "Effacer la clé API enregistrée ? Tous les autres paramètres d’IA seront conservés.",
    apiKeyCleared: "Clé API effacée",
    apiKeyClearFailed: "Impossible d’effacer la clé API.",
    model: "Modèle",
    modelPlaceholder: "Saisissez l’identifiant du modèle fourni",
    modelTip: "Saisissez exactement l’identifiant indiqué dans la documentation du prestataire. Ce n’est pas un nom d’affichage et l’application ne le devine ni ne le recommande.",
    temperature: "Température",
    temperatureTip: "Contrôle le degré d’aléatoire entre 0 et 2 ; la valeur par défaut est 0,7. Une valeur basse est plus stable. Certains prestataires ignorent ce réglage en mode Reasoning.",
    defaultStyle: "Style de traduction par défaut",
    defaultStyleTip: "Définit l’unique style présélectionné à l’ouverture du panneau de traduction. Vous pouvez encore le modifier avant chaque requête.",
    defaultReasoning: "Activer Reasoning par défaut",
    reasoningHint: "Demande le mode de raisonnement et affiche reasoning_content au fil de sa réception. Si le prestataire ne le prend pas en charge, aucun raisonnement ne sera affiché.",
    save: "Enregistrer les paramètres",
    saving: "Enregistrement...",
    changesPending: "En attente d’enregistrement",
    loadFailed: "Échec du chargement",
    saveFailed: "Échec de l’enregistrement",
    cancel: "Annuler",
    close: "Fermer",
    back: "Retour",
    stopAndBack: "Arrêter la traduction et revenir",
    settingsSaved: "Paramètres enregistrés",
    settingsLoadFailed: "Impossible de charger les paramètres de l’IA.",
    settingsSaveFailed: "Impossible d’enregistrer les paramètres de l’IA.",
    aiTranslate: "Traduire par IA",
    aiTranslateTitle: "Traduction des paroles par IA",
    aiTranslateDescription: "Choisissez un style pour générer une seule traduction française.",
    reasoning: "Utiliser Reasoning",
    reasoningDescription: "Le modèle raisonne d’abord, puis diffuse la traduction finale dans le champ prévu, sans y copier le raisonnement.",
    phaseConnecting: "Connexion au service d’IA",
    phaseConnected: "Connexion établie ; attente du premier bloc de données du modèle",
    phaseReasoning: "Le modèle raisonne",
    phaseTranslating: "Le modèle génère la traduction",
    connectingTip: "Si l’attente se prolonge, vérifiez l’URL de base, la clé API, l’identifiant du modèle et la connexion réseau.",
    connectedTip: "La requête a été acceptée. L’attente dépend de la charge du prestataire, de la longueur des paroles et du mode Reasoning.",
    reasoningStream: "Raisonnement en direct",
    live: "En direct",
    reasoningWaiting: "En attente du reasoning_content renvoyé par le modèle…",
    translationWaiting: "La traduction apparaîtra ici progressivement une fois le raisonnement terminé.",
    translate: "Traduire",
    translating: "Traduction...",
    stop: "Arrêter",
    streamPreview: "Traduction en direct",
    lyricsEmpty: "Les paroles sont vides. Saisissez d’abord des paroles.",
    configureFirst: "Les paramètres de l’IA sont incomplets. Configurez d’abord une clé API et un modèle.",
    overwriteConfirm: "Le champ de traduction contient déjà du texte. Voulez-vous continuer et le remplacer ?",
    emptyResponse: "L’IA a renvoyé une réponse vide. Réessayez ou choisissez un autre modèle.",
    translated: "La traduction de l’IA a été insérée dans le champ de traduction existant.",
    cancelled: "Traduction par IA annulée."
  },
  ja: {
    settings: "設定",
    settingsTitle: "アプリケーション設定",
    settingsDescription: "インターフェース言語と AI 歌詞翻訳の接続を管理します。",
    languageSection: "インターフェース言語",
    aiSection: "AI 歌詞翻訳",
    baseUrl: "ベース URL",
    baseUrlTip: "プロバイダーが提供する OpenAI 互換 API のルート URL を入力してください。末尾に /chat/completions がない場合は自動的に追加されます。",
    apiKey: "API キー",
    apiKeyPlaceholder: "API キーを入力",
    apiKeyConfigured: "設定済みです。空欄のままなら現在のキーを使用し、新しい値を入力すると置き換えます",
    apiKeyTip: "AI プロバイダーが発行したアクセスキーを入力してください。sk- で始まる必要はありません。配布版デスクトップアプリはシステムの安全なストレージで暗号化して永続保存するため、再起動後も再入力は不要です。システムのキーボルトを利用できない 127.0.0.1 の開発プレビューだけは現在のセッションに限って保持します。完全なキーは表示されません。",
    clearApiKey: "API キーを消去",
    clearingApiKey: "消去中...",
    clearApiKeyConfirm: "保存済みの API キーを消去しますか？その他の AI 設定は保持されます。",
    apiKeyCleared: "API キーを消去しました",
    apiKeyClearFailed: "API キーを消去できませんでした。",
    model: "モデル",
    modelPlaceholder: "プロバイダーのモデル識別子を入力",
    modelTip: "プロバイダーのドキュメントに記載された正確なモデル識別子を入力してください。表示名ではなく、アプリが推測または推奨することもありません。",
    temperature: "Temperature",
    temperatureTip: "出力のランダム性を 0〜2 の範囲で調整します。初期値は 0.7 で、低いほど安定します。Reasoning モードでは無視される場合があります。",
    defaultStyle: "既定の翻訳スタイル",
    defaultStyleTip: "翻訳パネルを開いたときにあらかじめ選択する一つのスタイルです。リクエストごとに変更できます。",
    defaultReasoning: "Reasoning を既定で有効にする",
    reasoningHint: "推論モードを要求し、受信した reasoning_content をリアルタイムで表示します。プロバイダーが未対応の場合、推論過程は表示されません。",
    save: "設定を保存",
    saving: "保存中...",
    changesPending: "保存待ち",
    loadFailed: "読み込みに失敗しました",
    saveFailed: "保存に失敗しました",
    cancel: "キャンセル",
    close: "閉じる",
    back: "戻る",
    stopAndBack: "翻訳を停止して戻る",
    settingsSaved: "設定を保存しました",
    settingsLoadFailed: "AI 設定を読み込めませんでした。",
    settingsSaveFailed: "AI 設定を保存できませんでした。",
    aiTranslate: "AI 翻訳",
    aiTranslateTitle: "AI 歌詞翻訳",
    aiTranslateDescription: "スタイルを一つ選び、日本語の訳詞を一版だけ生成します。",
    reasoning: "Reasoning を使用",
    reasoningDescription: "モデルが先に推論し、その後に最終訳だけを歌詞欄へストリーミングします。推論内容は書き込みません。",
    phaseConnecting: "AI エンドポイントに接続中",
    phaseConnected: "接続済み。モデルからの最初のデータを待っています",
    phaseReasoning: "モデルが推論中です",
    phaseTranslating: "モデルが訳詞を生成中です",
    connectingTip: "時間がかかる場合は、ベース URL、API キー、モデル識別子、ネットワーク接続を確認してください。",
    connectedTip: "リクエストは受け付けられました。待ち時間はプロバイダーの負荷、歌詞の長さ、Reasoning の有無で変わります。",
    reasoningStream: "リアルタイム推論",
    live: "リアルタイム",
    reasoningWaiting: "モデルから reasoning_content が返されるのを待っています…",
    translationWaiting: "推論が終わると、訳詞がここに順次表示されます。",
    translate: "翻訳を開始",
    translating: "翻訳中...",
    stop: "停止",
    streamPreview: "ストリーミング訳詞",
    lyricsEmpty: "歌詞が空です。先に歌詞を入力してください。",
    configureFirst: "AI 設定が不足しています。先に API キーとモデルを設定してください。",
    overwriteConfirm: "翻訳欄にはすでに内容があります。既存の訳詞を上書きして続行しますか？",
    emptyResponse: "AI から空の応答が返されました。再試行するか、別のモデルを選択してください。",
    translated: "AI の訳詞を既存の翻訳欄に入力しました。",
    cancelled: "AI 翻訳をキャンセルしました。"
  },
  es: {
    settings: "Configuración",
    settingsTitle: "Configuración de la aplicación",
    settingsDescription: "Gestiona el idioma de la interfaz y la conexión para traducir letras con IA.",
    languageSection: "Idioma de la interfaz",
    aiSection: "Traducción de letras con IA",
    baseUrl: "URL base",
    baseUrlTip: "Introduce la URL raíz de la API compatible con OpenAI que proporciona tu proveedor. /chat/completions se añade automáticamente si aún no está incluido.",
    apiKey: "Clave API",
    apiKeyPlaceholder: "Introduce la clave API",
    apiKeyConfigured: "Configurada; deja el campo vacío para conservarla o introduce un valor nuevo para sustituirla",
    apiKeyTip: "Usa la clave de acceso creada por tu proveedor de IA. No es necesario que empiece por sk-. La aplicación de escritorio distribuida la cifra y guarda de forma persistente en el almacenamiento seguro del sistema, por lo que no hace falta volver a introducirla después de reiniciar. Solo la vista previa de desarrollo en 127.0.0.1 la limita a la sesión actual porque no dispone del almacén de claves del sistema. La clave completa nunca se muestra.",
    clearApiKey: "Borrar clave API",
    clearingApiKey: "Borrando...",
    clearApiKeyConfirm: "¿Quieres borrar la clave API guardada? Se conservarán los demás ajustes de IA.",
    apiKeyCleared: "Clave API borrada",
    apiKeyClearFailed: "No se pudo borrar la clave API.",
    model: "Modelo",
    modelPlaceholder: "Introduce el identificador del modelo",
    modelTip: "Introduce exactamente el identificador indicado en la documentación del proveedor. No es un nombre visible y la aplicación no lo adivina ni recomienda.",
    temperature: "Temperatura",
    temperatureTip: "Controla la aleatoriedad entre 0 y 2; el valor predeterminado es 0,7. Los valores bajos son más estables. Algunos proveedores ignoran esta opción en modo Reasoning.",
    defaultStyle: "Estilo de traducción predeterminado",
    defaultStyleTip: "Define el único estilo preseleccionado al abrir el panel de traducción. Puedes cambiarlo antes de cada solicitud.",
    defaultReasoning: "Activar Reasoning de forma predeterminada",
    reasoningHint: "Solicita el modo de razonamiento y muestra reasoning_content a medida que llega. Si el proveedor no lo admite, puede que no aparezca ningún proceso de razonamiento.",
    save: "Guardar configuración",
    saving: "Guardando...",
    changesPending: "Pendiente de guardar",
    loadFailed: "Error al cargar",
    saveFailed: "Error al guardar",
    cancel: "Cancelar",
    close: "Cerrar",
    back: "Volver",
    stopAndBack: "Detener la traducción y volver",
    settingsSaved: "Configuración guardada",
    settingsLoadFailed: "No se pudo cargar la configuración de IA.",
    settingsSaveFailed: "No se pudo guardar la configuración de IA.",
    aiTranslate: "Traducir con IA",
    aiTranslateTitle: "Traducción de letras con IA",
    aiTranslateDescription: "Elige un estilo para generar una única traducción al español.",
    reasoning: "Usar Reasoning",
    reasoningDescription: "El modelo razona primero y después transmite solo la traducción final al campo de letras; el razonamiento no se copiará.",
    phaseConnecting: "Conectando con el servicio de IA",
    phaseConnected: "Conexión establecida; esperando el primer bloque de datos del modelo",
    phaseReasoning: "El modelo está razonando",
    phaseTranslating: "El modelo está generando la traducción",
    connectingTip: "Si tarda demasiado, comprueba la URL base, la clave API, el identificador del modelo y la conexión de red.",
    connectedTip: "La solicitud ha sido aceptada. La espera depende de la carga del proveedor, la longitud de la letra y el modo Reasoning.",
    reasoningStream: "Razonamiento en directo",
    live: "En directo",
    reasoningWaiting: "Esperando reasoning_content del modelo…",
    translationWaiting: "La traducción aparecerá aquí progresivamente cuando termine el razonamiento.",
    translate: "Traducir",
    translating: "Traduciendo...",
    stop: "Detener",
    streamPreview: "Traducción en directo",
    lyricsEmpty: "La letra está vacía. Introduce primero la letra.",
    configureFirst: "La configuración de IA está incompleta. Configura primero una clave API y un modelo.",
    overwriteConfirm: "El campo de traducción ya contiene texto. ¿Quieres continuar y sobrescribirlo?",
    emptyResponse: "La IA devolvió una respuesta vacía. Vuelve a intentarlo o elige otro modelo.",
    translated: "La traducción de IA se ha escrito en el campo de traducción existente.",
    cancelled: "Traducción con IA cancelada."
  }
};

export function getAIUiCopy(locale: Locale): AIUiCopy {
  return AI_UI_COPY[locale];
}
