// Generated by scripts/generate-shared-contracts.mjs; edit card-style-schema.json.
export type CardStyleInputs = {
  backgroundMode: "palette" | "gradient" | "solid";
  solidColor?: string;
  solidColorSource?: "auto" | "user";
  layoutMode: "portrait" | "landscape";
  ratio: "1:1" | "4:5" | "9:16" | "16:9" | "21:9" | "3:2" | "custom";
  width: number;
  height: number;
  autoWidth: boolean;
  autoHeight: boolean;
  font: "sans-heavy" | "serif-heavy" | "system-sans" | "system-serif";
  fontScheme?: FontSchemeInputs;
  customFontEnabled?: boolean;
  customFontFamily?: string;
  customFontLabel?: string;
  customFontWeight?: number;
  customFontStyle?: "normal" | "italic";
  lyricFontSize: number;
  lineHeight: number;
  align: "left" | "center";
  textColorMode: "auto" | "preset" | "custom";
  textColorPreset: "white" | "black" | "warmWhite" | "cream" | "charcoal" | "softBlue" | "softGold";
  customTextColor: string;
  resolvedTextColor: string;
  translationScale: number;
  allowMultiLineTitle: boolean;
  contentMode: "lyrics" | "instrumental";
  instrumentalText: string;
  showCover: boolean;
  showSongInfo: boolean;
  showAlbumName: boolean;
  showGeneratedWatermark: boolean;
  showSharedBy: boolean;
  sharedByText: string;
  showWatermark: boolean;
  showFineGrid: boolean;
  fineGridDensity: "sparse" | "medium" | "dense";
  separatorStyle?: "dot" | "line";
  coverCropScale: number;
  watermark: string;
  landscapeLayout?: LandscapeLayoutInputs;
};

export type FontSchemeInputs = {
  mode: "preset" | "custom";
  presetId?: "source-han-sans" | "source-han-serif" | "mona-sans";
  cjkFontFamily: string;
  latinFontFamily: string;
};

export type LandscapeLayoutInputs = {
  autoLyricsWidth: boolean;
  lyricsWidth: number;
  autoHeight: boolean;
  requestedHeight: number;
};
