import assert from "node:assert/strict";
import { defaultState } from "../components/editor/editor-defaults";
import { BACKGROUND_GRID_SIZE_BY_DENSITY, resolveBackgroundGridDensity } from "../lib/background-grid";
import { normalizeInstrumentalLayout } from "../lib/card-style-normalize";
import type { CardStyle } from "../lib/types";

const baseStyle: CardStyle = {
  backgroundMode: "palette",
  layoutMode: "portrait",
  ratio: "custom",
  width: 1040,
  height: 1400,
  autoHeight: true,
  font: "sans-heavy",
  customFontEnabled: false,
  customFontFamily: "",
  lyricFontSize: 60,
  lineHeight: 1.4,
  align: "center",
  textColorMode: "auto",
  textColorPreset: "white",
  customTextColor: "#FFFFFF",
  resolvedTextColor: "#FFFFFF",
  translationEnabled: true,
  translationText: "translation",
  translationScale: 0.75,
  allowTwoLineTitle: false,
  contentMode: "lyrics",
  instrumentalText: "Instrumental Track",
  showCover: true,
  showSongInfo: true,
  showAlbumName: true,
  showGeneratedWatermark: true,
  showSharedBy: true,
  sharedByText: "Shared by Test",
  showWatermark: true,
  showPlatformBadge: true,
  showFineGrid: false,
  fineGridDensity: "medium",
  coverCropScale: 1,
  watermark: "generated by lyric card generator"
};

const normalizedInstrumental = normalizeInstrumentalLayout({
  ...baseStyle,
  contentMode: "instrumental",
  layoutMode: "landscape",
  ratio: "16:9",
  width: 1920,
  height: 1080,
  autoHeight: true
});

assert.equal(normalizedInstrumental.contentMode, "instrumental");
assert.equal(normalizedInstrumental.layoutMode, "portrait");
assert.equal(normalizedInstrumental.ratio, "1:1");
assert.equal(normalizedInstrumental.width, 1080);
assert.equal(normalizedInstrumental.height, 1080);
assert.equal(normalizedInstrumental.autoHeight, false);
assert.equal(normalizedInstrumental.translationEnabled, false);
assert.equal(normalizedInstrumental.translationText, "");

const lyricsLandscape = normalizeInstrumentalLayout({
  ...baseStyle,
  contentMode: "lyrics",
  layoutMode: "landscape",
  ratio: "16:9",
  width: 1920,
  height: 1080,
  autoHeight: false
});

assert.equal(lyricsLandscape.layoutMode, "landscape");
assert.equal(lyricsLandscape.ratio, "16:9");
assert.equal(lyricsLandscape.width, 1920);
assert.equal(lyricsLandscape.height, 1080);

assert.equal(defaultState.style.showFineGrid, false);
assert.equal(defaultState.style.fineGridDensity, "medium");
assert.equal(defaultState.style.showAlbumName, true);
assert.equal(defaultState.style.layoutMode, "portrait");
assert.equal(defaultState.style.ratio, "custom");
assert.equal(defaultState.style.autoHeight, true);

assert.deepEqual(BACKGROUND_GRID_SIZE_BY_DENSITY, {
  sparse: 72,
  medium: 56,
  dense: 40
});
assert.equal(resolveBackgroundGridDensity(undefined), "medium");
assert.equal(resolveBackgroundGridDensity("sparse"), "sparse");

console.log(JSON.stringify({ ok: true, v34LayoutGridTests: 20 }, null, 2));
