import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { defaultState } from "../components/editor/editor-defaults";
import { BACKGROUND_GRID_SIZE_BY_DENSITY, resolveBackgroundGridDensity } from "../lib/background-grid";
import { AUTO_HEIGHT_MIN, getCardSize, PRESET_CARD_SIZES } from "../lib/card-size";
import {
  FIXED_COVER_CROP_SCALE,
  FIXED_WHITE_TEXT_COLOR,
  normalizeCardStyle,
  normalizeInstrumentalLayout
} from "../lib/card-style-normalize";
import { applyEditorStyleChange } from "../lib/editor/apply-style-change";
import { createExportSnapshot } from "../lib/export-snapshot";
import { messages } from "../lib/i18n";
import { hasCurrentLandscapePlan } from "../lib/landscape-measurement-key";
import {
  DEFAULT_LYRIC_LINE_HEIGHT,
  LYRIC_LINE_HEIGHT_MAX,
  LYRIC_LINE_HEIGHT_MIN,
  LYRIC_LINE_HEIGHT_STEP
} from "../lib/lyric-typography";
import type { AppState, CardStyle, Locale } from "../lib/types";

const baseStyle: CardStyle = {
  backgroundMode: "palette",
  layoutMode: "portrait",
  ratio: "custom",
  width: 1040,
  height: 1400,
  autoWidth: false,
  autoHeight: true,
  font: "sans-heavy",
  customFontEnabled: false,
  customFontFamily: "",
  lyricFontSize: 60,
  lineHeight: 1.8,
  align: "center",
  textColorMode: "auto",
  textColorPreset: "white",
  customTextColor: "#FFFFFF",
  resolvedTextColor: "#FFFFFF",
  translationEnabled: true,
  translationText: "translation",
  translationScale: 0.75,
  allowMultiLineTitle: false,
  contentMode: "lyrics",
  instrumentalText: "Instrumental Track",
  showCover: true,
  showSongInfo: true,
  showAlbumName: true,
  showGeneratedWatermark: true,
  showSharedBy: true,
  sharedByText: "Shared by Test",
  showWatermark: true,
  showPlatformBadge: true,
  showFineGrid: false,
  fineGridDensity: "medium",
  coverCropScale: 1,
  watermark: "generated by lyric card generator"
};

// Instrumental normalization is intentionally destructive: it collapses
// incompatible lyric and landscape settings into the fixed square contract.
const normalizedInstrumental = normalizeInstrumentalLayout({
  ...baseStyle,
  contentMode: "instrumental",
  layoutMode: "landscape",
  ratio: "16:9",
  width: 1920,
  height: 1080,
  autoHeight: true
});

assert.equal(normalizedInstrumental.contentMode, "instrumental");
assert.equal(normalizedInstrumental.layoutMode, "portrait");
assert.equal(normalizedInstrumental.ratio, "1:1");
assert.equal(normalizedInstrumental.width, 1080);
assert.equal(normalizedInstrumental.height, 1080);
assert.equal(normalizedInstrumental.autoHeight, false);
assert.equal(normalizedInstrumental.translationEnabled, false);
assert.equal(normalizedInstrumental.translationText, "");

const lyricsLandscape = normalizeInstrumentalLayout({
  ...baseStyle,
  contentMode: "lyrics",
  layoutMode: "landscape",
  ratio: "16:9",
  width: 1920,
  height: 1080,
  autoHeight: false
});

assert.equal(lyricsLandscape.layoutMode, "landscape");
assert.equal(lyricsLandscape.ratio, "16:9");
assert.equal(lyricsLandscape.width, 1920);
assert.equal(lyricsLandscape.height, 1080);

assert.equal(defaultState.style.showFineGrid, false);
assert.equal(defaultState.style.fineGridDensity, "medium");
assert.equal(defaultState.style.showAlbumName, true);
assert.equal(defaultState.style.layoutMode, "portrait");
assert.equal(defaultState.style.ratio, "custom");
assert.equal(defaultState.style.autoWidth, true, "new portrait custom cards enable automatic width");
assert.equal(defaultState.style.autoHeight, true);
assert.equal(defaultState.style.landscapeLayout?.autoLyricsWidth, true);
assert.equal(defaultState.style.landscapeLayout?.autoHeight, true);
assert.equal(defaultState.lastPortraitSize?.autoWidth, true, "new portrait history keeps automatic width enabled");
assert.equal(defaultState.lastPortraitCustomSize?.autoWidth, true, "new custom history keeps automatic width enabled");
assert.equal(defaultState.style.textColorMode, "preset");
assert.equal(defaultState.style.textColorPreset, "white");
assert.equal(defaultState.style.resolvedTextColor, FIXED_WHITE_TEXT_COLOR);
assert.equal(defaultState.style.coverCropScale, FIXED_COVER_CROP_SCALE);

const portraitStart: AppState = {
  ...defaultState,
  style: {
    ...defaultState.style,
    layoutMode: "portrait",
    ratio: "custom",
    width: 1040,
    height: 1080,
    autoHeight: true
  },
  lastPortraitSize: {
    ratio: "custom",
    width: 1040,
    height: 1080,
    autoHeight: true
  },
  lastLandscapeSize: undefined
};
const landscapeDefault = applyEditorStyleChange(portraitStart, {
  ...portraitStart.style,
  layoutMode: "landscape"
});
assert.deepEqual(
  {
    layoutMode: landscapeDefault.style.layoutMode,
    ratio: landscapeDefault.style.ratio,
    width: landscapeDefault.style.width,
    height: landscapeDefault.style.height,
    autoHeight: landscapeDefault.style.autoHeight
  },
  {
    layoutMode: "landscape",
    ratio: "custom",
    width: PRESET_CARD_SIZES["16:9"].width,
    height: PRESET_CARD_SIZES["16:9"].height,
    autoHeight: true
  }
);

const portraitRestored = applyEditorStyleChange(landscapeDefault, {
  ...landscapeDefault.style,
  layoutMode: "portrait"
});
assert.deepEqual(
  {
    layoutMode: portraitRestored.style.layoutMode,
    ratio: portraitRestored.style.ratio,
    width: portraitRestored.style.width,
    height: portraitRestored.style.height,
    autoHeight: portraitRestored.style.autoHeight
  },
  {
    layoutMode: "portrait",
    ratio: "custom",
    width: 1040,
    height: 1080,
    autoHeight: true
  }
);
assert.deepEqual(getCardSize(portraitRestored.style), { width: 1040, height: 1080 });
assert.notDeepEqual(getCardSize(portraitRestored.style), PRESET_CARD_SIZES["4:5"]);

const landscapeRestored = applyEditorStyleChange(portraitRestored, {
  ...portraitRestored.style,
  layoutMode: "landscape"
});
assert.equal(landscapeRestored.style.ratio, "custom");
assert.deepEqual(getCardSize(landscapeRestored.style), PRESET_CARD_SIZES["16:9"]);

const landscapeWide = applyEditorStyleChange(landscapeRestored, {
  ...landscapeRestored.style,
  ratio: "21:9",
  width: PRESET_CARD_SIZES["21:9"].width,
  height: PRESET_CARD_SIZES["21:9"].height,
  autoHeight: false
});
const portraitAfterWide = applyEditorStyleChange(landscapeWide, {
  ...landscapeWide.style,
  layoutMode: "portrait"
});
const landscapeWideRestored = applyEditorStyleChange(portraitAfterWide, {
  ...portraitAfterWide.style,
  layoutMode: "landscape"
});
assert.equal(landscapeWideRestored.style.layoutMode, "landscape");
assert.equal(landscapeWideRestored.style.ratio, "custom", "obsolete landscape presets normalize to free layout");
assert.equal(landscapeWideRestored.style.landscapeLayout?.autoLyricsWidth, true);

const portraitWithoutHistory = applyEditorStyleChange(
  { ...landscapeWide, lastPortraitSize: undefined },
  { ...landscapeWide.style, layoutMode: "portrait" }
);
assert.equal(portraitWithoutHistory.style.autoWidth, true, "missing portrait history uses the new automatic-width default");
assert.deepEqual(
  {
    layoutMode: portraitWithoutHistory.style.layoutMode,
    ratio: portraitWithoutHistory.style.ratio,
    width: portraitWithoutHistory.style.width,
    height: portraitWithoutHistory.style.height,
    autoHeight: portraitWithoutHistory.style.autoHeight
  },
  {
    layoutMode: "portrait",
    ratio: "custom",
    width: 1040,
    height: 1080,
    autoHeight: true
  }
);

const legacyPortraitWithoutAutoWidth = applyEditorStyleChange(
  {
    ...landscapeWide,
    lastPortraitSize: {
      ratio: "custom",
      width: 980,
      height: 1200,
      autoHeight: true
    }
  },
  { ...landscapeWide.style, layoutMode: "portrait" }
);
assert.equal(
  legacyPortraitWithoutAutoWidth.style.autoWidth,
  false,
  "legacy portrait history without the field remains manual"
);

const invalidPortraitRatioSize = getCardSize({
  ...portraitRestored.style,
  ratio: "16:9",
  width: 1000,
  height: 1200
});
assert.deepEqual(invalidPortraitRatioSize, { width: 1000, height: 1200 });
assert.notDeepEqual(invalidPortraitRatioSize, PRESET_CARD_SIZES["4:5"]);

const legacyInvalidPortraitState: AppState = {
  ...portraitRestored,
  style: {
    ...portraitRestored.style,
    ratio: "16:9",
    width: PRESET_CARD_SIZES["16:9"].width,
    height: PRESET_CARD_SIZES["16:9"].height,
    autoHeight: false
  }
};
const canonicalPortraitState = applyEditorStyleChange(legacyInvalidPortraitState, {
  ...legacyInvalidPortraitState.style,
  lyricFontSize: legacyInvalidPortraitState.style.lyricFontSize + 1
});
assert.deepEqual(
  {
    layoutMode: canonicalPortraitState.style.layoutMode,
    ratio: canonicalPortraitState.style.ratio,
    width: canonicalPortraitState.style.width,
    height: canonicalPortraitState.style.height,
    autoHeight: canonicalPortraitState.style.autoHeight
  },
  {
    layoutMode: "portrait",
    ratio: "custom",
    width: 1040,
    height: 1080,
    autoHeight: true
  }
);
assert.deepEqual(getCardSize(canonicalPortraitState.style), { width: 1040, height: 1080 });
assert.notDeepEqual(getCardSize(canonicalPortraitState.style), PRESET_CARD_SIZES["4:5"]);
assert.equal(
  getCardSize({ ...baseStyle, height: 200, autoHeight: true }).height,
  AUTO_HEIGHT_MIN,
  "automatic height may compact below the manual canvas minimum"
);
assert.equal(
  getCardSize({ ...baseStyle, height: 200, autoHeight: false }).height,
  720,
  "manual canvas height retains its existing minimum"
);

const normalizedLegacyAuto = normalizeCardStyle({
  ...baseStyle,
  textColorMode: "auto",
  textColorPreset: "black",
  resolvedTextColor: "#111111",
  coverCropScale: 1.72
});
assert.equal(normalizedLegacyAuto.textColorMode, "preset");
assert.equal(normalizedLegacyAuto.textColorPreset, "white");
assert.equal(normalizedLegacyAuto.resolvedTextColor, FIXED_WHITE_TEXT_COLOR);
assert.equal(normalizedLegacyAuto.coverCropScale, FIXED_COVER_CROP_SCALE);

const normalizedLegacyPreset = normalizeCardStyle({
  ...baseStyle,
  textColorMode: "preset",
  textColorPreset: "softGold",
  resolvedTextColor: "#E7D7A1"
});
assert.equal(normalizedLegacyPreset.textColorPreset, "white");
assert.equal(normalizedLegacyPreset.resolvedTextColor, FIXED_WHITE_TEXT_COLOR);

const normalizedCustomColor = normalizeCardStyle({
  ...baseStyle,
  textColorMode: "custom",
  customTextColor: "#AABBCC",
  resolvedTextColor: "#000000",
  coverCropScale: 1.5
});
assert.equal(normalizedCustomColor.textColorMode, "custom");
assert.equal(normalizedCustomColor.customTextColor, "#AABBCC");
assert.equal(normalizedCustomColor.resolvedTextColor, "#AABBCC");
assert.equal(normalizedCustomColor.coverCropScale, FIXED_COVER_CROP_SCALE);

const staleLandscapePlan = {
  version: 1 as const,
  measurementKey: "stale-persisted-measurement",
  canvas: { width: 10, height: 10 },
  safeRect: { x: 0, y: 0, width: 10, height: 10 },
  leftColumnRect: { x: 0, y: 0, width: 4, height: 10 },
  coverRect: { x: 0, y: 0, width: 4, height: 4 },
  metadataRect: { x: 0, y: 4, width: 4, height: 2 },
  lyricsRect: { x: 6, y: 0, width: 4, height: 10 },
  lyricsNaturalHeight: 10,
  leftScale: 1,
  flexibleGap: 0,
  score: 0
};
const migratedLegacyLandscape = normalizeCardStyle({
  ...baseStyle,
  layoutMode: "landscape",
  ratio: "21:9",
  showCover: false,
  showSongInfo: false,
  landscapePlan: staleLandscapePlan
});
assert.equal(migratedLegacyLandscape.ratio, "custom", "legacy landscape ratios migrate to free layout");
assert.equal(migratedLegacyLandscape.showCover, true, "landscape cover is mandatory after migration");
assert.equal(migratedLegacyLandscape.showSongInfo, true, "song information is mandatory after migration");
assert.equal(migratedLegacyLandscape.landscapePlan, undefined, "persisted derived plans are discarded");
assert.equal(
  normalizeCardStyle({ ...baseStyle, showSongInfo: false }).showSongInfo,
  true,
  "portrait legacy state also migrates hidden song information to visible"
);
assert.equal(
  normalizeCardStyle({ ...baseStyle, showCover: false }).showCover,
  false,
  "portrait retains its independent cover visibility setting"
);
assert.equal(
  normalizeCardStyle(
    { ...baseStyle, layoutMode: "landscape", landscapePlan: staleLandscapePlan },
    { preserveDerivedLandscapePlan: true }
  ).landscapePlan?.measurementKey,
  staleLandscapePlan.measurementKey,
  "only the live render path may explicitly retain a derived plan"
);
const rawStalePlanState: AppState = {
  ...defaultState,
  style: {
    ...defaultState.style,
    layoutMode: "landscape",
    ratio: "custom",
    landscapePlan: staleLandscapePlan
  }
};
assert.equal(hasCurrentLandscapePlan(rawStalePlanState), false, "stale plans never reach preview/export render state");
assert.throws(
  () => createExportSnapshot(rawStalePlanState, 2, 1),
  /measurement is stale/,
  "immutable export snapshots reject a plan from different content"
);

assert.equal(defaultState.style.lineHeight, DEFAULT_LYRIC_LINE_HEIGHT, "new documents use the 1.8 line-height default");
assert.equal(defaultState.style.allowMultiLineTitle, false, "new documents keep title wrapping opt-in");
assert.equal(LYRIC_LINE_HEIGHT_MIN, 1.5);
assert.equal(LYRIC_LINE_HEIGHT_MAX, 2.1);
assert.equal(LYRIC_LINE_HEIGHT_STEP, 0.05);
assert.equal(
  normalizeCardStyle({ ...baseStyle, lineHeight: 1.1 }).lineHeight,
  LYRIC_LINE_HEIGHT_MIN,
  "legacy line heights clamp to the new lower bound"
);
assert.equal(
  normalizeCardStyle({ ...baseStyle, lineHeight: 2.4 }).lineHeight,
  LYRIC_LINE_HEIGHT_MAX,
  "oversized line heights clamp to the new upper bound"
);
assert.equal(
  normalizeCardStyle({ ...baseStyle, lineHeight: 1.83 }).lineHeight,
  1.85,
  "legacy off-step line heights snap to the nearest supported step"
);
assert.equal(
  normalizeCardStyle({ ...baseStyle, lineHeight: Number.NaN }).lineHeight,
  DEFAULT_LYRIC_LINE_HEIGHT,
  "invalid line heights recover to the default"
);

const expectedTextDesignTitles: Record<Locale, string> = {
  zh: "文字设计",
  "zh-TW": "文字設計",
  en: "Text Design",
  fr: "Design du texte",
  ja: "文字デザイン",
  es: "Diseño del texto"
};
for (const [locale, title] of Object.entries(expectedTextDesignTitles) as Array<[Locale, string]>) {
  assert.equal(messages[locale]["step.fontScheme"], title, `${locale} text-design step title`);
  assert.ok(messages[locale].fontSchemeDescription.trim(), `${locale} text-design description`);
  assert.ok(messages[locale].pureWhite.trim(), `${locale} white color label`);
}

// Source checks pin the UI wiring that pure normalization tests cannot observe.
const stylePanelSource = readFileSync(resolve("components/editor/StylePanel.tsx"), "utf8");
const colorControlsSource = readFileSync(resolve("components/editor/style-panel/ColorControls.tsx"), "utf8");
const previewPaneSource = readFileSync(resolve("components/editor/PreviewPane.tsx"), "utf8");
const lyricCardPreviewSource = readFileSync(resolve("components/preview/LyricCardPreview.tsx"), "utf8");
const lyricCardSource = readFileSync(resolve("components/preview/LyricCard.tsx"), "utf8");
const autoHeightSource = readFileSync(resolve("components/editor/hooks/useMeasuredAutoCanvasHeight.ts"), "utf8");
const exportCoordinatorSource = readFileSync(resolve("components/editor/hooks/export-card-dom-coordinator.ts"), "utf8");
const landscapeCardSource = readFileSync(resolve("components/preview/LandscapeLyricCard.tsx"), "utf8");
const instrumentalBlockSource = readFileSync(resolve("components/preview/InstrumentalBlock.tsx"), "utf8");
const fontPanelSource = stylePanelSource.slice(
  stylePanelSource.indexOf("export function FontSchemeSettingsPanel"),
  stylePanelSource.indexOf("export function LayoutSettingsPanel")
);
const visualPanelSource = stylePanelSource.slice(stylePanelSource.indexOf("export function VisualSettingsPanel"));
assert.ok(fontPanelSource.includes("<ColorControls"), "text color is part of the text-design step");
assert.ok(!stylePanelSource.includes("CustomFontPanel"), "the retired custom-font panel stays removed");
assert.ok(!visualPanelSource.includes("<ColorControls"), "visual step no longer duplicates text color");
assert.ok(!stylePanelSource.includes('option value="4:5"'), "portrait presets omit 4:5");
assert.ok(!stylePanelSource.includes('option value="9:16"'), "portrait presets omit 9:16");
assert.ok(!stylePanelSource.includes("const portraitRatio"), "portrait ratio is never masked only at render time");
assert.ok(stylePanelSource.includes("<SegmentedControl<CardAlign>"), "alignment uses the keyboard-accessible segmented slider");
assert.ok(stylePanelSource.includes("<SegmentedControl<CardRatio>"), "size mode uses a segmented slider");
assert.ok(stylePanelSource.includes("<RangeSlider"), "layout range inputs use the shared polished slider");
assert.ok(!stylePanelSource.includes('label={t("coverCrop")}'), "cover crop control is removed");
assert.ok(colorControlsSource.includes('{ value: "white", label: t("pureWhite") }'), "white mode is exposed");
assert.ok(!colorControlsSource.includes("TEXT_COLOR_PRESETS"), "legacy color presets are not exposed");
assert.ok(previewPaneSource.includes("fontSchemePreview ? { ...style, fontScheme: fontSchemePreview } : style"), "font draft previews use the real card");
assert.ok(previewPaneSource.includes("lg:sticky lg:top-0 lg:z-20"), "the right preview pane stays pinned above scrolling controls");
assert.ok(!previewPaneSource.includes("FontSchemePreviewPanel"), "the dedicated font preview card is removed");
assert.ok(lyricCardPreviewSource.includes("self-start"), "live preview panel follows its own content height");
assert.ok(!lyricCardPreviewSource.includes("min-h-[520px]"), "live preview canvas no longer reserves empty vertical space");
assert.ok(!lyricCardPreviewSource.includes("min-h-[calc(100vh-48px)]"), "live preview border no longer stretches to the viewport");
assert.ok(!lyricCardSource.includes("cropScale={style.coverCropScale}"), "portrait rendering fixes crop scale");
assert.ok(!landscapeCardSource.includes("cropScale={style.coverCropScale}"), "landscape rendering fixes crop scale");
assert.ok(instrumentalBlockSource.includes("data-instrumental-song-info"), "instrumental metadata has a dedicated spaced layout");
assert.ok(instrumentalBlockSource.includes("song.album?.trim()"), "instrumental album ignores blank metadata");
assert.ok(instrumentalBlockSource.includes("data-instrumental-album"), "instrumental cards render album metadata when enabled");
assert.ok(instrumentalBlockSource.includes("mt-7"), "instrumental title and artist use relaxed spacing");
assert.ok(instrumentalBlockSource.includes('allowMultiLineTitle ? "multi-line-title" : "truncate"'), "instrumental titles honor the multi-line setting");
assert.ok(lyricCardSource.includes("allowMultiLineTitle={style.allowMultiLineTitle}"), "instrumental rendering receives the multi-line title setting");
assert.ok(instrumentalBlockSource.includes("stackedSongInfoHeight"), "instrumental artwork reserves measured multi-line metadata height");
assert.ok(lyricCardSource.includes('pt-8 pb-4'), "lyrics keep a smaller but non-zero bottom breathing room");
assert.ok(
  exportCoordinatorSource.includes("createMutationObserver") &&
    exportCoordinatorSource.includes("characterData: true") &&
    exportCoordinatorSource.includes("childList: true"),
  "arbitrary content mutations trigger coordinated auto-height measurement"
);
assert.ok(autoHeightSource.includes("state.song.title"), "song title changes trigger auto-height measurement");
assert.ok(autoHeightSource.includes("state.translationText"), "translation changes trigger auto-height measurement");
assert.ok(autoHeightSource.includes("Math.max(AUTO_HEIGHT_MIN, nextHeight)"), "auto-height uses the compact lower bound");

assert.deepEqual(BACKGROUND_GRID_SIZE_BY_DENSITY, {
  sparse: 72,
  medium: 56,
  dense: 40
});
assert.equal(resolveBackgroundGridDensity(undefined), "medium");
assert.equal(resolveBackgroundGridDensity("sparse"), "sparse");

console.log(JSON.stringify({ ok: true, v34LayoutGridTests: 80 }, null, 2));
