import { getLandscapeLayout, getPortraitLayout } from "../lib/card-layout-engine";
import { buildUpdateResult } from "../lib/github-update";
import { proxiedImageUrl } from "../lib/image-utils";
import { formatChineseTranslation, splitAlternatingLyrics } from "../lib/lyric-format";
import type { CardStyle } from "../lib/types";
import { compareVersionStrings } from "../lib/version-compare";

const baseStyle: CardStyle = {
  backgroundMode: "palette",
  layoutMode: "portrait",
  ratio: "custom",
  width: 1040,
  height: 1400,
  autoHeight: true,
  font: "sans-heavy",
  customFontEnabled: false,
  customFontFamily: "",
  lyricFontSize: 60,
  lineHeight: 1.4,
  align: "center",
  textColorMode: "auto",
  textColorPreset: "white",
  customTextColor: "#FFFFFF",
  resolvedTextColor: "#FFFFFF",
  translationEnabled: true,
  translationText: "翻译",
  translationScale: 0.75,
  allowTwoLineTitle: false,
  contentMode: "lyrics",
  instrumentalText: "Instrumental Track",
  showCover: true,
  showSongInfo: true,
  showGeneratedWatermark: true,
  showSharedBy: true,
  sharedByText: "Shared by Test",
  showWatermark: true,
  showPlatformBadge: true,
  frameStyleEnabled: false,
  frameVariant: "fullBleed",
  showFrame: false,
  showShadow: false,
  coverCropScale: 1,
  watermark: "generated by lyric card generator"
};

function main() {
  testLyricFormat();
  testVersionCompare();
  testUpdateResult();
  testLayoutEngine();
  testImageProxy();
  console.log(JSON.stringify({ ok: true, tests: 5 }, null, 2));
}

function testLyricFormat() {
  const split = splitAlternatingLyrics(
    [
      "English 1",
      "\u4E2D\u6587 1",
      "\u541B\u306E\u540D\u306F",
      "\uC0AC\uB791\uD574",
      "English 2",
      "\u4E2D\u6587 2"
    ].join("\n")
  );
  assertEqual(split.lyrics, "English 1\n\u541B\u306E\u540D\u306F\n\uC0AC\uB791\uD574\nEnglish 2", "split lyrics");
  assertEqual(split.translationText, "\u4E2D\u6587 1\n\u4E2D\u6587 2", "split translation");
  assertEqual(
    formatChineseTranslation("\u4F60\u6765,\u6211\u8D70\u3002\u518D\u89C1\uFF0C\u4E0D\u9001."),
    "\u4F60\u6765 \u6211\u8D70\n\u518D\u89C1 \u4E0D\u9001\n",
    "format translation"
  );
}

function testVersionCompare() {
  assert(compareVersionStrings("v2.0.0", "1.1.0")! > 0, "v prefix compare");
  assert(compareVersionStrings("2.0.0", "2.0.0-beta.1")! > 0, "release beats prerelease");
  assert(compareVersionStrings("2.0.0-beta.2", "2.0.0-beta.1")! > 0, "prerelease numeric compare");
}

function testUpdateResult() {
  const result = buildUpdateResult(
    {
      tag_name: "v2.0.0",
      html_url: "https://github.com/Qrzzzz/lyrics-card-generator/releases/tag/v2.0.0",
      assets: [
        {
          name: "Lyrics Card Generator Setup 2.0.0.exe",
          browser_download_url: "https://example.com/setup.exe"
        },
        {
          name: "Lyrics Card Generator-2.0.0-portable.exe",
          browser_download_url: "https://example.com/portable.exe"
        }
      ]
    },
    "1.1.0"
  );
  assert(result.status === "update-available", "update available");
  if (result.status === "update-available") {
    assertEqual(result.installerUrl, "https://example.com/setup.exe", "installer URL");
    assertEqual(result.portableUrl, "https://example.com/portable.exe", "portable URL");
  }
}

function testLayoutEngine() {
  const portrait = getPortraitLayout({ width: 1040, height: 1400 }, baseStyle, "apple");
  assert(Math.abs(centerX(portrait.safeRect) - centerX(portrait.lyricsRect)) < 1, "portrait center lyrics");
  assert(portrait.lyricsRect.width <= portrait.safeRect.width, "portrait lyrics inside safe area");

  const landscape = getLandscapeLayout(
    { width: 2520, height: 1080 },
    { ...baseStyle, layoutMode: "landscape", ratio: "21:9", autoHeight: false },
    "apple"
  );
  assert(landscape.coverRect && landscape.coverRect.width <= landscape.safeRect.height * 0.74 + 1, "landscape cover height bound");
  assert(landscape.contentRect.width <= 1180, "landscape content max width");
  assert(landscape.lyricsRect.height > 170, "landscape lyrics has usable height");
}

function testImageProxy() {
  assertEqual(proxiedImageUrl("blob:http://localhost/id"), "blob:http://localhost/id", "blob not proxied");
  assertEqual(proxiedImageUrl("data:image/png;base64,abc"), "data:image/png;base64,abc", "data not proxied");
  assertEqual(proxiedImageUrl("file:///C:/cover.png"), "file:///C:/cover.png", "file not proxied");
  assertEqual(proxiedImageUrl("https://example.com/cover.jpg"), "/api/image-proxy?url=https%3A%2F%2Fexample.com%2Fcover.jpg", "http proxied");
}

function centerX(rect: { x: number; width: number }) {
  return rect.x + rect.width / 2;
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) {
    throw new Error(`Assertion failed: ${message}`);
  }
}

function assertEqual<T>(actual: T, expected: T, message: string) {
  if (actual !== expected) {
    throw new Error(`Assertion failed: ${message}. Expected ${String(expected)}, got ${String(actual)}`);
  }
}

main();
