import { getLandscapeLayout, getPortraitLayout } from "../lib/card-layout-engine";
import { cleanAITranslation } from "../lib/ai/clean";
import { validateConfiguredSettings } from "../lib/ai/client";
import { buildLyricsTranslationPrompt, getDefaultStylePrompt, PROMPT_OUTPUT_RULES } from "../lib/ai/prompt";
import { getTranslationPresets, getTranslationStyles } from "../lib/ai/styles";
import { getLocalePromptOverrides, normalizeAISettings, normalizePromptLibrary, setLocalePromptOverrides } from "../lib/ai/settings-normalize";
import { DEFAULT_AI_SETTINGS } from "../lib/ai/types";
import { getAIUiCopy } from "../lib/ai/ui-copy";
import { buildUpdateResult } from "../lib/github-update";
import { getUpdateLink } from "../lib/update-link";
import { proxiedImageUrl } from "../lib/image-utils";
import { clearLyricContent, hasClearableLyricContent } from "../lib/clear-content";
import { defaultState } from "../components/editor/editor-defaults";
import {
  FONT_PREVIEW_COLORS,
  FONT_PREVIEW_PALETTE,
  FONT_SCHEME_PRESETS,
  identifyFontPreset,
  normalizeFontScheme
} from "../lib/font-schemes";
import { messages } from "../lib/i18n";
import {
  getActiveFontMode,
  getResolvedFontStyle,
  quoteSingleFontFamily,
  sanitizeCssFontFamilyName
} from "../lib/fonts";
import { formatChineseTranslation, splitAlternatingLyrics } from "../lib/lyric-format";
import type { CardStyle } from "../lib/types";
import { compareVersionStrings } from "../lib/version-compare";

const baseStyle: CardStyle = {
  backgroundMode: "palette",
  layoutMode: "portrait",
  ratio: "custom",
  width: 1040,
  height: 1400,
  autoHeight: true,
  font: "sans-heavy",
  customFontEnabled: false,
  customFontFamily: "",
  lyricFontSize: 60,
  lineHeight: 1.4,
  align: "center",
  textColorMode: "auto",
  textColorPreset: "white",
  customTextColor: "#FFFFFF",
  resolvedTextColor: "#FFFFFF",
  translationEnabled: true,
  translationText: "翻译",
  translationScale: 0.75,
  allowTwoLineTitle: false,
  contentMode: "lyrics",
  instrumentalText: "Instrumental Track",
  showCover: true,
  showSongInfo: true,
  showAlbumName: true,
  showGeneratedWatermark: true,
  showSharedBy: true,
  sharedByText: "Shared by Test",
  showWatermark: true,
  showPlatformBadge: true,
  showFineGrid: true,
  fineGridDensity: "medium",
  coverCropScale: 1,
  watermark: "generated by lyric card generator"
};

function main() {
  testLyricFormat();
  testVersionCompare();
  testUpdateResult();
  testLayoutEngine();
  testImageProxy();
  testFontResolution();
  testFontSchemeTranslations();
  testAITranslationPrompt();
  testClearLyricContent();
  console.log(JSON.stringify({ ok: true, tests: 9 }, null, 2));
}

function testClearLyricContent() {
  assert(!hasClearableLyricContent(defaultState), "default state is already clear");
  assert(
    hasClearableLyricContent({ ...defaultState, song: { ...defaultState.song, explicit: true } }),
    "explicit-only metadata can be cleared"
  );

  const populated = {
    ...defaultState,
    song: { ...defaultState.song, source: "apple" as const, title: "Opalite", album: "Album" },
    lyrics: "One line",
    style: { ...defaultState.style, showSharedBy: true, sharedByText: "Shared by Test" }
  };
  assert(hasClearableLyricContent(populated), "song content can be cleared");

  const cleared = clearLyricContent(populated);
  assert(!hasClearableLyricContent(cleared), "cleared state rejects repeated clear");
  assertEqual(cleared.style.showSharedBy, true, "clear keeps card defaults and visual settings");
  assertEqual(cleared.style.sharedByText, "Shared by Test", "clear keeps default sharer text");
}

function testLyricFormat() {
  const split = splitAlternatingLyrics(
    [
      "English 1",
      "\u4E2D\u6587 1",
      "\u541B\u306E\u540D\u306F",
      "\uC0AC\uB791\uD574",
      "English 2",
      "\u4E2D\u6587 2"
    ].join("\n")
  );
  assertEqual(split.lyrics, "English 1\n\u541B\u306E\u540D\u306F\n\uC0AC\uB791\uD574\nEnglish 2", "split lyrics");
  assertEqual(split.translationText, "\u4E2D\u6587 1\n\u4E2D\u6587 2", "split translation");
  const traditionalChineseSplit = splitAlternatingLyrics("English line\n\u7E41\u9AD4\u4E2D\u6587 1", "zh-TW");
  assertEqual(traditionalChineseSplit.lyrics, "English line", "split Traditional Chinese target lyrics");
  assertEqual(traditionalChineseSplit.translationText, "\u7E41\u9AD4\u4E2D\u6587 1", "split Traditional Chinese target translation");
  const englishSplit = splitAlternatingLyrics("君の名は\nI remember your name", "en");
  assertEqual(englishSplit.lyrics, "君の名は", "split English target lyrics");
  assertEqual(englishSplit.translationText, "I remember your name", "split English target translation");
  const frenchSplit = splitAlternatingLyrics("I miss you tonight\nTu me manques ce soir", "fr");
  assertEqual(frenchSplit.lyrics, "I miss you tonight", "split French target lyrics");
  assertEqual(frenchSplit.translationText, "Tu me manques ce soir", "split French target translation");
  const japaneseSplit = splitAlternatingLyrics("I remember your name\n君の名前を覚えている", "ja");
  assertEqual(japaneseSplit.lyrics, "I remember your name", "split Japanese target lyrics");
  assertEqual(japaneseSplit.translationText, "君の名前を覚えている", "split Japanese target translation");
  const spanishSplit = splitAlternatingLyrics("I miss you tonight\nTe echo de menos esta noche", "es");
  assertEqual(spanishSplit.lyrics, "I miss you tonight", "split Spanish target lyrics");
  assertEqual(spanishSplit.translationText, "Te echo de menos esta noche", "split Spanish target translation");
  assertEqual(
    formatChineseTranslation("\u4F60\u6765,\u6211\u8D70\u3002\u518D\u89C1\uFF0C\u4E0D\u9001."),
    "\u4F60\u6765 \u6211\u8D70\n\u518D\u89C1 \u4E0D\u9001\n",
    "format translation"
  );
}

function testVersionCompare() {
  assert(compareVersionStrings("v2.0.0", "1.1.0")! > 0, "v prefix compare");
  assert(compareVersionStrings("2.0.0", "2.0.0-beta.1")! > 0, "release beats prerelease");
  assert(compareVersionStrings("2.0.0-beta.2", "2.0.0-beta.1")! > 0, "prerelease numeric compare");
}

function testUpdateResult() {
  const result = buildUpdateResult(
    {
      tag_name: "v2.0.0",
      html_url: "https://github.com/Qrzzzz/lyrics-card-generator/releases/tag/v2.0.0",
      assets: [
        {
          name: "Lyrics Card Generator Setup 2.0.0.exe",
          browser_download_url: "https://example.com/setup.exe"
        },
        {
          name: "Lyrics Card Generator-2.0.0-portable.exe",
          browser_download_url: "https://example.com/portable.exe"
        }
      ]
    },
    "1.1.0"
  );
  assert(result.status === "update-available", "update available");
  if (result.status === "update-available") {
    assertEqual(result.installerUrl, "https://example.com/setup.exe", "installer URL");
    assertEqual(result.portableUrl, "https://example.com/portable.exe", "portable URL");
    assertEqual(getUpdateLink(result), "https://github.com/Qrzzzz/lyrics-card-generator/releases/tag/v2.0.0", "update link opens release page");
  }
}

function testLayoutEngine() {
  const portrait = getPortraitLayout({ width: 1040, height: 1400 }, baseStyle, { source: "apple", album: "Album" });
  const portraitWithoutAlbum = getPortraitLayout({ width: 1040, height: 1400 }, baseStyle, { source: "apple", album: "" });
  assert(Math.abs(centerX(portrait.safeRect) - centerX(portrait.lyricsRect)) < 1, "portrait center lyrics");
  assert(portrait.lyricsRect.width <= portrait.safeRect.width, "portrait lyrics inside safe area");
  assert(
    portrait.headerRect && portraitWithoutAlbum.headerRect && portrait.headerRect.height > portraitWithoutAlbum.headerRect.height,
    "portrait reserves album height only when album text exists"
  );

  const landscape = getLandscapeLayout(
    { width: 2520, height: 1080 },
    { ...baseStyle, layoutMode: "landscape", ratio: "21:9", autoHeight: false },
    { source: "apple", album: "Album" }
  );
  const landscapeWithoutAlbum = getLandscapeLayout(
    { width: 2520, height: 1080 },
    { ...baseStyle, layoutMode: "landscape", ratio: "21:9", autoHeight: false },
    { source: "apple", album: "" }
  );
  assert(landscape.coverRect && landscape.coverRect.width <= landscape.safeRect.height * 0.74 + 1, "landscape cover height bound");
  assert(landscape.contentRect.width <= 1180, "landscape content max width");
  assert(landscape.lyricsRect.height > 170, "landscape lyrics has usable height");
  assert(
    landscape.songInfoRect &&
      landscapeWithoutAlbum.songInfoRect &&
      landscape.songInfoRect.height > landscapeWithoutAlbum.songInfoRect.height,
    "landscape reserves album height only when album text exists"
  );
}

function testImageProxy() {
  assertEqual(proxiedImageUrl("blob:http://localhost/id"), "blob:http://localhost/id", "blob not proxied");
  assertEqual(proxiedImageUrl("data:image/png;base64,abc"), "data:image/png;base64,abc", "data not proxied");
  assertEqual(proxiedImageUrl("file:///C:/cover.png"), "file:///C:/cover.png", "file not proxied");
  assertEqual(proxiedImageUrl("https://example.com/cover.jpg"), "/api/image-proxy?url=https%3A%2F%2Fexample.com%2Fcover.jpg", "http proxied");
}

function testFontResolution() {
  assertEqual(sanitizeCssFontFamilyName(' "Microsoft YaHei" (TrueType) '), "Microsoft YaHei", "sanitize registry family");
  assertEqual(sanitizeCssFontFamilyName("Arial, sans-serif"), "Arial", "drop fallback list");
  assertEqual(sanitizeCssFontFamilyName("Arial & Arial Unicode MS"), "Arial", "select one combined registry family");
  assertEqual(quoteSingleFontFamily("sans-serif"), "sans-serif", "generic family is unquoted");
  assertEqual(quoteSingleFontFamily('Test "Font"'), '"Test \\"Font\\""', "custom family is escaped");
  assertEqual(getActiveFontMode(baseStyle), "preset", "disabled custom font stays in preset mode");
  assert(
    getResolvedFontStyle(baseStyle)?.fontFamily?.startsWith('"Source Han Sans SC", var(--font-source-han-sans-heavy)'),
    "legacy default resolves to the Source Han Sans scheme"
  );

  const customStyle = {
    ...baseStyle,
    customFontEnabled: true,
    customFontFamily: "Microsoft YaHei",
    customFontLabel: "微软雅黑",
    customFontWeight: 700,
    customFontStyle: "italic" as const
  };
  assertEqual(getActiveFontMode(customStyle), "custom", "valid custom font activates custom mode");
  assert(
    getResolvedFontStyle(customStyle)?.fontFamily?.startsWith('"Microsoft YaHei", var(--font-source-han-sans-heavy)'),
    "resolved custom font keeps the shared export fallback stack"
  );
  assertEqual(getResolvedFontStyle(customStyle)?.fontWeight, 700, "resolved custom font keeps its face weight");
  assertEqual(getResolvedFontStyle(customStyle)?.fontStyle, "italic", "resolved custom font keeps its face style");

  const splitFontStyle = {
    ...baseStyle,
    fontScheme: {
      mode: "custom" as const,
      cjkFontFamily: "Source Han Sans SC",
      latinFontFamily: "Georgia"
    }
  };
  assertEqual(getActiveFontMode(splitFontStyle), "custom", "split CJK and Latin families activate custom mode");
  assert(
    getResolvedFontStyle(splitFontStyle)?.fontFamily?.startsWith('"Georgia", "Source Han Sans SC"'),
    "Latin family precedes the CJK fallback so each script resolves to its selected family"
  );
  assertEqual(
    identifyFontPreset(FONT_SCHEME_PRESETS["source-han-serif"]),
    "source-han-serif",
    "Source Han Serif fields are recognized as the serif preset"
  );
  assertEqual(
    normalizeFontScheme({
      mode: "custom",
      cjkFontFamily: "Source Han Sans SC",
      latinFontFamily: "Source Han Sans SC"
    }).presetId,
    "source-han-sans",
    "custom fields that exactly match a preset normalize to that preset"
  );
}

function testFontSchemeTranslations() {
  const expectedTitles = {
    zh: "字体方案",
    "zh-TW": "字體方案",
    en: "Font Schemes",
    fr: "Jeux de polices",
    ja: "フォント構成",
    es: "Combinaciones tipográficas"
  } as const;

  for (const [locale, expectedTitle] of Object.entries(expectedTitles)) {
    assertEqual(messages[locale as keyof typeof messages].fontSchemeTitle, expectedTitle, `${locale} font scheme title`);
  }

  assertEqual(messages["zh-TW"].fontSchemeCurrentTitle, "目前方案", "Traditional Chinese current scheme wording");
  assertEqual(messages["zh-TW"].fontSchemeCustomTitle, "自訂方案", "Traditional Chinese custom scheme wording");
  assertEqual(messages["zh-TW"].fontSchemeCjkFont, "中日韓文字體", "Traditional Chinese CJK label");
  assertEqual(messages["zh-TW"].fontSchemeSaveCurrent, "儲存為目前方案", "Traditional Chinese save action");
  assertEqual(
    messages["zh-TW"].fontSchemePreviewBackgroundDescription,
    "使用與真實歌詞卡片相同的背景演算法，並固定以深宵藍、鈷藍、天藍與冰藍取色。",
    "Traditional Chinese generated preview background description"
  );
  assertEqual(FONT_PREVIEW_COLORS.length, 4, "font preview uses four fixed palette inputs");
  assertEqual(FONT_PREVIEW_PALETTE.primary, "#0F2D58", "font preview midnight primary");
  assertEqual(FONT_PREVIEW_PALETTE.secondary, "#1E66B0", "font preview cobalt secondary");
  assertEqual(FONT_PREVIEW_PALETTE.accent, "#53A1DB", "font preview sky accent");
  assertEqual(FONT_PREVIEW_PALETTE.dark, "#9FCFEE", "font preview ice color");
}

function testAITranslationPrompt() {
  const prompt = buildLyricsTranslationPrompt({
    lyrics: "I miss you\nTonight",
    style: "recommended",
    targetLocale: "zh"
  });
  assert(prompt.includes("输出规则是最高优先级，必须严格遵守"), "strong output rules retained");
  assert(prompt.includes(PROMPT_OUTPUT_RULES), "output rule block included");
  assert(prompt.includes("采用“推荐版”风格：这是一个独立版本"), "recommended is its own style");
  assert(!prompt.includes("采用“抒情译版”风格"), "only selected style included");
  const frenchPrompt = buildLyricsTranslationPrompt({
    lyrics: "I miss you",
    style: "faithful",
    targetLocale: "fr"
  });
  assert(frenchPrompt.includes("traduction française"), "French UI requests French output");
  assert(frenchPrompt.includes("Fidèle et soignée"), "French style prompt is localized");
  assert(!frenchPrompt.includes("简体中文译文"), "French prompt does not request Chinese output");
  const localeTargets = {
    zh: "简体中文译文本身",
    "zh-TW": "繁體中文譯文本身",
    en: "English translation itself",
    fr: "traduction française elle-même",
    ja: "日本語の翻訳本文だけ",
    es: "traducción al español"
  } as const;
  for (const [targetLocale, marker] of Object.entries(localeTargets)) {
    const localizedPrompt = buildLyricsTranslationPrompt({
      lyrics: "I miss you",
      style: "recommended",
      targetLocale: targetLocale as keyof typeof localeTargets
    });
    assert(localizedPrompt.includes(marker), `${targetLocale} prompt targets its UI language`);
    assertEqual(getTranslationStyles(targetLocale as keyof typeof localeTargets).length, 6, `${targetLocale} has six localized styles`);
  }
  assertEqual(getAIUiCopy("zh-TW").settingsTitle, "應用程式設定", "Traditional Chinese AI UI copy");
  assertEqual(getAIUiCopy("fr").aiSection, "Traduction des paroles par IA", "French AI UI copy");
  assertEqual(getAIUiCopy("ja").settingsSaveFailed, "AI 設定を保存できませんでした。", "Japanese AI UI copy");
  assertEqual(getAIUiCopy("es").defaultStyle, "Estilo de traducción predeterminado", "Spanish AI UI copy");
  const promptLibrary = {
    localeOverrides: {
      zh: {
        formatRulesOverride: "只输出中文译文。",
        styleOverrides: [{ id: "lyrical" as const, title: "安静版", prompt: "保持中文表达安静克制。" }]
      },
      en: {
        formatRulesOverride: "ONLY THE TRANSLATED LINES.",
        styleOverrides: [{ id: "lyrical" as const, title: "Quiet cut", prompt: "Keep every line quiet and close." }]
      }
    },
    hiddenStyleIds: ["faithful" as const],
    customPresets: [
      { id: "custom:first", title: "Night drive", prompt: "Use cinematic night-drive imagery." },
      { id: "custom:second", title: "Bare", prompt: "Use plain and spare language." }
    ]
  };
  const customPrompt = buildLyricsTranslationPrompt({ lyrics: "I miss you", presetId: "custom:first", targetLocale: "en", promptLibrary });
  assert(customPrompt.includes("Use cinematic night-drive imagery."), "custom preset replaces the style module");
  assert(customPrompt.includes("ONLY THE TRANSLATED LINES."), "custom format rules remain a separate shared module");
  assert(!customPrompt.includes("Use the Recommended style"), "custom preset does not inherit recommended style text");
  const englishStylePrompt = buildLyricsTranslationPrompt({ lyrics: "I miss you", presetId: "lyrical", targetLocale: "en", promptLibrary });
  assert(englishStylePrompt.includes("Keep every line quiet and close."), "English uses its own style override");
  assert(!englishStylePrompt.includes("保持中文表达安静克制"), "Chinese style override never leaks into English");
  const japanesePrompt = buildLyricsTranslationPrompt({ lyrics: "I miss you", presetId: "lyrical", targetLocale: "ja", promptLibrary });
  assert(japanesePrompt.includes(getDefaultStylePrompt("ja", "lyrical")), "Japanese keeps its localized default style");
  assert(!japanesePrompt.includes("ONLY THE TRANSLATED LINES."), "English format override never leaks into Japanese");
  assertEqual(getTranslationPresets("en", promptLibrary).length, 7, "one hidden default plus two custom presets resolve to seven entries");
  assertEqual(getTranslationPresets("zh", promptLibrary).find((preset) => preset.id === "lyrical")?.name, "安静版", "title override is locale scoped");
  assertEqual(getTranslationPresets("ja", promptLibrary).find((preset) => preset.id === "lyrical")?.name, "抒情的", "title-only edits do not leak across locales");
  const resetChinese = setLocalePromptOverrides(promptLibrary, "zh", { formatRulesOverride: "", styleOverrides: [] });
  assertEqual(getLocalePromptOverrides(resetChinese, "zh").styleOverrides.length, 0, "reset clears only the current locale");
  assertEqual(getLocalePromptOverrides(resetChinese, "en").styleOverrides.length, 1, "reset preserves other locale overrides");
  const normalizedLibrary = normalizeAISettings({
    ...DEFAULT_AI_SETTINGS,
    defaultStyle: "faithful",
    promptLibrary: {
      ...promptLibrary,
      customPresets: [...promptLibrary.customPresets, { id: "custom:third", title: "Third", prompt: "Ignored" }]
    }
  });
  assertEqual(normalizedLibrary.promptLibrary.customPresets.length, 2, "custom preset storage is capped at two");
  assertEqual(normalizedLibrary.defaultStyle, "recommended", "deleting the selected default falls back to recommended");
  const duplicateMigration = normalizePromptLibrary({
    customPresets: [
      { id: "custom:a", title: "A old", prompt: "First" },
      { id: "custom:a", title: "A", prompt: "Updated" },
      { id: "custom:b", title: "B", prompt: "Second" },
      { id: "custom:empty", title: "Empty", prompt: "" }
    ]
  });
  assertEqual(duplicateMigration.customPresets.length, 2, "custom migration filters, deduplicates, then caps at two");
  assertEqual(duplicateMigration.customPresets[1]?.id, "custom:b", "deduplication does not discard a later unique preset");
  assertEqual(duplicateMigration.customPresets[0]?.initialTitle, "A", "legacy custom presets capture their current title as the reset baseline");
  assertEqual(duplicateMigration.customPresets[0]?.initialPrompt, "Updated", "legacy custom presets capture their current prompt as the reset baseline");
  const emptyEditableDraft = normalizePromptLibrary({
    localeOverrides: { zh: { styleOverrides: [{ id: "lyrical", title: "", prompt: "" }] } }
  });
  assertEqual(getLocalePromptOverrides(emptyEditableDraft, "zh").styleOverrides.length, 1, "empty built-in draft remains present while replacing all text");
  assertEqual(cleanAITranslation("```text\n译文如下：\n想念你\n```"), "想念你", "clean AI wrapper text");
  assertThrows(
    () => validateConfiguredSettings({
      baseUrl: "https://api.example.com/v1",
      model: "model",
      temperature: 0.7,
      defaultStyle: "recommended",
      reasoningEnabled: false,
      promptLibrary: DEFAULT_AI_SETTINGS.promptLibrary,
      hasApiKey: false
    }),
    "未配置 API Key",
    "missing API key validation"
  );
  assertThrows(
    () => validateConfiguredSettings({
      baseUrl: "https://api.example.com/v1",
      model: "",
      temperature: 0.7,
      defaultStyle: "recommended",
      reasoningEnabled: false,
      promptLibrary: DEFAULT_AI_SETTINGS.promptLibrary,
      hasApiKey: true
    }),
    "未配置模型",
    "missing model validation"
  );
}

function centerX(rect: { x: number; width: number }) {
  return rect.x + rect.width / 2;
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) {
    throw new Error(`Assertion failed: ${message}`);
  }
}

function assertEqual<T>(actual: T, expected: T, message: string) {
  if (actual !== expected) {
    throw new Error(`Assertion failed: ${message}. Expected ${String(expected)}, got ${String(actual)}`);
  }
}

function assertThrows(action: () => void, expectedMessage: string, message: string) {
  try {
    action();
  } catch (error) {
    assert(error instanceof Error && error.message.includes(expectedMessage), message);
    return;
  }
  throw new Error(`Assertion failed: ${message}. Expected function to throw.`);
}

main();
