import type { Locale } from "@/lib/types";

const en = {
  settings: "Settings",
  description: "Change the app interface and defaults for new lyric cards.",
  general: "General",
  appearance: "Appearance",
  export: "Card & export",
  ai: "AI",
  about: "About",
  generalDescription: "Language, interaction, history, and storage preferences.",
  appearanceDescription: "Interface mode, accent color, and font.",
  exportDescription: "Defaults for new-card credits and exported image files.",
  aiDescription: "Provider connection and translation prompts.",
  aboutDescription: "Version, updates, and project links.",
  language: "Language",
  spark: "Click effect",
  sparkDescription: "Show a brief spark where you click.",
  reduceMotion: "Reduce motion",
  reduceMotionDescription: "Use fewer interface movements and celebration effects. The system setting is always respected.",
  interactionPreferences: "Interface & interaction",
  historyAndStorage: "History & storage",
  historyAndStorageDescription: "Control automatic history and restore application preferences without changing documents or saved content.",
  restoreAppPreferences: "Restore application defaults",
  restoreAppPreferencesDescription: "Resets interface, appearance, and card/export defaults. Current documents, history, manual saves, and the AI API key are kept.",
  restoreAppPreferencesConfirm: "Restore interface, appearance, and card/export defaults? Your current document, history, manual saves, and AI API key will not be changed.",
  preferencesRestored: "Application preferences restored",
  retrySave: "Retry save",
  retryLoad: "Retry load",
  preferenceSaveFailed: "Application preferences could not be saved.",
  theme: "Interface mode",
  albumDynamic: "Match album cover",
  darkAcrylic: "Dark Acrylic",
  lightAcrylic: "Light Acrylic",
  acrylicEffect: "Acrylic effect",
  acrylicSupportNote: "Acrylic uses the Windows window material and requires Windows 11 22H2 or later. Other systems use a transparent fallback.",
  acrylicAlbumDisabled: "Album-cover colors are not available with Acrylic.",
  accentColor: "Accent color",
  accentAlbumDynamic: "Match album cover",
  accentPreset: "Preset colors",
  accentCustom: "Custom hex",
  accentRed: "Red",
  accentOrange: "Orange",
  accentYellow: "Yellow",
  accentGreen: "Green",
  accentBlue: "Blue",
  accentPurple: "Purple",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "Enter a 6-digit hex color, such as #7C3AED.",
  uiFont: "Interface font",
  uiFontDescription: "Enter a font-family list. CSS functions and declarations are not allowed.",
  uiFontInvalid: "Enter font names separated by commas; do not use CSS functions or declarations.",
  restoreSystemFont: "Restore system default",
  defaultFont: "System default",
  light: "Light",
  dark: "Dark",
  newCardDefaults: "New-card footer defaults",
  newCardDefaultsDescription: "Applied only when a genuinely new card is created; existing and loaded documents stay unchanged.",
  fileExportDefaults: "File export defaults",
  fileExportDefaultsDescription: "Default format and quality for newly exported image files.",
  defaultGeneratedWatermark: "Project signature",
  defaultGeneratedWatermarkDescription: "Show the project signature on new cards.",
  defaultSharedBy: "Sharer credit",
  defaultSharedByDescription: "Show a sharer credit on new cards.",
  defaultSharedByText: "Default sharer text",
  defaultSharedByPlaceholder: "e.g. Shared by Cherry",
  exportFormat: "Default image format",
  exportQuality: "Default image quality",
  low: "Standard · 1x",
  medium: "High · 1.4x",
  high: "Maximum · 2x",
  version: "Version",
  checkUpdates: "Check for updates",
  githubProfile: "GitHub profile",
  repository: "Project repository",
  releases: "Releases",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  example: "Example",
  examples: "Examples",
  loadExample: "Load example",
  exampleLoaded: "Example loaded",
  originalLanguage: "Source language",
  translationLanguage: "Translation language",
  firstLaunchTitle: "Choose a language",
  firstLaunchDescription: "You can change this later in Settings.",
  projectDescription: "Create lyric cards from music links or local audio.",
  licenses: "Licenses & notices",
  licensesDescription: "These documents are bundled with the app and remain available offline.",
  sourceAvailableLicense: "Lyrics Card Generator source-available license",
  thirdPartyNotices: "Third-party notices",
  sourceHanSansLicense: "Source Han Sans license",
  sourceHanSerifLicense: "Source Han Serif license",
  clearAll: "Clear content",
  clearAllDescription: "Clear the current song and keep app settings.",
  clearAlreadyEmpty: "The card is already empty"
};

type Copy = typeof en;

const zh: Copy = {
  settings: "设置",
  description: "调整软件界面和新歌词卡片的默认设置。",
  general: "通用",
  appearance: "外观",
  export: "卡片与导出",
  ai: "AI",
  about: "关于",
  generalDescription: "语言、交互、历史与存储偏好。",
  appearanceDescription: "界面模式、主题色和字体。",
  exportDescription: "新卡片页脚与导出图片文件的默认值。",
  aiDescription: "服务连接和翻译提示词。",
  aboutDescription: "版本、更新和项目链接。",
  language: "语言",
  spark: "点击特效",
  sparkDescription: "点击界面时显示短暂的火花效果。",
  reduceMotion: "减弱动效",
  reduceMotionDescription: "减少界面位移和庆祝动画；系统的减弱动态效果设置始终生效。",
  interactionPreferences: "界面与交互",
  historyAndStorage: "历史与存储",
  historyAndStorageDescription: "管理自动历史，并在不影响文档或存档的前提下恢复应用偏好。",
  restoreAppPreferences: "恢复应用偏好默认值",
  restoreAppPreferencesDescription: "仅重置界面、外观及卡片/导出默认值；当前文档、历史、手动存档和 AI API Key 均会保留。",
  restoreAppPreferencesConfirm: "恢复界面、外观及卡片/导出默认值？当前文档、历史、手动存档和 AI API Key 不会更改。",
  preferencesRestored: "已恢复应用偏好默认值",
  retrySave: "重试保存",
  retryLoad: "重试加载",
  preferenceSaveFailed: "无法保存应用偏好。",
  theme: "界面模式",
  albumDynamic: "跟随专辑封面",
  darkAcrylic: "深色亚克力",
  lightAcrylic: "浅色亚克力",
  acrylicEffect: "亚克力效果",
  acrylicSupportNote: "亚克力使用 Windows 窗口材质，需要 Windows 11 22H2 或更高版本；其他系统使用透明备用样式。",
  acrylicAlbumDisabled: "亚克力模式暂不支持跟随专辑封面配色。",
  accentColor: "主题色",
  accentAlbumDynamic: "跟随专辑封面",
  accentPreset: "预设颜色",
  accentCustom: "自定义色号",
  accentRed: "红色",
  accentOrange: "橙色",
  accentYellow: "黄色",
  accentGreen: "绿色",
  accentBlue: "蓝色",
  accentPurple: "紫色",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "请输入 6 位十六进制颜色，例如 #7C3AED。",
  uiFont: "界面字体",
  uiFontDescription: "输入 font-family 字体列表；不允许 CSS 函数或声明。",
  uiFontInvalid: "请输入以逗号分隔的字体名称，不要使用 CSS 函数或声明。",
  restoreSystemFont: "恢复系统默认",
  defaultFont: "系统默认",
  light: "浅色",
  dark: "深色",
  newCardDefaults: "新卡片页脚默认值",
  newCardDefaultsDescription: "仅在真正新建卡片时应用；当前文档和已载入文档不会被偏好变化覆盖。",
  fileExportDefaults: "文件导出默认值",
  fileExportDefaultsDescription: "新导出图片文件使用的默认格式和质量。",
  defaultGeneratedWatermark: "项目署名",
  defaultGeneratedWatermarkDescription: "新卡片默认显示项目署名。",
  defaultSharedBy: "分享人署名",
  defaultSharedByDescription: "新卡片默认显示分享人署名。",
  defaultSharedByText: "默认分享人文字",
  defaultSharedByPlaceholder: "例如：Shared by Cherry",
  exportFormat: "默认图片格式",
  exportQuality: "默认图片质量",
  low: "标准 · 1x",
  medium: "高清 · 1.4x",
  high: "最高 · 2x",
  version: "版本",
  checkUpdates: "检查更新",
  githubProfile: "GitHub 主页",
  repository: "项目仓库",
  releases: "发布页面",
  save: "保存",
  cancel: "取消",
  close: "关闭",
  example: "示例",
  examples: "示例",
  loadExample: "载入示例",
  exampleLoaded: "示例已载入",
  originalLanguage: "原文语言",
  translationLanguage: "译文语言",
  firstLaunchTitle: "选择界面语言",
  firstLaunchDescription: "之后可以随时在设置中更改。",
  projectDescription: "从音乐链接或本地音频制作歌词卡片。",
  licenses: "许可与声明",
  licensesDescription: "这些文档随软件打包，离线时也可访问。",
  sourceAvailableLicense: "歌词卡片生成器 source-available 许可",
  thirdPartyNotices: "第三方许可声明",
  sourceHanSansLicense: "思源黑体许可",
  sourceHanSerifLicense: "思源宋体许可",
  clearAll: "清空内容",
  clearAllDescription: "清空当前歌曲，保留软件设置。",
  clearAlreadyEmpty: "卡片已为空"
};

const zhTW: Copy = {
  settings: "設定",
  description: "調整應用程式介面與新歌詞卡片的預設值。",
  general: "一般",
  appearance: "外觀",
  export: "卡片與匯出",
  ai: "AI",
  about: "關於",
  generalDescription: "語言、操作、歷史與儲存偏好。",
  appearanceDescription: "介面模式、強調色與字型。",
  exportDescription: "新卡片頁尾與匯出圖片檔案的預設值。",
  aiDescription: "服務連線與翻譯提示詞。",
  aboutDescription: "版本、更新與專案連結。",
  language: "語言",
  spark: "點擊特效",
  sparkDescription: "點擊介面時顯示短暫的火花效果。",
  reduceMotion: "減少動態效果",
  reduceMotionDescription: "減少介面移動與慶祝動畫；系統的動態效果設定一律優先套用。",
  interactionPreferences: "介面與操作",
  historyAndStorage: "歷史與儲存",
  historyAndStorageDescription: "管理自動歷史，並在不影響文件或存檔的情況下還原應用程式偏好。",
  restoreAppPreferences: "還原應用程式偏好預設值",
  restoreAppPreferencesDescription: "只重設介面、外觀及卡片／匯出預設值；目前文件、歷史、手動存檔與 AI API Key 都會保留。",
  restoreAppPreferencesConfirm: "還原介面、外觀及卡片／匯出預設值？目前文件、歷史、手動存檔與 AI API Key 不會變更。",
  preferencesRestored: "已還原應用程式偏好預設值",
  retrySave: "重試儲存",
  retryLoad: "重試載入",
  preferenceSaveFailed: "無法儲存應用程式偏好。",
  theme: "介面模式",
  albumDynamic: "配合專輯封面",
  darkAcrylic: "深色壓克力",
  lightAcrylic: "淺色壓克力",
  acrylicEffect: "壓克力效果",
  acrylicSupportNote: "壓克力使用 Windows 視窗材質，需要 Windows 11 22H2 或更新版本；其他系統會改用透明備用樣式。",
  acrylicAlbumDisabled: "壓克力模式目前不支援配合專輯封面取色。",
  accentColor: "強調色",
  accentAlbumDynamic: "配合專輯封面",
  accentPreset: "預設顏色",
  accentCustom: "自訂色碼",
  accentRed: "紅色",
  accentOrange: "橘色",
  accentYellow: "黃色",
  accentGreen: "綠色",
  accentBlue: "藍色",
  accentPurple: "紫色",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "請輸入 6 位十六進位色碼，例如 #7C3AED。",
  uiFont: "介面字型",
  uiFontDescription: "輸入 font-family 字型清單；不允許 CSS 函式或宣告。",
  uiFontInvalid: "請輸入以逗號分隔的字型名稱，勿使用 CSS 函式或宣告。",
  restoreSystemFont: "還原系統預設",
  defaultFont: "系統預設",
  light: "淺色",
  dark: "深色",
  newCardDefaults: "新卡片頁尾預設值",
  newCardDefaultsDescription: "只在真正建立新卡片時套用；目前文件與已載入文件不會被偏好變更覆寫。",
  fileExportDefaults: "檔案匯出預設值",
  fileExportDefaultsDescription: "新匯出圖片檔案使用的預設格式與品質。",
  defaultGeneratedWatermark: "專案署名",
  defaultGeneratedWatermarkDescription: "新卡片預設顯示專案署名。",
  defaultSharedBy: "分享者署名",
  defaultSharedByDescription: "新卡片預設顯示分享者署名。",
  defaultSharedByText: "預設分享者文字",
  defaultSharedByPlaceholder: "例如：Shared by Cherry",
  exportFormat: "預設圖片格式",
  exportQuality: "預設圖片品質",
  low: "標準 · 1x",
  medium: "高畫質 · 1.4x",
  high: "最高 · 2x",
  version: "版本",
  checkUpdates: "檢查更新",
  githubProfile: "GitHub 個人頁面",
  repository: "專案原始碼",
  releases: "發行版本",
  save: "儲存",
  cancel: "取消",
  close: "關閉",
  example: "範例",
  examples: "範例",
  loadExample: "載入範例",
  exampleLoaded: "範例已載入",
  originalLanguage: "原文語言",
  translationLanguage: "譯文語言",
  firstLaunchTitle: "選擇介面語言",
  firstLaunchDescription: "之後可以隨時在設定中更改。",
  projectDescription: "從音樂連結或本機音訊製作歌詞卡片。",
  licenses: "授權與聲明",
  licensesDescription: "這些文件隨應用程式一同封裝，離線時也能存取。",
  sourceAvailableLicense: "歌詞卡片產生器 source-available 授權",
  thirdPartyNotices: "第三方授權聲明",
  sourceHanSansLicense: "思源黑體授權",
  sourceHanSerifLicense: "思源宋體授權",
  clearAll: "清除內容",
  clearAllDescription: "清除目前歌曲，保留應用程式設定。",
  clearAlreadyEmpty: "卡片已為空"
};

const fr: Copy = {
  settings: "Paramètres",
  description: "Modifiez l’interface et les valeurs par défaut des nouvelles cartes.",
  general: "Général",
  appearance: "Apparence",
  export: "Carte et export",
  ai: "IA",
  about: "À propos",
  generalDescription: "Langue, utilisation, historique et stockage.",
  appearanceDescription: "Mode d’affichage, couleur d’accent et police.",
  exportDescription: "Valeurs par défaut des crédits des nouvelles cartes et des fichiers exportés.",
  aiDescription: "Connexion au service et prompts de traduction.",
  aboutDescription: "Version, mises à jour et liens du projet.",
  language: "Langue",
  spark: "Effet au clic",
  sparkDescription: "Affiche une brève étincelle à chaque clic.",
  reduceMotion: "Réduire les animations",
  reduceMotionDescription: "Limite les mouvements de l’interface et les animations de fin. Le réglage du système reste prioritaire.",
  interactionPreferences: "Interface et utilisation",
  historyAndStorage: "Historique et stockage",
  historyAndStorageDescription: "Gérez l’historique automatique et restaurez les préférences sans modifier les documents ou sauvegardes.",
  restoreAppPreferences: "Restaurer les préférences par défaut",
  restoreAppPreferencesDescription: "Réinitialise l’interface, l’apparence et les valeurs carte/export. Le document, l’historique, les sauvegardes manuelles et la clé API IA sont conservés.",
  restoreAppPreferencesConfirm: "Restaurer l’interface, l’apparence et les valeurs carte/export ? Le document, l’historique, les sauvegardes manuelles et la clé API IA ne seront pas modifiés.",
  preferencesRestored: "Préférences de l’application restaurées",
  retrySave: "Réessayer l’enregistrement",
  retryLoad: "Réessayer le chargement",
  preferenceSaveFailed: "Impossible d’enregistrer les préférences de l’application.",
  theme: "Mode d’affichage",
  albumDynamic: "Selon la pochette",
  darkAcrylic: "Acrylic sombre",
  lightAcrylic: "Acrylic clair",
  acrylicEffect: "Effet Acrylic",
  acrylicSupportNote: "Acrylic utilise le matériau de fenêtre de Windows et nécessite Windows 11 22H2 ou une version ultérieure. Ailleurs, un fond transparent est utilisé.",
  acrylicAlbumDisabled: "Les couleurs de la pochette ne sont pas disponibles avec Acrylic.",
  accentColor: "Couleur d’accent",
  accentAlbumDynamic: "Selon la pochette",
  accentPreset: "Couleurs prédéfinies",
  accentCustom: "Code hexadécimal",
  accentRed: "Rouge",
  accentOrange: "Orange",
  accentYellow: "Jaune",
  accentGreen: "Vert",
  accentBlue: "Bleu",
  accentPurple: "Violet",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "Saisissez un code hexadécimal à 6 chiffres, par exemple #7C3AED.",
  uiFont: "Police de l’interface",
  uiFontDescription: "Saisissez une liste font-family. Les fonctions et déclarations CSS sont interdites.",
  uiFontInvalid: "Saisissez des noms de police séparés par des virgules, sans fonction ni déclaration CSS.",
  restoreSystemFont: "Restaurer la police du système",
  defaultFont: "Police du système",
  light: "Clair",
  dark: "Sombre",
  newCardDefaults: "Valeurs du pied des nouvelles cartes",
  newCardDefaultsDescription: "Appliquées uniquement à une carte réellement nouvelle ; les documents ouverts restent inchangés.",
  fileExportDefaults: "Valeurs d’export des fichiers",
  fileExportDefaultsDescription: "Format et qualité par défaut des nouveaux fichiers image exportés.",
  defaultGeneratedWatermark: "Signature du projet",
  defaultGeneratedWatermarkDescription: "Affiche la signature du projet sur les nouvelles cartes.",
  defaultSharedBy: "Crédit de partage",
  defaultSharedByDescription: "Affiche un crédit de partage sur les nouvelles cartes.",
  defaultSharedByText: "Texte de partage par défaut",
  defaultSharedByPlaceholder: "ex. Partagé par Cherry",
  exportFormat: "Format d’image par défaut",
  exportQuality: "Qualité d’image par défaut",
  low: "Standard · 1x",
  medium: "Élevée · 1,4x",
  high: "Maximale · 2x",
  version: "Version",
  checkUpdates: "Rechercher les mises à jour",
  githubProfile: "Profil GitHub",
  repository: "Dépôt du projet",
  releases: "Versions publiées",
  save: "Enregistrer",
  cancel: "Annuler",
  close: "Fermer",
  example: "Exemple",
  examples: "Exemples",
  loadExample: "Charger l’exemple",
  exampleLoaded: "Exemple chargé",
  originalLanguage: "Langue source",
  translationLanguage: "Langue de traduction",
  firstLaunchTitle: "Choisissez une langue",
  firstLaunchDescription: "Vous pourrez la modifier plus tard dans les paramètres.",
  projectDescription: "Créez des cartes de paroles depuis un lien musical ou un fichier audio.",
  licenses: "Licences et mentions",
  licensesDescription: "Ces documents sont inclus dans l’application et restent accessibles hors ligne.",
  sourceAvailableLicense: "Licence source-available de Lyrics Card Generator",
  thirdPartyNotices: "Mentions relatives aux tiers",
  sourceHanSansLicense: "Licence de Source Han Sans",
  sourceHanSerifLicense: "Licence de Source Han Serif",
  clearAll: "Effacer le contenu",
  clearAllDescription: "Efface la chanson en cours sans modifier les paramètres.",
  clearAlreadyEmpty: "La carte est déjà vide"
};

const ja: Copy = {
  settings: "設定",
  description: "アプリの表示と新しい歌詞カードの初期値を変更します。",
  general: "一般",
  appearance: "外観",
  export: "カードと書き出し",
  ai: "AI",
  about: "このアプリについて",
  generalDescription: "言語、操作、履歴、ストレージの設定です。",
  appearanceDescription: "表示モード、アクセントカラー、フォントを変更します。",
  exportDescription: "新しいカードのフッターと書き出し画像ファイルの初期値です。",
  aiDescription: "サービス接続と翻訳プロンプトを設定します。",
  aboutDescription: "バージョン、更新、プロジェクトのリンクです。",
  language: "言語",
  spark: "クリックエフェクト",
  sparkDescription: "クリックした場所に短い光のエフェクトを表示します。",
  reduceMotion: "動きを減らす",
  reduceMotionDescription: "画面の移動や完了時のアニメーションを減らします。システムの設定は常に優先されます。",
  interactionPreferences: "画面と操作",
  historyAndStorage: "履歴とストレージ",
  historyAndStorageDescription: "文書や保存内容を変えずに、自動履歴の管理とアプリ設定の復元を行います。",
  restoreAppPreferences: "アプリ設定を初期値に戻す",
  restoreAppPreferencesDescription: "画面、外観、カード／書き出しの初期値だけをリセットします。現在の文書、履歴、手動保存、AI API キーは保持されます。",
  restoreAppPreferencesConfirm: "画面、外観、カード／書き出しの初期値を復元しますか？現在の文書、履歴、手動保存、AI API キーは変更されません。",
  preferencesRestored: "アプリ設定を初期値に戻しました",
  retrySave: "保存を再試行",
  retryLoad: "読み込みを再試行",
  preferenceSaveFailed: "アプリ設定を保存できませんでした。",
  theme: "表示モード",
  albumDynamic: "ジャケットに合わせる",
  darkAcrylic: "ダーク Acrylic",
  lightAcrylic: "ライト Acrylic",
  acrylicEffect: "Acrylic 効果",
  acrylicSupportNote: "Acrylic は Windows のウィンドウ素材を使用するため、Windows 11 22H2 以降が必要です。その他の環境では透明な代替表示になります。",
  acrylicAlbumDisabled: "Acrylic ではジャケットに合わせた配色を使用できません。",
  accentColor: "アクセントカラー",
  accentAlbumDynamic: "ジャケットに合わせる",
  accentPreset: "プリセットカラー",
  accentCustom: "カラーコード",
  accentRed: "赤",
  accentOrange: "オレンジ",
  accentYellow: "黄",
  accentGreen: "緑",
  accentBlue: "青",
  accentPurple: "紫",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "#7C3AED のような 6 桁のカラーコードを入力してください。",
  uiFont: "画面のフォント",
  uiFontDescription: "font-family の一覧を入力します。CSS 関数や宣言は使用できません。",
  uiFontInvalid: "フォント名をカンマで区切って入力し、CSS 関数や宣言は使用しないでください。",
  restoreSystemFont: "システム標準に戻す",
  defaultFont: "システム標準",
  light: "ライト",
  dark: "ダーク",
  newCardDefaults: "新しいカードのフッター初期値",
  newCardDefaultsDescription: "本当に新しいカードを作るときだけ適用され、現在または読み込んだ文書は変更されません。",
  fileExportDefaults: "ファイル書き出しの初期値",
  fileExportDefaultsDescription: "新しく書き出す画像ファイルの既定の形式と品質です。",
  defaultGeneratedWatermark: "プロジェクト署名",
  defaultGeneratedWatermarkDescription: "新しいカードにプロジェクト署名を表示します。",
  defaultSharedBy: "共有者のクレジット",
  defaultSharedByDescription: "新しいカードに共有者のクレジットを表示します。",
  defaultSharedByText: "共有者の初期テキスト",
  defaultSharedByPlaceholder: "例：Shared by Cherry",
  exportFormat: "既定の画像形式",
  exportQuality: "既定の画像品質",
  low: "標準 · 1x",
  medium: "高画質 · 1.4x",
  high: "最高 · 2x",
  version: "バージョン",
  checkUpdates: "更新を確認",
  githubProfile: "GitHub プロフィール",
  repository: "プロジェクトのリポジトリ",
  releases: "リリース",
  save: "保存",
  cancel: "キャンセル",
  close: "閉じる",
  example: "サンプル",
  examples: "サンプル",
  loadExample: "サンプルを読み込む",
  exampleLoaded: "サンプルを読み込みました",
  originalLanguage: "原文の言語",
  translationLanguage: "翻訳先の言語",
  firstLaunchTitle: "表示言語を選択",
  firstLaunchDescription: "後から設定で変更できます。",
  projectDescription: "音楽リンクやローカル音声から歌詞カードを作成します。",
  licenses: "ライセンスと表示",
  licensesDescription: "これらの文書はアプリに同梱され、オフラインでも閲覧できます。",
  sourceAvailableLicense: "Lyrics Card Generator source-available ライセンス",
  thirdPartyNotices: "サードパーティ表示",
  sourceHanSansLicense: "Source Han Sans ライセンス",
  sourceHanSerifLicense: "Source Han Serif ライセンス",
  clearAll: "内容を消去",
  clearAllDescription: "設定を残して、現在の曲を消去します。",
  clearAlreadyEmpty: "カードはすでに空です"
};

const es: Copy = {
  settings: "Ajustes",
  description: "Cambia la interfaz y los valores predeterminados de las tarjetas nuevas.",
  general: "General",
  appearance: "Apariencia",
  export: "Tarjeta y exportación",
  ai: "IA",
  about: "Acerca de",
  generalDescription: "Preferencias de idioma, uso, historial y almacenamiento.",
  appearanceDescription: "Modo de interfaz, color de acento y tipografía.",
  exportDescription: "Valores predeterminados del pie de tarjetas nuevas y de los archivos exportados.",
  aiDescription: "Conexión con el servicio y prompts de traducción.",
  aboutDescription: "Versión, actualizaciones y enlaces del proyecto.",
  language: "Idioma",
  spark: "Efecto al hacer clic",
  sparkDescription: "Muestra un destello breve donde hagas clic.",
  reduceMotion: "Reducir movimiento",
  reduceMotionDescription: "Reduce los movimientos de la interfaz y las animaciones de celebración. La preferencia del sistema siempre tiene prioridad.",
  interactionPreferences: "Interfaz y uso",
  historyAndStorage: "Historial y almacenamiento",
  historyAndStorageDescription: "Gestiona el historial automático y restaura preferencias sin cambiar documentos ni guardados.",
  restoreAppPreferences: "Restaurar preferencias predeterminadas",
  restoreAppPreferencesDescription: "Restablece la interfaz, apariencia y valores de tarjeta/exportación. Conserva el documento, historial, guardados manuales y la clave API de IA.",
  restoreAppPreferencesConfirm: "¿Restaurar la interfaz, apariencia y valores de tarjeta/exportación? El documento, historial, guardados manuales y la clave API de IA no cambiarán.",
  preferencesRestored: "Preferencias de la aplicación restauradas",
  retrySave: "Reintentar guardado",
  retryLoad: "Reintentar carga",
  preferenceSaveFailed: "No se pudieron guardar las preferencias de la aplicación.",
  theme: "Modo de interfaz",
  albumDynamic: "Según la portada",
  darkAcrylic: "Acrylic oscuro",
  lightAcrylic: "Acrylic claro",
  acrylicEffect: "Efecto Acrylic",
  acrylicSupportNote: "Acrylic usa el material de ventana de Windows y requiere Windows 11 22H2 o posterior. En otros sistemas se usa un fondo transparente alternativo.",
  acrylicAlbumDisabled: "Los colores de la portada no están disponibles con Acrylic.",
  accentColor: "Color de acento",
  accentAlbumDynamic: "Según la portada",
  accentPreset: "Colores predefinidos",
  accentCustom: "Código hexadecimal",
  accentRed: "Rojo",
  accentOrange: "Naranja",
  accentYellow: "Amarillo",
  accentGreen: "Verde",
  accentBlue: "Azul",
  accentPurple: "Morado",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "Escribe un color hexadecimal de 6 dígitos, por ejemplo #7C3AED.",
  uiFont: "Fuente de la interfaz",
  uiFontDescription: "Escribe una lista font-family. No se permiten funciones ni declaraciones CSS.",
  uiFontInvalid: "Escribe nombres de fuentes separados por comas, sin funciones ni declaraciones CSS.",
  restoreSystemFont: "Restaurar fuente del sistema",
  defaultFont: "Fuente del sistema",
  light: "Claro",
  dark: "Oscuro",
  newCardDefaults: "Valores del pie de tarjetas nuevas",
  newCardDefaultsDescription: "Se aplican solo a una tarjeta realmente nueva; los documentos actuales y cargados no cambian.",
  fileExportDefaults: "Valores de exportación de archivos",
  fileExportDefaultsDescription: "Formato y calidad predeterminados para nuevos archivos de imagen exportados.",
  defaultGeneratedWatermark: "Firma del proyecto",
  defaultGeneratedWatermarkDescription: "Muestra la firma del proyecto en las tarjetas nuevas.",
  defaultSharedBy: "Crédito de autor",
  defaultSharedByDescription: "Muestra un crédito de autor en las tarjetas nuevas.",
  defaultSharedByText: "Texto de autor predeterminado",
  defaultSharedByPlaceholder: "p. ej. Compartido por Cherry",
  exportFormat: "Formato de imagen predeterminado",
  exportQuality: "Calidad de imagen predeterminada",
  low: "Estándar · 1x",
  medium: "Alta · 1,4x",
  high: "Máxima · 2x",
  version: "Versión",
  checkUpdates: "Buscar actualizaciones",
  githubProfile: "Perfil de GitHub",
  repository: "Repositorio del proyecto",
  releases: "Versiones publicadas",
  save: "Guardar",
  cancel: "Cancelar",
  close: "Cerrar",
  example: "Ejemplo",
  examples: "Ejemplos",
  loadExample: "Cargar ejemplo",
  exampleLoaded: "Ejemplo cargado",
  originalLanguage: "Idioma de origen",
  translationLanguage: "Idioma de traducción",
  firstLaunchTitle: "Elige un idioma",
  firstLaunchDescription: "Podrás cambiarlo más tarde en Ajustes.",
  projectDescription: "Crea tarjetas de letras desde enlaces de música o archivos de audio.",
  licenses: "Licencias y avisos",
  licensesDescription: "Estos documentos se incluyen con la aplicación y están disponibles sin conexión.",
  sourceAvailableLicense: "Licencia source-available de Lyrics Card Generator",
  thirdPartyNotices: "Avisos de terceros",
  sourceHanSansLicense: "Licencia de Source Han Sans",
  sourceHanSerifLicense: "Licencia de Source Han Serif",
  clearAll: "Borrar contenido",
  clearAllDescription: "Borra la canción actual sin cambiar los ajustes.",
  clearAlreadyEmpty: "La tarjeta ya está vacía"
};

export const settingsCopy: Record<Locale, Copy> = {
  zh,
  "zh-TW": zhTW,
  en,
  fr,
  ja,
  es
};
