import type { Locale } from "@/lib/types";

const en = {
  settings: "Settings",
  description: "Change the app interface and defaults for new lyric cards.",
  general: "General",
  appearance: "Appearance",
  background: "Background",
  export: "Export",
  ai: "AI",
  about: "About",
  generalDescription: "Language and interaction preferences.",
  appearanceDescription: "Interface mode, accent color, and font.",
  exportDescription: "Default card credits, image format, and quality.",
  aiDescription: "Provider connection and translation prompts.",
  aboutDescription: "Version, updates, and project links.",
  language: "Language",
  spark: "Click effect",
  sparkDescription: "Show a brief spark where you click.",
  reduceMotion: "Reduce motion",
  reduceMotionDescription: "Use fewer interface movements and celebration effects. The system setting is always respected.",
  theme: "Interface mode",
  albumDynamic: "Match album cover",
  darkAcrylic: "Dark Acrylic",
  lightAcrylic: "Light Acrylic",
  acrylicEffect: "Acrylic effect",
  acrylicSupportNote: "Acrylic uses the Windows window material and requires Windows 11 22H2 or later. Other systems use a transparent fallback.",
  acrylicAlbumDisabled: "Album-cover colors are not available with Acrylic.",
  accentColor: "Accent color",
  accentAlbumDynamic: "Match album cover",
  accentPreset: "Preset colors",
  accentCustom: "Custom hex",
  accentRed: "Red",
  accentOrange: "Orange",
  accentYellow: "Yellow",
  accentGreen: "Green",
  accentBlue: "Blue",
  accentPurple: "Purple",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "Enter a 6-digit hex color, such as #7C3AED.",
  uiFont: "Interface font",
  defaultFont: "System default",
  light: "Light",
  dark: "Dark",
  source: "Source",
  solid: "Solid color",
  image: "Image",
  chooseImage: "Choose image",
  stretch: "Stretch",
  contain: "Fit",
  cover: "Fill",
  blur: "Blur",
  palette: "Use image colors",
  overlay: "Overlay",
  blurAmount: "Blur amount",
  resetBackground: "Reset background",
  defaultGeneratedWatermark: "App watermark",
  defaultGeneratedWatermarkDescription: "Show the app watermark on new cards.",
  defaultSharedBy: "Sharer credit",
  defaultSharedByDescription: "Show a sharer credit on new cards.",
  defaultSharedByText: "Default sharer text",
  defaultSharedByPlaceholder: "e.g. Shared by Cherry",
  exportFormat: "Default image format",
  exportQuality: "Default image quality",
  low: "Standard · 1x",
  medium: "High · 1.4x",
  high: "Maximum · 2x",
  version: "Version",
  checkUpdates: "Check for updates",
  githubProfile: "GitHub profile",
  repository: "Project repository",
  releases: "Releases",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  example: "Example",
  examples: "Examples",
  loadExample: "Load example",
  exampleLoaded: "Example loaded",
  originalLanguage: "Source language",
  translationLanguage: "Translation language",
  firstLaunchTitle: "Choose a language",
  firstLaunchDescription: "You can change this later in Settings.",
  projectDescription: "Create lyric cards from music links or local audio.",
  clearAll: "Clear content",
  clearAllDescription: "Clear the current song and keep app settings.",
  clearAlreadyEmpty: "The card is already empty.",
  backgroundImageSelected: "Background image saved.",
  backgroundImageFailed: "The background image could not be opened.",
  backgroundSaveFailed: "Settings were saved, but the previous background image could not be removed.",
  backgroundResetPending: "Background reset."
};

type Copy = typeof en;

const zh: Copy = {
  settings: "设置",
  description: "调整软件界面和新歌词卡片的默认设置。",
  general: "通用",
  appearance: "外观",
  background: "背景",
  export: "导出",
  ai: "AI",
  about: "关于",
  generalDescription: "语言和交互偏好。",
  appearanceDescription: "界面模式、主题色和字体。",
  exportDescription: "卡片署名和默认图片格式、质量。",
  aiDescription: "服务连接和翻译提示词。",
  aboutDescription: "版本、更新和项目链接。",
  language: "语言",
  spark: "点击特效",
  sparkDescription: "点击界面时显示短暂的火花效果。",
  reduceMotion: "减弱动效",
  reduceMotionDescription: "减少界面位移和庆祝动画；系统的减弱动态效果设置始终生效。",
  theme: "界面模式",
  albumDynamic: "跟随专辑封面",
  darkAcrylic: "深色亚克力",
  lightAcrylic: "浅色亚克力",
  acrylicEffect: "亚克力效果",
  acrylicSupportNote: "亚克力使用 Windows 窗口材质，需要 Windows 11 22H2 或更高版本；其他系统使用透明备用样式。",
  acrylicAlbumDisabled: "亚克力模式暂不支持跟随专辑封面配色。",
  accentColor: "主题色",
  accentAlbumDynamic: "跟随专辑封面",
  accentPreset: "预设颜色",
  accentCustom: "自定义色号",
  accentRed: "红色",
  accentOrange: "橙色",
  accentYellow: "黄色",
  accentGreen: "绿色",
  accentBlue: "蓝色",
  accentPurple: "紫色",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "请输入 6 位十六进制颜色，例如 #7C3AED。",
  uiFont: "界面字体",
  defaultFont: "系统默认",
  light: "浅色",
  dark: "深色",
  source: "背景来源",
  solid: "纯色",
  image: "图片",
  chooseImage: "选择图片",
  stretch: "拉伸",
  contain: "完整显示",
  cover: "裁切填充",
  blur: "模糊",
  palette: "使用图片配色",
  overlay: "遮罩",
  blurAmount: "模糊程度",
  resetBackground: "重置背景",
  defaultGeneratedWatermark: "软件水印",
  defaultGeneratedWatermarkDescription: "新卡片默认显示软件水印。",
  defaultSharedBy: "分享人署名",
  defaultSharedByDescription: "新卡片默认显示分享人署名。",
  defaultSharedByText: "默认分享人文字",
  defaultSharedByPlaceholder: "例如：Shared by Cherry",
  exportFormat: "默认图片格式",
  exportQuality: "默认图片质量",
  low: "标准 · 1x",
  medium: "高清 · 1.4x",
  high: "最高 · 2x",
  version: "版本",
  checkUpdates: "检查更新",
  githubProfile: "GitHub 主页",
  repository: "项目仓库",
  releases: "发布页面",
  save: "保存",
  cancel: "取消",
  close: "关闭",
  example: "示例",
  examples: "示例",
  loadExample: "载入示例",
  exampleLoaded: "已载入示例",
  originalLanguage: "原文语言",
  translationLanguage: "译文语言",
  firstLaunchTitle: "选择界面语言",
  firstLaunchDescription: "之后可以随时在设置中更改。",
  projectDescription: "从音乐链接或本地音频制作歌词卡片。",
  clearAll: "清空内容",
  clearAllDescription: "清空当前歌曲，保留软件设置。",
  clearAlreadyEmpty: "卡片已经是空的。",
  backgroundImageSelected: "背景图片已保存。",
  backgroundImageFailed: "无法打开背景图片。",
  backgroundSaveFailed: "设置已保存，但无法删除之前的背景图片。",
  backgroundResetPending: "背景已重置。"
};

const zhTW: Copy = {
  settings: "設定",
  description: "調整應用程式介面與新歌詞卡片的預設值。",
  general: "一般",
  appearance: "外觀",
  background: "背景",
  export: "匯出",
  ai: "AI",
  about: "關於",
  generalDescription: "語言與操作偏好。",
  appearanceDescription: "介面模式、強調色與字型。",
  exportDescription: "卡片署名與預設圖片格式、品質。",
  aiDescription: "服務連線與翻譯提示詞。",
  aboutDescription: "版本、更新與專案連結。",
  language: "語言",
  spark: "點擊特效",
  sparkDescription: "點擊介面時顯示短暫的火花效果。",
  reduceMotion: "減少動態效果",
  reduceMotionDescription: "減少介面移動與慶祝動畫；系統的動態效果設定一律優先套用。",
  theme: "介面模式",
  albumDynamic: "配合專輯封面",
  darkAcrylic: "深色壓克力",
  lightAcrylic: "淺色壓克力",
  acrylicEffect: "壓克力效果",
  acrylicSupportNote: "壓克力使用 Windows 視窗材質，需要 Windows 11 22H2 或更新版本；其他系統會改用透明備用樣式。",
  acrylicAlbumDisabled: "壓克力模式目前不支援配合專輯封面取色。",
  accentColor: "強調色",
  accentAlbumDynamic: "配合專輯封面",
  accentPreset: "預設顏色",
  accentCustom: "自訂色碼",
  accentRed: "紅色",
  accentOrange: "橘色",
  accentYellow: "黃色",
  accentGreen: "綠色",
  accentBlue: "藍色",
  accentPurple: "紫色",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "請輸入 6 位十六進位色碼，例如 #7C3AED。",
  uiFont: "介面字型",
  defaultFont: "系統預設",
  light: "淺色",
  dark: "深色",
  source: "背景來源",
  solid: "純色",
  image: "圖片",
  chooseImage: "選擇圖片",
  stretch: "延展",
  contain: "完整顯示",
  cover: "裁切填滿",
  blur: "模糊",
  palette: "使用圖片配色",
  overlay: "遮罩",
  blurAmount: "模糊程度",
  resetBackground: "重設背景",
  defaultGeneratedWatermark: "應用程式浮水印",
  defaultGeneratedWatermarkDescription: "新卡片預設顯示應用程式浮水印。",
  defaultSharedBy: "分享者署名",
  defaultSharedByDescription: "新卡片預設顯示分享者署名。",
  defaultSharedByText: "預設分享者文字",
  defaultSharedByPlaceholder: "例如：Shared by Cherry",
  exportFormat: "預設圖片格式",
  exportQuality: "預設圖片品質",
  low: "標準 · 1x",
  medium: "高畫質 · 1.4x",
  high: "最高 · 2x",
  version: "版本",
  checkUpdates: "檢查更新",
  githubProfile: "GitHub 個人頁面",
  repository: "專案原始碼",
  releases: "發行版本",
  save: "儲存",
  cancel: "取消",
  close: "關閉",
  example: "範例",
  examples: "範例",
  loadExample: "載入範例",
  exampleLoaded: "已載入範例",
  originalLanguage: "原文語言",
  translationLanguage: "譯文語言",
  firstLaunchTitle: "選擇介面語言",
  firstLaunchDescription: "之後可以隨時在設定中更改。",
  projectDescription: "從音樂連結或本機音訊製作歌詞卡片。",
  clearAll: "清除內容",
  clearAllDescription: "清除目前歌曲，保留應用程式設定。",
  clearAlreadyEmpty: "卡片已經是空的。",
  backgroundImageSelected: "背景圖片已儲存。",
  backgroundImageFailed: "無法開啟背景圖片。",
  backgroundSaveFailed: "設定已儲存，但無法刪除先前的背景圖片。",
  backgroundResetPending: "背景已重設。"
};

const fr: Copy = {
  settings: "Paramètres",
  description: "Modifiez l’interface et les valeurs par défaut des nouvelles cartes.",
  general: "Général",
  appearance: "Apparence",
  background: "Arrière-plan",
  export: "Export",
  ai: "IA",
  about: "À propos",
  generalDescription: "Langue et préférences d’utilisation.",
  appearanceDescription: "Mode d’affichage, couleur d’accent et police.",
  exportDescription: "Crédits, format et qualité d’image par défaut des cartes.",
  aiDescription: "Connexion au service et prompts de traduction.",
  aboutDescription: "Version, mises à jour et liens du projet.",
  language: "Langue",
  spark: "Effet au clic",
  sparkDescription: "Affiche une brève étincelle à chaque clic.",
  reduceMotion: "Réduire les animations",
  reduceMotionDescription: "Limite les mouvements de l’interface et les animations de fin. Le réglage du système reste prioritaire.",
  theme: "Mode d’affichage",
  albumDynamic: "Selon la pochette",
  darkAcrylic: "Acrylic sombre",
  lightAcrylic: "Acrylic clair",
  acrylicEffect: "Effet Acrylic",
  acrylicSupportNote: "Acrylic utilise le matériau de fenêtre de Windows et nécessite Windows 11 22H2 ou une version ultérieure. Ailleurs, un fond transparent est utilisé.",
  acrylicAlbumDisabled: "Les couleurs de la pochette ne sont pas disponibles avec Acrylic.",
  accentColor: "Couleur d’accent",
  accentAlbumDynamic: "Selon la pochette",
  accentPreset: "Couleurs prédéfinies",
  accentCustom: "Code hexadécimal",
  accentRed: "Rouge",
  accentOrange: "Orange",
  accentYellow: "Jaune",
  accentGreen: "Vert",
  accentBlue: "Bleu",
  accentPurple: "Violet",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "Saisissez un code hexadécimal à 6 chiffres, par exemple #7C3AED.",
  uiFont: "Police de l’interface",
  defaultFont: "Police du système",
  light: "Clair",
  dark: "Sombre",
  source: "Source",
  solid: "Couleur unie",
  image: "Image",
  chooseImage: "Choisir une image",
  stretch: "Étirer",
  contain: "Ajuster",
  cover: "Remplir",
  blur: "Flou",
  palette: "Couleurs de l’image",
  overlay: "Voile",
  blurAmount: "Intensité du flou",
  resetBackground: "Réinitialiser l’arrière-plan",
  defaultGeneratedWatermark: "Filigrane de l’application",
  defaultGeneratedWatermarkDescription: "Affiche le filigrane de l’application sur les nouvelles cartes.",
  defaultSharedBy: "Crédit de partage",
  defaultSharedByDescription: "Affiche un crédit de partage sur les nouvelles cartes.",
  defaultSharedByText: "Texte de partage par défaut",
  defaultSharedByPlaceholder: "ex. Partagé par Cherry",
  exportFormat: "Format d’image par défaut",
  exportQuality: "Qualité d’image par défaut",
  low: "Standard · 1x",
  medium: "Élevée · 1,4x",
  high: "Maximale · 2x",
  version: "Version",
  checkUpdates: "Rechercher les mises à jour",
  githubProfile: "Profil GitHub",
  repository: "Dépôt du projet",
  releases: "Versions publiées",
  save: "Enregistrer",
  cancel: "Annuler",
  close: "Fermer",
  example: "Exemple",
  examples: "Exemples",
  loadExample: "Charger l’exemple",
  exampleLoaded: "Exemple chargé",
  originalLanguage: "Langue source",
  translationLanguage: "Langue de traduction",
  firstLaunchTitle: "Choisissez une langue",
  firstLaunchDescription: "Vous pourrez la modifier plus tard dans les paramètres.",
  projectDescription: "Créez des cartes de paroles depuis un lien musical ou un fichier audio.",
  clearAll: "Effacer le contenu",
  clearAllDescription: "Efface la chanson en cours sans modifier les paramètres.",
  clearAlreadyEmpty: "La carte est déjà vide.",
  backgroundImageSelected: "Image d’arrière-plan enregistrée.",
  backgroundImageFailed: "Impossible d’ouvrir l’image d’arrière-plan.",
  backgroundSaveFailed: "Les paramètres ont été enregistrés, mais l’ancienne image d’arrière-plan n’a pas pu être supprimée.",
  backgroundResetPending: "Arrière-plan réinitialisé."
};

const ja: Copy = {
  settings: "設定",
  description: "アプリの表示と新しい歌詞カードの初期値を変更します。",
  general: "一般",
  appearance: "外観",
  background: "背景",
  export: "書き出し",
  ai: "AI",
  about: "このアプリについて",
  generalDescription: "言語と操作の設定です。",
  appearanceDescription: "表示モード、アクセントカラー、フォントを変更します。",
  exportDescription: "カードのクレジット、画像形式、品質の初期値です。",
  aiDescription: "サービス接続と翻訳プロンプトを設定します。",
  aboutDescription: "バージョン、更新、プロジェクトのリンクです。",
  language: "言語",
  spark: "クリックエフェクト",
  sparkDescription: "クリックした場所に短い光のエフェクトを表示します。",
  reduceMotion: "動きを減らす",
  reduceMotionDescription: "画面の移動や完了時のアニメーションを減らします。システムの設定は常に優先されます。",
  theme: "表示モード",
  albumDynamic: "ジャケットに合わせる",
  darkAcrylic: "ダーク Acrylic",
  lightAcrylic: "ライト Acrylic",
  acrylicEffect: "Acrylic 効果",
  acrylicSupportNote: "Acrylic は Windows のウィンドウ素材を使用するため、Windows 11 22H2 以降が必要です。その他の環境では透明な代替表示になります。",
  acrylicAlbumDisabled: "Acrylic ではジャケットに合わせた配色を使用できません。",
  accentColor: "アクセントカラー",
  accentAlbumDynamic: "ジャケットに合わせる",
  accentPreset: "プリセットカラー",
  accentCustom: "カラーコード",
  accentRed: "赤",
  accentOrange: "オレンジ",
  accentYellow: "黄",
  accentGreen: "緑",
  accentBlue: "青",
  accentPurple: "紫",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "#7C3AED のような 6 桁のカラーコードを入力してください。",
  uiFont: "画面のフォント",
  defaultFont: "システム標準",
  light: "ライト",
  dark: "ダーク",
  source: "背景の種類",
  solid: "単色",
  image: "画像",
  chooseImage: "画像を選択",
  stretch: "引き伸ばす",
  contain: "全体を表示",
  cover: "いっぱいに表示",
  blur: "ぼかし",
  palette: "画像の色を使う",
  overlay: "オーバーレイ",
  blurAmount: "ぼかしの強さ",
  resetBackground: "背景をリセット",
  defaultGeneratedWatermark: "アプリのウォーターマーク",
  defaultGeneratedWatermarkDescription: "新しいカードにアプリのウォーターマークを表示します。",
  defaultSharedBy: "共有者のクレジット",
  defaultSharedByDescription: "新しいカードに共有者のクレジットを表示します。",
  defaultSharedByText: "共有者の初期テキスト",
  defaultSharedByPlaceholder: "例：Shared by Cherry",
  exportFormat: "既定の画像形式",
  exportQuality: "既定の画像品質",
  low: "標準 · 1x",
  medium: "高画質 · 1.4x",
  high: "最高 · 2x",
  version: "バージョン",
  checkUpdates: "更新を確認",
  githubProfile: "GitHub プロフィール",
  repository: "プロジェクトのリポジトリ",
  releases: "リリース",
  save: "保存",
  cancel: "キャンセル",
  close: "閉じる",
  example: "サンプル",
  examples: "サンプル",
  loadExample: "サンプルを読み込む",
  exampleLoaded: "サンプルを読み込みました",
  originalLanguage: "原文の言語",
  translationLanguage: "翻訳先の言語",
  firstLaunchTitle: "表示言語を選択",
  firstLaunchDescription: "後から設定で変更できます。",
  projectDescription: "音楽リンクやローカル音声から歌詞カードを作成します。",
  clearAll: "内容を消去",
  clearAllDescription: "設定を残して、現在の曲を消去します。",
  clearAlreadyEmpty: "カードはすでに空です。",
  backgroundImageSelected: "背景画像を保存しました。",
  backgroundImageFailed: "背景画像を開けませんでした。",
  backgroundSaveFailed: "設定は保存されましたが、以前の背景画像を削除できませんでした。",
  backgroundResetPending: "背景をリセットしました。"
};

const es: Copy = {
  settings: "Ajustes",
  description: "Cambia la interfaz y los valores predeterminados de las tarjetas nuevas.",
  general: "General",
  appearance: "Apariencia",
  background: "Fondo",
  export: "Exportación",
  ai: "IA",
  about: "Acerca de",
  generalDescription: "Idioma y preferencias de uso.",
  appearanceDescription: "Modo de interfaz, color de acento y tipografía.",
  exportDescription: "Créditos, formato y calidad de imagen predeterminados de la tarjeta.",
  aiDescription: "Conexión con el servicio y prompts de traducción.",
  aboutDescription: "Versión, actualizaciones y enlaces del proyecto.",
  language: "Idioma",
  spark: "Efecto al hacer clic",
  sparkDescription: "Muestra un destello breve donde hagas clic.",
  reduceMotion: "Reducir movimiento",
  reduceMotionDescription: "Reduce los movimientos de la interfaz y las animaciones de celebración. La preferencia del sistema siempre tiene prioridad.",
  theme: "Modo de interfaz",
  albumDynamic: "Según la portada",
  darkAcrylic: "Acrylic oscuro",
  lightAcrylic: "Acrylic claro",
  acrylicEffect: "Efecto Acrylic",
  acrylicSupportNote: "Acrylic usa el material de ventana de Windows y requiere Windows 11 22H2 o posterior. En otros sistemas se usa un fondo transparente alternativo.",
  acrylicAlbumDisabled: "Los colores de la portada no están disponibles con Acrylic.",
  accentColor: "Color de acento",
  accentAlbumDynamic: "Según la portada",
  accentPreset: "Colores predefinidos",
  accentCustom: "Código hexadecimal",
  accentRed: "Rojo",
  accentOrange: "Naranja",
  accentYellow: "Amarillo",
  accentGreen: "Verde",
  accentBlue: "Azul",
  accentPurple: "Morado",
  accentCustomPlaceholder: "#7C3AED",
  accentInvalid: "Escribe un color hexadecimal de 6 dígitos, por ejemplo #7C3AED.",
  uiFont: "Fuente de la interfaz",
  defaultFont: "Fuente del sistema",
  light: "Claro",
  dark: "Oscuro",
  source: "Origen",
  solid: "Color sólido",
  image: "Imagen",
  chooseImage: "Elegir imagen",
  stretch: "Estirar",
  contain: "Ajustar",
  cover: "Rellenar",
  blur: "Desenfoque",
  palette: "Usar colores de la imagen",
  overlay: "Capa",
  blurAmount: "Intensidad del desenfoque",
  resetBackground: "Restablecer fondo",
  defaultGeneratedWatermark: "Marca de agua de la aplicación",
  defaultGeneratedWatermarkDescription: "Muestra la marca de agua de la aplicación en las tarjetas nuevas.",
  defaultSharedBy: "Crédito de autor",
  defaultSharedByDescription: "Muestra un crédito de autor en las tarjetas nuevas.",
  defaultSharedByText: "Texto de autor predeterminado",
  defaultSharedByPlaceholder: "p. ej. Compartido por Cherry",
  exportFormat: "Formato de imagen predeterminado",
  exportQuality: "Calidad de imagen predeterminada",
  low: "Estándar · 1x",
  medium: "Alta · 1,4x",
  high: "Máxima · 2x",
  version: "Versión",
  checkUpdates: "Buscar actualizaciones",
  githubProfile: "Perfil de GitHub",
  repository: "Repositorio del proyecto",
  releases: "Versiones publicadas",
  save: "Guardar",
  cancel: "Cancelar",
  close: "Cerrar",
  example: "Ejemplo",
  examples: "Ejemplos",
  loadExample: "Cargar ejemplo",
  exampleLoaded: "Ejemplo cargado",
  originalLanguage: "Idioma de origen",
  translationLanguage: "Idioma de traducción",
  firstLaunchTitle: "Elige un idioma",
  firstLaunchDescription: "Podrás cambiarlo más tarde en Ajustes.",
  projectDescription: "Crea tarjetas de letras desde enlaces de música o archivos de audio.",
  clearAll: "Borrar contenido",
  clearAllDescription: "Borra la canción actual sin cambiar los ajustes.",
  clearAlreadyEmpty: "La tarjeta ya está vacía.",
  backgroundImageSelected: "Imagen de fondo guardada.",
  backgroundImageFailed: "No se pudo abrir la imagen de fondo.",
  backgroundSaveFailed: "Los ajustes se guardaron, pero no se pudo eliminar la imagen de fondo anterior.",
  backgroundResetPending: "Fondo restablecido."
};

export const settingsCopy: Record<Locale, Copy> = {
  zh,
  "zh-TW": zhTW,
  en,
  fr,
  ja,
  es
};
