import type { ToastNotifier } from "@/components/feedback/AppToast";
import type { useEditorAutosave } from "./useEditorAutosave";
import type { AppState } from "@/lib/types";
import type { ExportFormatId } from "@/lib/settings/types";
import type { ExportSnapshot } from "@/lib/export-snapshot";
import type { EditorAILifecycle } from "@/lib/editor/editor-ai-lifecycle";
export type UseEditorActionsInput = {
  autosave: ReturnType<typeof useEditorAutosave>;
  parsedState: AppState;
  setState: React.Dispatch<React.SetStateAction<AppState>>;
  cardRef: React.RefObject<HTMLElement | null>;
  exportPixelRatio: number;
  exportFormat: ExportFormatId;
  exportBlockMessage?: string;
  getExportBlockMessage?: (snapshot?: ExportSnapshot) => string | undefined;
  exportBusyMessage: string;
  exportFailedMessage: string;
  copyImageSuccessMessage: string;
  copyImageFailedMessage: string;
  exportImageTooLargeMessage: string;
  exampleLoadedMessage: string;
  clearAlreadyEmptyMessage: string;
  confirmReplaceDocument: () => Promise<boolean>;
  onNotify: ToastNotifier;
  onCloseExamples: () => void;
  onCloseHistory: () => void;
  onClearTransientState: () => void;
  aiLifecycle: EditorAILifecycle;
};
