"use client";

export function GeneratedWatermark({ color, variant = "portrait" }: { color: string; variant?: "portrait" | "landscape" }) {
  const isLandscape = variant === "landscape";

  return (
    <div
      className="flex w-full items-center justify-center gap-6 opacity-[0.88]"
      style={{
        color,
        fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
      }}
    >
      <div className={isLandscape ? "h-px w-28 bg-current/35" : "h-px min-w-12 max-w-44 flex-1 bg-current/45"} />
      <span className={isLandscape ? "shrink-0 whitespace-nowrap text-[16px] font-light tracking-[0.22em] text-current/75 drop-shadow-sm" : "shrink-0 whitespace-nowrap text-[18px] font-light tracking-[0.2em] text-current/85 drop-shadow-sm"}>
        generated by lyric card generator
      </span>
      <div className={isLandscape ? "h-px w-28 bg-current/35" : "h-px min-w-12 max-w-44 flex-1 bg-current/45"} />
    </div>
  );
}
